### ISSUE TITLE
[spring-server]: jcenter required for transitive com.apollographql.federation dependency

### ISSUE THREAD

**Issue by rowi1de** [ExpediaGroup/graphql-kotlin#1033]
**Library Version**
- com.expediagroup:graphql-kotlin-spring-server:3.7.0

**Describe the bug**
On upgrading from `com.expediagroup:graphql-kotlin-spring-server:3.6.5` to "com.expediagroup:graphql-kotlin-spring-server:3.7.0" the transitive dependency can only be resolved with jcenter - maven repo: `com.apollographql.federation:federation-graphql-java-support:0.5.0` 

I don't include any other "com.expediagroup:graphql-*" dependencies
Getting this error:

```bash
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.apollographql.federation:federation-graphql-java-support:0.5.0.
     Required by:
         project : > com.expediagroup:graphql-kotlin-spring-server:3.7.0
         project : > com.expediagroup:graphql-kotlin-spring-server:3.7.0 > com.expediagroup:graphql-kotlin-federation:3.7.0

```
**To Reproduce**
Steps to reproduce the behavior. Please provide:
-  use `com.expediagroup:graphql-kotlin-spring-server:3.7.0`
- don't use jcenter repository 

**Expected behavior**
- `com.expediagroup:graphql-kotlin-spring-server:3.7.0` is self contained / doesn't have additional transitive dependencies that can only be resolved within a specific repo

```kotlin
repositories {
    mavenLocal()
    mavenCentral()
    jcenter() // FIXME: graphql-kotlin 3.6.5 => 3.7.x uncomment to break
}

dependencies {
    implementation("com.expediagroup:graphql-kotlin-spring-server:3.7.0")
    //implementation("com.expediagroup:graphql-kotlin-spring-server:3.6.5") worked without JCenter?
}

```

**Comment by dariuszkuc** [comment]
We were thinking about using shade plugin to avoid this issue but since [JCenter is going away on May 1st](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) we might not need to do it. Raised https://github.com/apollographql/federation-jvm/issues/91 asking Apollo to start publishing to MavenCentral.

**Comment by smyrick** [comment]
Resolved with https://github.com/ExpediaGroup/graphql-kotlin/pull/1184
