### ISSUE TITLE
Docs link redirects to nonexistent landing page

### ISSUE THREAD

**Issue by okarmazin** [ExpediaGroup/graphql-kotlin#1043]
https://expediagroup.github.io/graphql-kotlin

Redirects to https://expediagroup.github.io/graphql-kotlin/docs/id-of-doc-to-land-on.html

**Comment by dariuszkuc** [comment]
I tried reproducing it in a number of browsers (Chrome, Safari, Edge) and on both Mac and Windows and it always redirects correctly to me as defined in the [index.html](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/website/static/index.html#L23).

**Comment by smyrick** [comment]
Thanks for the bug report!
