### ISSUE TITLE
Handling of GraphQLErrors in KotlinDataFetcherExceptionHandler

### ISSUE THREAD

**Issue by hsudbrock** [ExpediaGroup/graphql-kotlin#1062]
[The KDoc](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/exception/KotlinDataFetcherExceptionHandler.kt) of `KotlinDataFetcherExceptionHandler` states:
> All exceptions thrown during GraphQL execution are logged and then returned as wrapped ExceptionWhileDataFetching error if they are not a valid GraphQLError

However, the actual implementation also wraps valid `GraphQLError` exceptions as an `ExceptionWhileDataFetching`, instead of passing those directly into the `DataFetcherExceptionHandlerResult`.

Do I misunderstand the KDoc, or is this a small issue that needs to be fixed? (If it needs to be fixed, I would of course be willing to provide a fix - I'd just like to clarify whether this actually is an issue first).

I think that *not* wrapping `GraphQLError` instances in an `ExceptionWhileDataFetching` would be beneficial, because it would allow implementors to define the error message displayed in the graphql response, while currently the error message from the original `GraphQLError` is modified by the `KotlinGraphQLError`.

**Comment by dariuszkuc** [comment]
Hello 👋 
It looks like `KDoc` wasn't updated. The reason why we wrap the exceptions in `KotlinGraphQLError` is to ensure proper serialization of error response -> i.e. we rely on Jackson which uses reflections to serialize all fields that have getters. So if you throw any of the `graphql-java` `GraphQLErrors` your exception field will also be serialized. I think we probably should update it to check if it is already an instance of `KotlinGraphQLError` and only wrap it if it is not.
