### ISSUE TITLE
What is the recommended way for configuring customScalars for the maven plugin?

### ISSUE THREAD

**Issue by ssullivan** [ExpediaGroup/graphql-kotlin#1067]
I am testing the latest alpha version of this library that I could find: 4.0.0-alpha.14

I've created a project: [https://github.com/ssullivan/graphql-kotlin-customscalar-exampl](https://github.com/ssullivan/graphql-kotlin-customscalar-example) based on the example maven-client project from this repository. I've a made few small mods to the maven setup and customized the queries, and graphql schema so I can test out the plugin.

The customScalars that are specified don't appear to be used by the generated code. It looks like only the type aliases defined defined in `GraphQLTypeAliases.kt` are being utilized.

I noticed that the `GenerateClientAbstractMojo.kt` has a parameter defined [here](https://github.com/ExpediaGroup/graphql-kotlin/blob/4a89a8b183defa6a1f25494f2f9f90753f2723b2/plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientAbstractMojo.kt#L73):

```kotlin
@Parameter(name = "converters")
private var customScalars: List<CustomScalar> mutableListOf()
```

I checked out the graphql-kotlin master branch and modified this section of code locally to look like the following

```kotlin
@Parameter(name = "customScalars")
private var customScalars: List<CustomScalar> mutableListOf()
```

After making this change my generated code is using the converter specified by the CustomScalar configuration.

Am I just configuring things wrong here or is this a bug?

**Comment by dariuszkuc** [comment]
Hello. Thanks for raising this. It is indeed a bug (I hit the same problem when working on adding kotlinx serialization support).
