### ISSUE TITLE
Usage in multi-module project

### ISSUE THREAD

**Issue by akullpp** [ExpediaGroup/graphql-kotlin#1071]
Given the following structure:

```
build.gradle.kts

settings.gradle.kts

src/
  Application.kt

api/
  build.gradle.kts
  Queries.kt
  Mutations.kt
```
I added the dependency to the `root/build.gradle.kts` and `api/build.gradle.kts` so it picks up the resolvers correctly but when Spring Boot's Tomcat starts, neither it does register playground nor is the `/graphql` endpoint available. 

Is it possible to use this library with the default Spring Boot Tomcat, put the resolvers in submodules where they get picked up and a servlet registered somehow?

**Comment by akullpp** [comment]
I guess it's not possible since this library is based on Netty and can't work with Tomcat :-/

**Comment by dariuszkuc** [comment]
You can still use schema generator - as for the server part yes you would need to implement your own tomcat compatible one.
