### ISSUE TITLE
GraphQL endpoints observe the Reactive Spring Boot context path, but Playground tries to reach /graphql

### ISSUE THREAD

**Issue by joaodias14** [ExpediaGroup/graphql-kotlin#1097]
**Library Version**
3.6.8

**Describe the bug**
GraphQL endpoints observe the Reactive Spring Boot context path, but Playground tries to reach /graphql without including the context path. I haven't tried it but I would say the same is true for the Servlet stack.

**To Reproduce**
1. Create a Reactive Spring Boot application and configure its context path using `spring.webflux.base-path`;
2. Access Playground in the browser using `{domain}/{context-path}/playground`;
3. Playground opens but with errors;
4. Open the browser console and check that it is trying to reach `{domain}/graphql` instead of `{domain}/{context-path}/graphql`.

**Expected behavior**
Playground should reach `{domain}/{context-path}/graphql` instead of `{domain}/graphql`.

**Comment by dariuszkuc** [comment]
Resolved in https://github.com/ExpediaGroup/graphql-kotlin/pull/1098
