### ISSUE TITLE
Inconsistent order of kotlin prop declaration and scheme prop order

### ISSUE THREAD

**Issue by heyvvwg** [ExpediaGroup/graphql-kotlin#1118]
**Library Version**
4.0.0-rc.1

**Describe the bug**
Inconsistent order of kotlin prop declaration and scheme prop order

**To Reproduce**
[Data Class]
@GraphQLName("BbsMdBoard")
data class BbsMdBoardType(
    override val id: ID,
    val name: String,
    val dtCreate: String
) : GqlNode

[Scheme]
type BbsMdBoard implements Node {
  dtCreate: String!
  id: ID!
  name: String!
}

**Expected behavior**
[Scheme]
type BbsMdBoard implements Node {
  id: ID!
  name: String!
  dtCreate: String!
}

**Comment by dariuszkuc** [comment]
I believe the schema printer prints the properties in alphabetical order to ensure consistent order. Can you elaborate why this would be an issue?

**Comment by icon1123** [comment]
I think the order in which it is declared has meaning. For example, these are the following cases:

[declared] 
id,         (id, i want first)
width,   (size)
height,  (size)
left,       (position)
top,       (position)
dtCreate

[alphabet]
dtCreate
height
id
left
top
width

**Comment by icon1123** [comment]
> I believe the schema printer prints the properties in alphabetical order to ensure consistent order. Can you elaborate why this would be an issue?

I think the order in which it is declared has meaning. For example, these are the following cases:
[declared] 
id,         (id, i want first)
width,   (size)
height,  (size)
left,       (position)
top,       (position)
dtCreate

[alphabet]
dtCreate
height
id
left
top
width

**Comment by smyrick** [comment]
We also don't control the schema printer and I wouldn't want to change what we get from graphql-java [SchemaPrinter](https://javadoc.io/doc/com.graphql-java/graphql-java/16.2/graphql/schema/idl/SchemaPrinter.html)

While I also agree that GraphQL services should not be concerned with field order, if you wanted to start a discussion, I would open one on the [graphql-java repo](https://github.com/graphql-java/graphql-java)
