### ISSUE TITLE
Specifying clientType in build.gradel in 4.0.1

### ISSUE THREAD

**Issue by krispharper** [ExpediaGroup/graphql-kotlin#1131]
We're currently on 4.0.0-alpha.9 and I'm trying to upgrade to 4.0.1. I get the following error when building

```
> Could not get unknown property 'com' for object of type com.expediagroup.graphql.plugin.gradle.GraphQLPluginClientExtension.
```

The relevant `build.gradle` section is

```
graphql {
    client {
        clientType = com.expediagroup.graphql.plugin.generator.GraphQLClientType.DEFAULT
        endpoint = "https://my-endpoint.com/graphql"
        packageName = "com.company.my_package.generated"
    }
}
```

Do I need to make a change for 4.0.1?

**Comment by dariuszkuc** [comment]
Hello 👋 
With the refactor to add support for `kotlinx-serialization` we simplified generated data models to be pure POJOs which can be used with any client (Ktor or Spring based). As a result, `clientType` is no longer a valid configuration option. 

See updated docs
* https://expediagroup.github.io/graphql-kotlin/docs/plugins/gradle-plugin-tasks#extension
* https://expediagroup.github.io/graphql-kotlin/docs/client/client-overview#generating-graphql-operations
