### ISSUE TITLE
Schema stitching support

### ISSUE THREAD

**Issue by rocketraman** [ExpediaGroup/graphql-kotlin#1138]
**Is your feature request related to a problem? Please describe.**
I have multiple independent GraphQL services, and I want graphql-kotlin to act as a single backend for all of these.

**Describe the solution you'd like**
I see that graphql-kotlin now has support for Apollo Federation. However, Federation requires all the backend schemas to cooperate in their design, and thereby couples them relatively tightly. The stitching approach taken by GraphQL guild (see https://www.graphql-tools.com/docs/stitch-combining-schemas/) accomplishes the same goals, but each backend is independent and decoupled. Furthermore, Federation does not support non-federation-compliant managed services like Hasura, without the addition of yet more intermediate proxy components into the stack.

See this comparison article by Vox Media: https://product.voxmedia.com/2020/11/2/21494865/to-federate-or-stitch-a-graphql-gateway-revisited.

**Describe alternatives you've considered**
1) Using Federation + intermediate NodeJS-based proxy components (see above for a discussion about why that is non-ideal)
2) Using the Guild's GraphQL gateway that supports schema stitching, but that also requires NodeJS.

**Comment by smyrick** [comment]
@rocketraman As you have already described schema stitching does not require that the implementing services do anything in particular, all the merging and conflict resolution goes in your gateway which runs the schema stitching code. 

So what you are looking for is a schema stitching gateway. The best option today is probably what you have already linked too, [graphql-tools](https://www.graphql-tools.com/docs/stitch-combining-schemas/). This does run on JavaScript though. If you are looking for a JVM based schema stitcher there is [graphql-braid](https://bitbucket.org/atlassian/graphql-braid/src/master/)

GraphQL Kotlin has no intention of being a GraphQL gateway or merging GraphQL schemas, but you can definitely use a graphql-kotlin service in a stitching architecture.

**Comment by rocketraman** [comment]
Thank you for the link to graphql-braid, I'll check it out.

**Comment by smyrick** [comment]
Just as a note, even at Expedia Group we use a NodeJS gateway that connects our various graphql-kotlin services. We use Node because libraries and tooling in the NPM ecosystem is hard to beat and NodeJS does work fairly well as a traffic router.

**Comment by rocketraman** [comment]
Yeah I've done the same in other projects also. Will likely do that again here.
