### ISSUE TITLE
Cannot use DataFetcherResult as an item for GraphQL List fields

### ISSUE THREAD

**Issue by teoboley** [ExpediaGroup/graphql-kotlin#1146]
**Library Version**
What version are you using? 
4.1.1

**Describe the bug**
GraphQL-Java supports using DataFetcherResult as an item for list fields with this [PR](https://github.com/graphql-java/graphql-java/pull/1567), which is useful for providing local context for individual items in lists (see [this issue](https://github.com/graphql-java/graphql-java/issues/1559)).

However, graphql-kotlin's schema generator throws a TypeNotSupportedException when it is provided as a return type for a resolver:

```
com.expediagroup.graphql.generator.exceptions.TypeNotSupportedException: Cannot convert graphql.execution.DataFetcherResult<mypackage.EntityType> since it is not a valid GraphQL type or outside the supported packages "[mypackage.graphql]"
```

**To Reproduce**
Steps to reproduce the behavior. Please provide:
- Schema Configuration

```yaml
graphql:
  packages:
    - "mypackage.graphql"
```

(no other config)

- Kotlin code used to generate the schema

```kotlin
data class WorldType(
    private val world: World
) {
  fun entities(
      dataFetchingEnvironment: DataFetchingEnvironment
  ): List<DataFetcherResult<EntityType>> = world.entities.map {
      DataFetcherResult.newResult<EntityType>()
          .data(it)
          .localContext(dataFetchingEnvironment.getLocalContext<LocalContext>()?.copy(
              currentEntityId = it.entityId
          ))
          .build()
  }
}
```

**Expected behavior**

There should be no `TypeNotSupportedException` thrown, as this configuration is supported by graphql-java and requires no type mapping by graphql-kotlin.

**Comment by smyrick** [comment]
@teoboley `DataFetcherResult` is supported as a return type but there are two issues with your code:

* Your allowed packages are `mypackage.graphql` but your class is `mypackage.EntityType`. You need to move your class or update your package config
* If you are going to use `DataFetcherResult` it needs to be the topmost wrapping class as it is wrapping the entire schema class. See the docs here: https://expediagroup.github.io/graphql-kotlin/docs/schema-generator/execution/exceptions

**Comment by smyrick** [comment]
You can see the logic of how we unwrap the possible wrappers here: https://github.com/ExpediaGroup/graphql-kotlin/blob/2a498e85e0cd2104dfcc3ccb7a3d73ca225fc92a/generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/utils/functionReturnTypes.kt#L42-L49

**Comment by smyrick** [comment]
So actually I think we could support a `List<DataFetcherResult<Entity>>`, can you try solving the package config issue?

**Comment by teoboley** [comment]
Sorry, EntityType is actually under mypackage.graphql, I had just changed out the package names for the sake of the example

**Comment by teoboley** [comment]
I've created a PR with the change for review: https://github.com/ExpediaGroup/graphql-kotlin/pull/1150
