### ISSUE TITLE
[client] support optional undefined arguments

### ISSUE THREAD

**Issue by dariuszkuc** [ExpediaGroup/graphql-kotlin#1151]
**Is your feature request related to a problem? Please describe.**
When using parameterized arguments, optional arguments can be omitted (undefined), `null` or have a specific value. Currently `graphql-kotlin-client`s do not support undefined arguments which requires specifying redundant queries to handle   case when arguments should be skipped/omitted.

**Describe the solution you'd like**
Generated GraphQL client code should provide mechanism for handling optional undefined arguments.

**Describe alternatives you've considered**
Redundant queries can be specified that omit the unnecessary arguments but it means that we might end up writing an extra query for every possible permutation of optional argument.

**Additional context**
See [discussion](https://github.com/ExpediaGroup/graphql-kotlin/discussions/1147) for more details

**Comment by dariuszkuc** [comment]
Hello 👋 
We are always open to contributions! 

I was playing around with optional input serializers and got a draft PR open -> https://github.com/ExpediaGroup/graphql-kotlin/pull/1158. Sadly it looks like we won't be able to support this functionality for `kotlinx-serialization` until https://github.com/Kotlin/kotlinx.serialization/issues/1091 is resolved (or someone has a better idea how to solve it).

**Comment by jozef-slezak** [comment]
@dariuszkuc, that is great! We just need Jackson. Is it possible to separate Jackson only solution from `kotlinx-serialization`? We can test that on our use case.
