### ISSUE TITLE
Load SDL from file system- Gradle

### ISSUE THREAD

**Issue by jarpz** [ExpediaGroup/graphql-kotlin#1153]
Hi, 

How can we load the sdl file from file system, suppose we download the sdl and put inside the project.

we use this config:

```
val graphqlGenerateClient by tasks.getting(GraphQLGenerateClientTask::class) {
    packageName.set("com.osm.soft.sync.graphql.shopify")
    schemaFileName.set("schema.graphql")
}
```

and run the task, but the plugin non generate anything.

Regards.

**Comment by smyrick** [comment]
@jarpz What version of what library are you using here? I am assuming version 4.x.x of the client-generator.

@dariuszkuc Are the docs here out of date? https://expediagroup.github.io/graphql-kotlin/docs/plugins/gradle-plugin-tasks#graphqlgenerateclient

I see in the code the actually parameters is actually just one called `schemaPath`: https://github.com/ExpediaGroup/graphql-kotlin/blob/669d62b022b798be315c18a62d9a0627d5fb8186/plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/parameters/GenerateClientParameters.kt#L40

**Comment by dariuszkuc** [comment]
Docs are correct - either `schemaFileName` (String) or `schemaFile` (File) can be specified as task inputs (which in turn gets converted to the path used by the worker.

@jarpz how are you executing it? are you invoking the task directly (i.e. `./gradlew graphqlGenerateClient`)? did you configure it to run as part of your build?

**Comment by smyrick** [comment]
> Docs are correct - either `schemaFileName` (String) or `schemaFile` (File) can be specified as task inputs (which in turn gets converted to the path used by the worker.

Ok, I see that is an internal class, the plugin parameters are mapped here:

https://github.com/ExpediaGroup/graphql-kotlin/blob/edad0b4e05d79206e9059d0fba725b96346e9ed2/plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/AbstractGenerateClientTask.kt#L149-L153

**Comment by jarpz** [comment]
Yeah is working.

Thanks. 
Regards
