### ISSUE TITLE
reading introspection query into GraphQLRequest fails

### ISSUE THREAD

**Issue by boiledbuns** [ExpediaGroup/graphql-kotlin#1187]
**Library Version**
I'm using gradle with the graphql-kotlin-server dependency with ktor:
```
implementation "com.expediagroup:graphql-kotlin-server:4.1.1"
```

**Describe the bug**
Following the ktor example on the [github](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/KtorGraphQLRequestParser.kt), my request handler fails when trying to parse the raw request I receive from the application request to GraphQLRequest (for introspection). Jackson will throw an IOException on readValue

```
Cannot construct instance of `com.expediagroup.graphql.server.types.GraphQLRequest` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
```

From what I can tell, the `GraphQLRequest` class (which is internal to the library) is configured to work with jackson properly so I'm not sure if there is an issue in the release or there are any additional steps I need to take to configure the library. 

**To Reproduce**
Steps to reproduce the behavior. Please provide:
- Schema Configuration
- Kotlin code used to generate the schema
^ I haven't provided the schema because I don't believe this is related - if it is required, I can provide it :P

Request handler
```kotlin
class KtorGraphQLRequestParser(
    private val mapper: ObjectMapper
) : GraphQLRequestParser<ApplicationRequest> {

    @Suppress("BlockingMethodInNonBlockingContext")
    override suspend fun parseRequest(request: ApplicationRequest): GraphQLServerRequest? = try {
        val rawRequest = request.call.receiveText()
        mapper.readValue(rawRequest, GraphQLServerRequest::class.java)
    } catch (e: IOException) {
        throw IOException("Unable to parse GraphQL request payload. \n Exception message: ${e.message}")
    }
}
```

This is the raw request
```
{
  "operationName": "IntrospectionQuery",
  "variables": {},
  "query": "query IntrospectionQuery {\n  __schema {\n    queryType {\n      name\n    }\n    mutationType {\n      name\n    }\n    subscriptionType {\n      name\n    }\n    types {\n      ...FullType\n    }\n    directives {\n      name\n      description\n      locations\n      args {\n        ...InputValue\n      }\n    }\n  }\n}\n\nfragment FullType on __Type {\n  kind\n  name\n  description\n  fields(includeDeprecated: true) {\n    name\n    description\n    args {\n      ...InputValue\n    }\n    type {\n      ...TypeRef\n    }\n    isDeprecated\n    deprecationReason\n  }\n  inputFields {\n    ...InputValue\n  }\n  interfaces {\n    ...TypeRef\n  }\n  enumValues(includeDeprecated: true) {\n    name\n    description\n    isDeprecated\n    deprecationReason\n  }\n  possibleTypes {\n    ...TypeRef\n  }\n}\n\nfragment InputValue on __InputValue {\n  name\n  description\n  type {\n    ...TypeRef\n  }\n  defaultValue\n}\n\nfragment TypeRef on __Type {\n  kind\n  name\n  ofType {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}\n"
}
```

**Expected behavior**
Jackson will be able to read the raw request into a `GraphQLRequest` instance

**Comment by smyrick** [comment]
I had to update the example ktor app to work with our Long scalar removal but once I did that the example app is still able to parse requests with variables.

https://github.com/ExpediaGroup/graphql-kotlin/pull/1191

And I can also see the incoming introspection query from the Playground on startup is working fine. How are you creating your ObjectMapper? Are you using the kotlin supported mapper?

**Comment by boiledbuns** [comment]
Yup, did a quick sanity check and can confirm that it works when I use exactly what exists in the example so it's probably related to one of the dependencies I'm pulling in though I'm still not sure exactly how. I am using the kotlin version of jackson `com.fasterxml.jackson.module:2.12.3` and I'm using the mapper in the same way as the example (ie. `val mapper = jacksonObjectMapper()`). I'll dig into it a bit more (maybe there's something going on with how dependencies are being resolved?) and update the issue if I find something :P hopefully it'll help someone else if they experience the same issue

**Comment by boiledbuns** [comment]
Figured it out - issue was completely on my end, I created an `ObjectMapper` using `jacksonObjectMapper()` but also created one using `ObjectMapper()`. Somehow I ended up using the wrong one 😢 kudos for the quick response 🙏
