### ISSUE TITLE
Load pre-compiled GraphQLSchema at application startup time

### ISSUE THREAD

**Issue by rocketraman** [ExpediaGroup/graphql-kotlin#1214]
**Is your feature request related to a problem? Please describe.**
I'm currently running my application in a serverless environment. Therefore, I am interested in minimizing startup time (recognizing that the JVM as a whole has limitations here). I've found that the creation of the `GraphQLSchema` object takes up the vast majority of my current startup time -- initializing takes about 4 seconds and about 75% of that seems to be `GraphQLSchema` construction.

**Describe the solution you'd like**
I'd like a mechanism to build and serialize the GraphQLSchema so that it can simply be loaded at runtime, instead of the schema being generated at runtime based on runtime introspection.

**Describe alternatives you've considered**
Obviously moving off of a serverless environment towards long-running server processes works around the issue. However, this is not always an ideal scenario at the early stages of a business looking to minimize costs when traffic is low.

**Additional context**

**Comment by smyrick** [comment]
@rocketraman Are you using `graphql-kotlin-spring-server` or your own server implementation and just using the generator?

**Comment by rocketraman** [comment]
> @rocketraman Are you using `graphql-kotlin-spring-server` or your own server implementation and just using the generator?

Just the generator. I'm usking ktor as my server FWIW.

**Comment by smyrick** [comment]
Then there really isn't much interaction our library can do here. The schema generator will output a graphql-java `graphql.schema.GraphQLSchema` object. Then to create the executable graphql-java object that your code needs at runtime, you [pass `GraphQLSchema` to `graphql.GraphQL`with your execution strategy](https://github.com/ExpediaGroup/graphql-kotlin/blob/a6b957c999398c741cdfbc955fb86243ea211094/servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLSchemaConfiguration.kt#L73-L76).

If you have some process to serialize the `GraphQLSchema` object, you can do that on your own. The object doesn't implement `java.io.Serializable` so you will have to use your own mapper

**Comment by rocketraman** [comment]
With that information in mind, I dug down a little bit more. Out of the 3s of initialization time used by the GraphQL subsystem, which represents 75% of my startup time), the call to:

* `toSchema` : 1.5 seconds
* `GraphQL.newGraphQL` : 1.5 seconds

So I guess while it doesn't look like there is much this lib can do about the `newGraphQL` call, it'd still be nice to reduce that 1.5s (37.5% of my startup time).

**Comment by rocketraman** [comment]
BTW, I posted here in case anyone from the graphql-java project community has any ideas: https://github.com/graphql-java/graphql-java/discussions/2452.

**Comment by smyrick** [comment]
Correct, the `GraphQLSchema` object is what you are looking to serialize. Even if you weren't using our library you would still have similar issues as you would have to read a SDL file with graphql-java, and still build the object from that and the type registry at startup.

If you do find something that works I would definitely be interest in the solution. But seeing as this is not something our library can help you with, I am going to close the issue.

**Comment by rocketraman** [comment]
> Correct, the `GraphQLSchema` object is what you are looking to serialize. Even if you weren't using our library you would still have similar issues as you would have to read a SDL file with graphql-java, and still build the object from that and the type registry at startup.

Partially in response to my discussion with them, looks like the graphql-java guys are making `TypeDefinitionRegistry` serializable: https://github.com/graphql-java/graphql-java/pull/2454. However, correct me if I'm wrong, but graphql-kotlin doesn't use TypeDefinitionRegistry so that doesn't help, does it?

**Comment by smyrick** [comment]
No, that wouldn't help. We don't use the `TypeDefinitionRegistry` since we build up the types and runtime wiring for you and construct the `CodeRegistry`. See example of how a function is created: https://github.com/ExpediaGroup/graphql-kotlin/blob/a6b957c999398c741cdfbc955fb86243ea211094/generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateFunction.kt#L55-L63

If you are looking for the fastest startup times then you may be better off using graphql-java directly

**Comment by rocketraman** [comment]
> If you are looking for the fastest startup times then you may be better off using graphql-java directly

Well sure, but I really like the code-first approach of graphql-kotlin.

Is the reticence to do the code introspection necessary to implement a code-first approach at build time rather than runtime philosophical, or just a lack of time / desired focus?

**Comment by smyrick** [comment]
Reflection is required to do a code-first approach as that is how we tie a specific function to a code registry, other wise you would have to wrap all your functions in DataFetchers and tie together the runtime wiring

https://www.graphql-java.com/documentation/v16/data-fetching/

**Comment by rocketraman** [comment]
> Reflection is required to do a code-first approach as that is how we tie a specific function to a code registry. I suppose in theory we could make the generator only output schema definitions, but then you would still have to wrap all your functions in DataFetchers and tie together the runtime wiring on startup, the same as you do in graphql-java

I recognize that, but what about doing that reflection at build time via a build plugin?

**Comment by dariuszkuc** [comment]
If you were to construct schema at build time you would have to serialize it into something that can be easily parsed at runtime - constructed schema could be saved in sdl format but again you would have a problem with what to do with code registry. Depending how fast this deserialization is it may or may not be worth it (guess there could be a potential benefit of avoiding reflections at runtime). Also unsure if it makes sense to do code -> generate SDL -> load schema, if you are going to load SDL why not just start with it?

Code registry take field coordinates and associate it with some data fetcher - if you only have single data fetcher serialization logic might be simple. In case of something more advanced (like our Spring aware datafetcher it is most likely not possible)
