### ISSUE TITLE
Playground endpoint path not possible to set to `graphql`

### ISSUE THREAD

**Issue by IvBre** [ExpediaGroup/graphql-kotlin#1221]
**Library Version**
4.1.1

**Describe the bug**
We would like to set up the endpoint of the Playground to be `/graphql`. So that `POST/PUT` requests are handled by the GQL server and a `GET` request to open the Playground. 
But setting the config to: `graphql.playground.endpoint: "graphql"` produced HTTP error 400 when accessing `GET /graphql`. 
If I would change it to whatever else, like for example: `graphql.playground.endpoint: "foo"` then `GET /foo` works.

**To Reproduce**
- Add the following configuration in your `application.yml` file: `graphql.playground.endpoint: "graphql"`
- Try to open `<your-host>:<host-ip>/graphql` and verify that it is not opening Playground.

**Expected behavior**
Having config set to: `graphql.playground.endpoint: "graphql"` should be able to open the Playground on `/graphql` endpoint.

**Comment by dariuszkuc** [comment]
Hello 👋 
In `graphql-kotlin-spring-server` we are following best practices defined in https://graphql.org/learn/serving-over-http/#http-methods-headers-and-body, so while yes a majority of GraphQL requests are generally made through a POST requests it is also possible to use GET with query parameters (thats actually what Playground relies on to easily share your queries).

You could probably just override the `graphQLRoutes` bean (https://github.com/ExpediaGroup/graphql-kotlin/blob/master/servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLRoutesConfiguration.kt#L42) to provide custom routing logic to only accept POST requests and serve Playground for GET requests but I wouldn't recommend it as it would break Playground ability to share queries.

**Comment by dariuszkuc** [comment]
Correction: looks like playground actually generates CURL thats POSTs requests. Still would recommend to follow graphql.org best practice to also handle GET requests.
