### ISSUE TITLE
ClassScanner not working when building with GraalVM native-image

### ISSUE THREAD

**Issue by navrocky** [ExpediaGroup/graphql-kotlin#1224]
**Library Version**
 \>= 4.1.1

**Describe the bug**
As we know dynamic class loading is not working at runtime in native image. So ClassGraph call in ClassScanner is not working too, it not find any classes.

**To Reproduce**
Steps to reproduce the behavior. 
- compile with native-image and run, you get error: 
 "The configured packages do not contain any valid classes: "$packages" 
 Error is here https://github.com/ExpediaGroup/graphql-kotlin/blob/a6b957c999398c741cdfbc955fb86243ea211094/generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt#L61

**Expected behavior**
It should working.

Possible fix is remove ClassScanner validation code, or make it optional. ClassScanner is used in a rare case for search classes by annotation.

**Comment by dariuszkuc** [comment]
> ClassScanner is used in a rare case for search classes by annotation.

`ClassScanner` is used to build polymorphic types (i.e. unions and interfaces) as well as to build federated schemas (i.e. locate extended federated objects through the annotations -> they won't be accessed through the regular query tree).

**Comment by navrocky** [comment]
Also I tried this workaround (https://github.com/SoftInstigate/classgraph-on-graalvm) but with no luck.

I add these parameters to native-image cli invokation, to execute class scan at build phase:
```
tasks {
    nativeImage {
        args("--initialize-at-build-time=hello.world.ClassGraphInit,io.github.classgraph.,nonapi.io.github.classgraph.")
    }
```

ClassGraphInit.java
```
package hello.world;

import io.github.classgraph.ClassGraph;

public class ClassGraphInit {
    static {
        new ClassGraph()
                .disableModuleScanning() // added for GraalVM
                // .disableDirScanning() // added for GraalVM
                // .disableNestedJarScanning() // added for GraalVM
                // .disableRuntimeInvisibleAnnotations() // added for GraalVM
                .addClassLoader(ClassLoader.getSystemClassLoader())
                .enableAllInfo()
                .acceptPackages("hello.world")
                .scan();
    }
}
```

Then I get this error:
```
Error: type is not available in this platform: com.oracle.svm.hosted.NativeImageGenerator
Detailed message:
Trace: Object was reached by 
        indexing into array
                constant java.lang.Class[]@37711028 reached by 
        reading field nonapi.io.github.classgraph.classpath.CallStackReader.callStack
```

**Comment by dariuszkuc** [comment]
You can now explicitly specify type hierarchy information (and federation entities) without relying on `ClassGraph`. `SchemaGeneratorConfig` now accepts the `GraphQLTypeResolver` which defaults to classpath scanning but can be configured with explicit resolver. See #1733 for details
