### ISSUE TITLE
Coroutine cancellation support

### ISSUE THREAD

**Issue by DrMetallius** [ExpediaGroup/graphql-kotlin#1257]
**Is your feature request related to a problem? Please describe.**
Currently `FunctionDataFetcher` launches suspend functions using `GlobalScope`. This means that it is disconnected from the scope the request is in and can't be canceled.

We discovered this when we were load testing the server. We can set a timeout for requests to drop the ones the server didn't handle in time, but this won't cancel the running coroutines started with `GlobalScope`. This means that when the load is above a certain threshold, it overwhelms the server, the memory is filled with uncancelled coroutine contexts from all the coroutine starts, and the server is doing the work for the clients which are no longer there.

**Describe the solution you'd like**
`GraphQLServer` should create a `supervisorScope`, run all the methods within it, and store a reference to that scope somewhere accessible to data fetchers. Judging by what GraphQL Java makes available, this should probably just be in `GraphQLContext`. `FunctionDataFetcher` can then get the scope and use it to execute the functions instead of `GlobalScope`.

**Describe alternatives you've considered**
Right now we're doing the same thing manually by overriding what GraphQL Kotlin offers us. However, we would prefer to have this problem fixed in the framework since it makes it more difficult to upgrade to newer versions as we have to reimplement the solution again every time.

I've seen issue #879, which describes an attempt to resolve this by making the whole context a scope, but that seems inflexible, also that commit leaves out the code required to actually create the scope. Speaking of the parent-child relationship of coroutines mentioned there, I don't see why it would be a blocker. `GlobalScope` doesn't handle this anyway, so it's not a regression. We could start with the basic support at the request level and make it more granular later if we need to, possibly using local context.

I really hope this issue gets addressed, it caused us a lot of trouble when we load tested our server.

**Comment by dariuszkuc** [comment]
This should be resolved in https://github.com/ExpediaGroup/graphql-kotlin/pull/1349
