### ISSUE TITLE
After upgrading to 5.1.0, calling toSchema generates "illegal reflective access" warning to stderr

### ISSUE THREAD

**Issue by xenomachina** [ExpediaGroup/graphql-kotlin#1272]
## Library Version
5.1.0

## Describe the bug

After upgrading to graphql-kotlin 5.1.0 (from 4.2.0), calling `toSchema` generates the following warning to stderr:

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by nonapi.io.github.classgraph.utils.ReflectionUtils$StandardReflectionDriver$1 (file:/home/laurence/.gradle/caches/modules-2/files-2.1/io.github.classgraph/classgraph/4.8.123/79131dde24cc79ee294d10639b481da76215b28b/classgraph-4.8.123.jar) to method sun.management.RuntimeImpl.getInputArguments()
> WARNING: Please consider reporting this to the maintainers of nonapi.io.github.classgraph.utils.ReflectionUtils$StandardReflectionDriver$1
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

## To Reproduce

I've pared this down to a minimal test case that illustrates the issue:

### Schema Configuration

``` kotlin
package com.example.gql

class TestQuery {
    @GraphQLDescription("add two numbers")
    fun plus(x: Int, y: Int): Int = x + y
}
```

### Kotlin code used to generate the schema

``` kotlin
toSchema(
    config = SchemaGeneratorConfig(supportedPackages = listOf("com.example") ),
    queries = listOf(TestQuery()).map(::TopLevelObject),
)
```

## Expected behavior

No warnings.

## Additional Information

I found that this warning is generated when `toSchema` (indirectly) does `ClassGraph().acceptPackages("com.example").scan()`, and I can reproduce the warning by doing this in my own code.

The root cause seems to be due to a change in `io.github.classgraph:classgraph`. Version 4.8.118 of classgraph and later produce this warning during `scan()`, while earlier versions do not.

**Comment by xenomachina** [comment]
Joe on the Slack channel linked to [a relevant classgraph issue](https://github.com/classgraph/classgraph/issues/579). It looks like classgraph has already [committed a fix](https://github.com/classgraph/classgraph/commit/928264d7da9de3955fe357f9d17382a5c3ba04a0), but has not yet released it.

**Comment by lukehutch** [comment]
ClassGraph 4.8.127 fixes this issue.
