### ISSUE TITLE
using @JsonProperty with @GraphQLName annotation is causing a DataFetchingExpection

### ISSUE THREAD

**Issue by shapan1** [ExpediaGroup/graphql-kotlin#1296]
**Library Version**
graphql-kotlin.version = 2.1.1

**Describe the bug**
I am using graphql-kotlin to take in an object with the following schema
```
 attributes{
  attrVal
  default
} 
```
`default` is boolean which needs to be mapped internally to variable with another name as we are using Mapstruct library for out graphql to internal model to dynamo Item mappings.
Mapstruct does not allow the usage of the keyword `default`, i.e. we name the variable to `defaultAttr` but renamed with the graphql as suggested in the [docs](https://opensource.expediagroup.com/graphql-kotlin/docs/schema-generator/customizing-schemas/renaming-fields/). 
However we are seeing the following issue ->
```
{
    "errors": [
        {
            "message": "Cannot return null for non-nullable type: 'Boolean' within parent 'Attribute' (/
                "attribute",
                0,
                "default"
            ],
            "extensions": {
                "classification": "DataFetchingException"
            }
        },
    "data": {
         attribute: null
     }
   
```
Debugging through the code I could trace it back all the way to `response` returned from my service, however could not trace to the how JsonProperty serializes the `defaultAttr` back to `default` and why is the whole `attribute` object null

**To Reproduce**
Steps to reproduce the behavior. Please provide:
- Schema Configuration
```
schema {
 query: Query
 mutation: Mutation
}
type Attribute {
  default: Boolean!
  attrVal: AttrVal!
}
input AttributeInput {
  default: Boolean!
  attrVal: AttrVal!
}
```
- Kotlin code used to generate the schema
```
/* GraphqlAttribute */
@KotlinBuilder
data class Attribute(
    val attrval: AttrEnum,
    @GraphQLDescription("xyz")
    @GraphQLName("default")
    @JsonProperty("default")
    val defaultAttr: Boolean
)

/* Internal Attribute */
@KotlinBuilder
data class Attribute(
    val attrval: AttrEnum,
    val defaultAttr: Boolean
)
```
This in turn is being used by Mapstruct (v 1.4.1) to map graphql model to internal model and then to dynamo Item.
Following is the mapper
```
    //
    // Internal Attribute
    //
    @Mappings(
        Mapping(
            target = "attrval",
            source = "attrval"
        ),
        Mapping(
            target = "defaultAttr",
            source = "defaultAttr"
        )
    )
    fun toAttribute(attribute: GraphQLAttribute): Attribute

    //
    // graphql Attribute
    //
    @InheritInverseConfiguration
    fun fromAttribute(attribute: Attribute): GraphQLAttribute
    
```

**Expected behavior**
expectation is for the `default` variable to return the appropriate value and not be null.

**Comment by smyrick** [comment]
@shapan1 We have fixed this in a more recent version. v2 is no longer supported. v5 is the current release and v4 is getting bug and security fixes.

Also can you try adding `@field:JsonProperty`

See https://github.com/ExpediaGroup/graphql-kotlin/issues/493

**Comment by shapan1** [comment]
Thanks @smyrick. For now I will try adding the fix you mentioned. But I think upgrading the version is an important task  and we will prioritize it. Which version do you recommend upgrading to? i.e. is there a specific version that's stable and supported and has the security patches?

**Comment by smyrick** [comment]
The lastest version, v5. You can see the release notes from previous versions for what has changed between each major version
