### ISSUE TITLE
Support of WebFlux

### ISSUE THREAD

**Issue by stasbit** [ExpediaGroup/graphql-kotlin#1307]
Hello team!

  Recently I switch Spring Boot services with GraphQL from MVC to Webflux. And mutations\queries are stop working. 

Sample of response is:
`type mismatch error, expected type LIST got class reactor.core.publisher.MonoFlatMap`

I try to follow [async guide](https://opensource.expediagroup.com/graphql-kotlin/docs/schema-generator/execution/async-models/) but still same error

**Comment by smyrick** [comment]
Can you share your schema code, config, and hooks?

**Comment by stasbit** [comment]
@smyrick Actually I was wrong, this part is working once I get hooks and config accoding to acticle. Now I have problem with PreAuthorize of Spring Security, but I'll create a separate issue
Thanks!
