### ISSUE TITLE
Subgraph schema incompatible with the specs: _FieldSet instead of _FieldSet!

### ISSUE THREAD

**Issue by IvBre** [ExpediaGroup/graphql-kotlin#1310]
**Library Version**
5.2.0

**Describe the bug**
We are getting the following errors on our Gateway:
```
Invalid redefinition of built-in directive @key: @key(fields:) should have type _FieldSet! but found type _FieldSet
Invalid redefinition of built-in directive @requires: @requires(fields:) should have type _FieldSet! but found type _FieldSet
Invalid redefinition of built-in directive @provides: @provides(fields:) should have type _FieldSet! but found type _FieldSet
```
And according to [the official subgraph specification](https://www.apollographql.com/docs/federation/federation-spec/#federation-schema-specification), it should indeed be a required type.

**To Reproduce**
Enable Federation on your GraphQL server and take a look at the schema definition for example for:
```
directive @requires
```

**Expected behavior**
The mentioned directives should have a `fields` input of type `_FieldSet!` instead of `_FieldSet`.

**Comment by dariuszkuc** [comment]
Hello 👋 
Can you provide a repo that reproduces this issue? Per our [integration tests](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorTest.kt#L31) and the [federation example](https://github.com/ExpediaGroup/graphql-kotlin/tree/master/examples/federation) generated schema should be correct.

**Comment by IvBre** [comment]
Hey, here is an example repo where one could reproduce this issue: https://github.com/IvBre/federation-subgraph-example
If you take a look at [the test schema](https://github.com/IvBre/federation-subgraph-example/blob/main/app/src/test/kotlin/federation/subgraph/example/AppTest.kt) you can see that the directives are with `_FieldSet` without `!`.
Can you see if I'm missing something to have it generated properly as in your integration test? 🤔

**Comment by dariuszkuc** [comment]
Thanks for the repro! It is indeed a bug and sadly its been there for quite some time (https://github.com/ExpediaGroup/graphql-kotlin/pull/702). What's even worse we had tests verifying this invalid schema 😢 

It affects all non-federated schemas (i.e. without extended types) exposed as a federated schema. It's fixed in https://github.com/ExpediaGroup/graphql-kotlin/pull/1322

**Comment by IvBre** [comment]
Ah I see, so it is some kind of edge case since we don't extend other types in this example. Thanks a lot for this super quick fix! 💪
