### ISSUE TITLE
GraphQL and Spring Security @PreAuthorize for Spring Boot webflux project

### ISSUE THREAD

**Issue by stasbit** [ExpediaGroup/graphql-kotlin#1311]
Hello team,
  
  I was recently asked to add Security support for kotlin Spring boot webflux service. After add certain spring security dependencies, I observer that test endpoint retruns Access Denied exception.

How to reproduce

1. Test service - https://github.com/stasbit/webflux-security-demo-service
2. Create test JWT token(http://jwtbuilder.jamiekurtz.com) here and put it to cookie "access_token". Add Claim Type "Roles" with values 'USER, MANAGER'
3. Send Query to getAllBooks

**Comment by dariuszkuc** [comment]
Have you checked https://github.com/ExpediaGroup/graphql-kotlin/discussions/1300?
