### ISSUE TITLE
OptionalInput<List<UUID>> is parsed as OptionalInput<List<String>> resulting in runtime ClassCastException

### ISSUE THREAD

**Issue by rocketraman** [ExpediaGroup/graphql-kotlin#1312]
**Library Version**
5.2.0

**Describe the bug**
An input type containing `OptionalInput<List<UUID>>` is parsed by GraphQL as `OptionalInput<List<String>>`. The runtime type mismatch results in a runtime `ClassCastException` when the code expects to see a UUID, but actually gets a String.

A workaround that can be used in most situations is to accept `List<UUID>?` and treat an empty list vs a null list as the difference between provided+empty and absent. However, the field semantics may not always allow for this.

**To Reproduce**
Steps to reproduce the behavior. Please provide:

```
data class Foo(
  val l: OptionalInput<List<UUID>>
)
```

```
val graphqlUuidType: GraphQLScalarType = GraphQLScalarType.newScalar()
  // lower-case name matches Hasura
  .name("uuid")
  .description("A type representing a formatted UUID")
  .coercing(UUIDCoercing)
  .build()

object UUIDCoercing : Coercing<UUID, String> {
  override fun parseValue(input: Any): UUID = UUID.fromString(serialize(input))

  override fun parseLiteral(input: Any): UUID {
    val s = (input as StringValue).value
    return UUID.fromString(s)
  }

  override fun serialize(dataFetcherResult: Any): String = coerceSafe(dataFetcherResult) { toString() }
}

class CustomSchemaGeneratorHooks(config: SchemaConfig) : SchemaGeneratorHooks {
  override fun willGenerateGraphQLType(type: KType): GraphQLType? = when (type.classifier as? KClass<*>) {
    UUID::class -> graphqlUuidType
    else -> null
  }
}
```

**Expected behavior**
I would expect the runtime type to be the same as the compile-time type.

**Comment by dariuszkuc** [comment]
Hello 👋 
This sounds like the same underlying issue as https://github.com/ExpediaGroup/graphql-kotlin/issues/1220
