### ISSUE TITLE
Where are my generated files? I can't find them or import anything from them

### ISSUE THREAD

**Issue by boofhead** [ExpediaGroup/graphql-kotlin#1313]
I have this in my `build.gradle .kts`

```
graphql {
    client {
        endpoint = "https://domain.com/graphql"
        headers = mapOf("x-api-key" to "XXX-MY-API-KEY")
        packageName = "com.domain.graphql.generated"
        serializer = GraphQLSerializer.JACKSON
        queryFileDirectory = project.buildDir.absolutePath
    }
}
```

names changed to protect the innocent.

schema generates from introspection as expected and looks good. Client generation task runs with no errors but there is no generated code anywhere I can see and nothing I can import to use.

I know I'm being stupid here but what am I doing wrong??

**Comment by smyrick** [comment]
For Gradle it would be at `<project>/build/generated/...`
