### ISSUE TITLE
context map rough edges

### ISSUE THREAD

**Issue by halfbaked** [ExpediaGroup/graphql-kotlin#1318]
**Library Version**
5.2.0

**Describe the bug**
I wonder if the `SpringGraphQLContextFactory` needs some finesse. It currently requires us to implement the deprecated `suspend fun generateContext(request: ServerRequest)` while leaving the new `suspend fun generateContextMap(request: ServerRequest): Map<*, Any>?` optional. In the current situation, using the IDE to implement the necessary methods in the subclass directs users to continue using the deprecated method. 

Also in the documentation for Generating GraphQL Context in spring server, the examples are for the deprecated method. To me, as a newcommer, it's a little confusing.

**Expected behavior**
Perhaps (for backwards compatibility) give both `generateContext` and `generateContextMap` default implementations in the abstract class, and update the spring server docs to use `generateContextMap`. 

Keep up the good work!

**Comment by dariuszkuc** [comment]
Should be resolved by https://github.com/ExpediaGroup/graphql-kotlin/pull/1349
