### ISSUE TITLE
Switch filter order in generator: hooks after internal filter

### ISSUE THREAD

**Issue by F43nd1r** [ExpediaGroup/graphql-kotlin#1368]
**Is your feature request related to a problem? Please describe.**
We have some code using `SchemaGeneratorHooks.isValidFunction`. It would be easier for us if this would not be called for methods which are filtered out afterwards anyway, e.g. equals and hashcode.

**Describe the solution you'd like**
This could be easily achieved by switching the filter order in [kClassExtensions#47](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kClassExtensions.kt#L47).
The same fix could probably be applied to properties etc.

**Describe alternatives you've considered**
Our current approach requires us to filter out these functions ourselves:
```kotlin
if (function.name in setOf("hashCode", "equals", "toString", "copy") || function.name.startsWith("component")) return false
if (function.visibility != KVisibility.PUBLIC) return false
```

**Comment by dariuszkuc** [comment]
Hello 👋 
I am unsure why we had hooks applied before generic filters. It might be a leftover of some original logic. I agree that custom hooks should be applied last.
