### ISSUE TITLE
"This type is final, so it cannot be inherited from" when extending DefaultSpringGraphQLContextFactory

### ISSUE THREAD

**Issue by chrisvettese** [ExpediaGroup/graphql-kotlin#1384]
**Library Version**
5.3.2

**Describe the bug**
The documentation [here](https://opensource.expediagroup.com/graphql-kotlin/docs/server/spring-server/spring-graphql-context) outlines that DefaultSpringGraphQLContextFactory can be extended to create a custom GraphQL context map. However, extending it produces the error `This type is final, so it cannot be inherited from`. I am using graphql-kotlin-spring-server.

**To Reproduce**
The following code will produce the error:
```kotlin
@Component
class MyGraphQLContextFactory : DefaultSpringGraphQLContextFactory() {
    override suspend fun generateContextMap(request: ServerRequest): Map<*, Any> = super.generateContextMap(request) + mapOf(
        "myCustomValue" to (request.headers().firstHeader("MyHeader") ?: "defaultContext")
    )
}
```

In addition, there is another error on the +:
`Operator call corresponds to a dot-qualified call 'super.generateContextMap(request).plus(mapOf(
        "myCustomValue" to (request.headers().firstHeader("MyHeader") ?: "defaultContext")
    ))' which is not allowed on a nullable receiver 'super.generateContextMap(request)'.`

**Expected behavior**
No syntax errors should appear. The code should be compileable.

**Comment by KDube1** [comment]
Do you have have an estimation of when this major release will come out?
