### ISSUE TITLE
graphql-java 18.0 support

### ISSUE THREAD

**Issue by cryptoki** [ExpediaGroup/graphql-kotlin#1392]
I tried to bump up graphql-kotlin to graphql-java 18.0. It seems a bit more work. :) Is there any task already in doing?

**Comment by dariuszkuc** [comment]
Hello 👋,
Thanks for taking the initiative with the update! Indeed the bump requires quite some changes (big change is the directive -> applied directive split). I'm working on it but still got to fix a number of unit tests.
