### ISSUE TITLE
Internal class @GraphQLName prefix

### ISSUE THREAD

**Issue by ronjunevaldoz** [ExpediaGroup/graphql-kotlin#1414]
Requesting feature to set the default GraphQLName for inner class to include the parent name as `UserStatus` for the below example.
```kotlin
data class User { 
     @GraphQLName("UserStatus")
     enum class Status
}
```
Conflicting class name
```kotlin
data class Other{  
     enum class Status
}
```

**Comment by dariuszkuc** [comment]
Hello 👋 
Thank you for raising this but we don't think this functionality should be a part of the core library. Renaming of the types should be explicit and you can do that by using `@GraphQLName` annotation (or through the hooks).
