### ISSUE TITLE
Partial support for generic classes

### ISSUE THREAD

**Issue by nk-coding** [ExpediaGroup/graphql-kotlin#1420]
**Is your feature request related to a problem? Please describe.**
Allow Kotlin generic classes if generic type does not affect GraphQL type (non of  the fields uses the generic type).  
Consider the following example:
```kt
abstract class Template<T : Any>(private val templatedVal: T) {
    val stringVal: String = templatedVal.toString()
}

class IntTemplate(x: Int) : Template<Int>(x)
```
Here, the Template  class is generic,  however the  generated GraphQL type has only the field `stringVal` and could therefore be generated without any generics:
```graphql
interface Template {
    stringVal: String!
}

type IntTemplate implements Template {
    stringVal: String!
}
```

**Describe the solution you'd like**
Allow this  use  case. This would be possible by replacing the `createType()` call with [starProjectedType](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.reflect.full/star-projected-type.html) in `SchemaGenerator.kt`, `generateInterface.kt`, `generateObject.kt` and `generateUnion.kt`

**Describe alternatives you've considered**
In graphql-kotlin:
- introducing a hook which transforms the `KClass` to a `KType`, it would call `createType()` by default, but could be overridden by users for example with `starProjectedType`

In my code:
- marking all the generic classes with `@GraphQLIgnore`, and introducing interfaces for the non-generic part (which should be present in the GraphQL schema), however this results in a lot of unnecessary code duplicates
- automatically ignoring generic classes, and then automatically creating the interfaces based on the supertypes (bascally reimplementing a small part of graphql-kotlin  for my use case)

**Additional context**
Please note that I'm aware of #292 and  #621.  However, in contrast  to those, I do  not propose to actually support generics in the GraphQL type, I only want to propose to ignore generic type parameters which do not affect the GraphQL type generation.  
Especially, this example would still throw an Exception during schema generation:
```kt
class Template<T : Any>(val templatedVal : T)
```

**Comment by nk-coding** [comment]
So, I could provide a PR for this, however I'm really not sure if this is a feature you actually want to support. There, if you're interested, just let me know

**Comment by dariuszkuc** [comment]
Hello :wave:
As you are aware we cannot support generics due to the JVM type erasure (and the fact that GraphQL spec does not support it either). That being said, as you mentioned, generic classes that do not expose any of the generic fields potentially could be supported. 

I personally don’t expect this to be a common pattern as I am unsure how useful would be a generic class that does not expose any the generic fields (nor accept any generic input arguments)? Can you provide a use case for such schema objects?

**Comment by nk-coding** [comment]
Hello,
my use case is some kind of template mechanism:
```kotlin
abstract class TemplatedNode<SELF : TemplatedNode<SELF,T>, T : Template<T, SELF>> : Node() {
    internal val template: T = // ...
    
    fun templateField(key: String): // ...
}

abstract class Template<SELF : Template<SELF, T>, T : TemplatedNode<T, SELF>> : Node() {
    internal val templatedNodes: List<T> = // ...

    fun templateFieldDefinition(key: String): // ...
}

class ComponentTemplate : Template<ComponentTemplate, Component>() {
    // some additional properties and functions
}

class Component(
    val name: String
) : TemplatedNode<Component, ComponentTemplate>() {
    // some additional properties and functions
}
```

A template defines a list of extension fields, each with a key and a type (in my case JSON schema).
Then, on the `TemplatedNode` (as an example `Component`), if it has a specific template, you can get and set these fields in a type-safe way.  
`Component` and `ComponentTemplate` now define additional fields, which are used internally.  
The generic type parameters now ensure, that templates are only used for the correct types, e.g. that a `ComponentTemplate` can only be used for a `Component`. When creating the `Component`, this is manually checked.  
Also, if it is necessary to expose the template via the API, the following could be added to `Component`:
```kt
val componentTemplate by ::template
```
This also brings me to a more general use case: while the internal generic type cannot be exposed, the result of computations can be exposed. E.g., there could be a subclass `ColoredTemplate` which defines a color String, and all `TemplateNode`s which have a `ColoredTemplate` could now provide this color from the template.  
Also, in theory, there are some things that can be done using the `isValidProperty` hook, basically exposing a generic field on the types where it is no more generic (basically the example above without the explicit delegated property), however, I'm not recommending this (although I think for the template this might be a valid use case).
