### ISSUE TITLE
Allow subgraph contact info during Schema generation

### ISSUE THREAD

**Issue by fletchgqc** [ExpediaGroup/graphql-kotlin#1429]
Apollo uses the @contact directive and extension to the schema object to show contact information for subgraphs, as described here: https://www.apollographql.com/docs/studio/federated-graphs/#subgraph-contact-info. I think it's a pretty handy thing.

Is there any way to include this data during schema generation? I saw in the doco that directives can be created, but I'm not sure how to modify the `schema` object.

**Comment by dariuszkuc** [comment]
Hello 👋 
We are currently looking into supporting federation v2 spec and most likely will provide support for contracts at that time as well (or as a quick follow up).
