### ISSUE TITLE
WebFilter called twice per request

### ISSUE THREAD

**Issue by lars250698** [ExpediaGroup/graphql-kotlin#1430]
I'm running a federated Spring GraphQL-Server using Version 5.3.2. I'm trying to implement a WebFilter for logging information such as Response times, specific headers etc., but every WebFilter gets executed twice per request.

```
@Component
class LoggingFilter : WebFilter {
    private val logger: Logger = LoggerFactory.getLogger(this::class.java)

    override fun filter(exchange: ServerWebExchange, chain: WebFilterChain): Mono<Void> {
        val startTime = System.currentTimeMillis()
        return chain.filter(exchange)
            .doAfterTerminate {
                val responseTime = System.currentTimeMillis() - startTime
                logger.info("Response Time: $responseTime ms")
            }
    }
}
```

```
2022-04-25 16:47:07.667  INFO 16371 --- [ctor-http-nio-2] n.api.invo.filter.LoggingFilter          : Response Time: 252 ms
2022-04-25 16:47:07.873  INFO 16371 --- [ctor-http-nio-3] n.api.invo.filter.LoggingFilter          : Response Time: 458 ms
```

Is there any solution or workaround for this? I seemingly can't find anything regarding this issue in the official documentation.

**Comment by samuelAndalon** [comment]
Hello, could you provide more info ? from where are you firing the request ? Apollo Studio, Playground GraphiQL ?
what i would suggest is to filter your requests by path to only apply your filter logic on requests to `/graphql`.

On top of my head there is no reason why the filter could be executed twice, thats webflux logic and we do not subscribe to the original stream (request) twice.

**Comment by lars250698** [comment]
Hi,
I've tried firing the request via GraphQL-Playground (local installation) and cURL, both result in the same behaviour.

After further inspection, it looks like one of the logs results from an introspection query which is automatically triggered with every incoming request. This is my cURL request:
```
curl 'http://localhost:8080/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: file://' -H 'Authorization: some-auth-token' --data-binary '{"query":"query nhm {\n  someQuery(someParam: param) {\n    something\n  }\n}\n"}' --compressed
```

The debug logs show that `[ctor-http-nio-2]` handles the actual request, while `[ctor-http-nio-3]` handles the introspection query.

These introspection queries are executed by GraphQL-Playground simultaneously with the request (weirdly even when the request is executed via cURL with GraphQL-Playground open in the background, though this is probably incidental).

Is there any elegant way to exclude introspection queries from the logging logic in the filter?

**Comment by samuelAndalon** [comment]
that's exactly what i was wondering, its the playground it runs the instrospection each certain amount of time (configurable with `"schema.polling.interval": 1000`), few options:
1. disable polling in playground `"schema.polling.enable": false,`
2. add a default header to playground and check for it in your filter
3. do nothing given that for prod envs request will be send with an http client (client side node-fetch or ajax or server side a client like webclient)

i definetely don't advice for checking the request payload given that in webflux you can subscribe to the payload only once -- you will have to write a decorator to cache the payload of the request and IMHO that's an over kill.

**Comment by lars250698** [comment]
Yeah, that's what I thought as well. Thanks for the help!

**Comment by lars250698** [comment]
Yeah, that's what I thought as well. Thanks for the help!
