### ISSUE TITLE
GraalVM / GraphQL Expediagroup 

### ISSUE THREAD

**Issue by fmorissette-equisoft** [ExpediaGroup/graphql-kotlin#1441]
**Library Version**
com.expediagroup:graphql-kotlin-schema-generator:5.3.2

**Describe the bug**
Everything work has expected when comes the time to run it using GraalVM. The schema generator is crashing with this:

Caused by: io.github.classgraph.ClassGraphException: Uncaught exception during scan
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1606)
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1623)
        at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1636)
        at com.expediagroup.graphql.generator.internal.state.ClassScanner.<init>(ClassScanner.kt:36)
        at com.expediagroup.graphql.generator.SchemaGenerator.<init>(SchemaGenerator.kt:52)

The issue occurs during the call to **toFederatedSchema(config, queries, emptyList())**

The reflection causes the problem at runtime. Tried to setup GraalVM with build-time compilation

Seems related to this same issue: https://github.com/ExpediaGroup/graphql-kotlin/issues/1224

**To Reproduce**
Steps to reproduce the behavior. Please provide:
- compiling the library with GraalVM 22.0.0.2
-  running the final generated binary 
- Asking for the whatever graphql request

**Expected behavior**
Should properly return the GraphQL result even within GraalVM

**Comment by dariuszkuc** [comment]
GraphQL Kotlin v7 introduces new plugin goals that will generate GraalVM reachability metadata that will allow you to generate native images.

Related:
* [GraalVM reachability metadata PR](https://github.com/ExpediaGroup/graphql-kotlin/pull/1739)
* [Gradle task PR](https://github.com/ExpediaGroup/graphql-kotlin/pull/1743)
* [Maven MOJO PR](https://github.com/ExpediaGroup/graphql-kotlin/pull/1759)
* [documentation PR](https://github.com/ExpediaGroup/graphql-kotlin/pull/1764)
* [Spring Boot GraalVM support PR](https://github.com/ExpediaGroup/graphql-kotlin/pull/1769)

**Comment by fmorissette-equisoft** [comment]
Good! So my understanding is it's working out of the box in v7

**Comment by dariuszkuc** [comment]
You need to explicitly provide polymorphic type hierarchy + generate reachability metadata (through plugin). See the [docs](https://opensource.expediagroup.com/graphql-kotlin/docs/7.x.x/plugins/gradle-plugin-usage-graalvm)*.

*changes to support SpringBoot still need to get merged

**Comment by fmorissette-equisoft** [comment]
Thanks @dariuszkuc will look at this. I'm not currently using SpringBoot, i'm integrating it with Micronaut.

**Comment by fmorissette-equisoft** [comment]
The type is generated but without the extend and key attributes

**Comment by dariuszkuc** [comment]
Hello 👋 
Without a link to repository that reproduces the issue it is hard to say what is the underlying problem.

**Comment by fmorissette-equisoft** [comment]
No problem, I can't share that portion of code.
Thanks for your feedback :)
