### ISSUE TITLE
KotlinDataLoaderRegistryTest fails intermittently 

### ISSUE THREAD

**Issue by tapaderster** [ExpediaGroup/graphql-kotlin#1442]
**Library Version**
What version are you using? 
Running master locally

**Describe the bug**
KotlinDataLoaderRegistryTest fails intermittently .

**To Reproduce**
Simply run `./gradlew clean build` few times.

**Expected behavior**
The master branch should not have tests failing without any change.

Screenshot of random test fails with no code change:

<img width="1564" alt="image" src="https://user-images.githubusercontent.com/2609481/167727561-09be7d23-3392-4d82-84bb-2fb98f8cbab1.png">

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/2609481/167727609-d9951324-3043-4e58-8c75-809abeba607d.png">

**Comment by samuelAndalon** [comment]
fixed in https://github.com/ExpediaGroup/graphql-kotlin/pull/1449
