### ISSUE TITLE
allow queryFileDirectory to include its subdirectories

### ISSUE THREAD

**Issue by idanDaniel12** [ExpediaGroup/graphql-kotlin#1453]
**Is your feature request related to a problem? Please describe.**
I have many queries in my project and I would like to have some sort of order in my resources files. so I want to separate every logical group of queries to a related directory. to do it I want to have the ability to use queryFileDirectory as my parent dir which will contain multiple files in each dir.

**Describe the solution you'd like**
my suggestion: https://github.com/idanDaniel12/graphql-kotlin/pull/1
convert queryFileDirectory to iterate over all subdirectories in that path.

if this suggestion is valid I will add/update needed tests/documentation

`queryFileDirectory.get().asFileTree.toList().filter { file -> file.extension == "graphql" }`

**Alternative**
introduce new variable in GraphQLPluginClientExtension which will accept List of Directories

**Comment by dariuszkuc** [comment]
Hello 👋 
We probably could change the behavior but we already expose `queryFiles` property that allows you to specify arbitrary list of files, any reason not to use it?

i.e.
```kotlin
queryFiles = Files.walk(Paths.get("${project.projectDir}/src/main/resources"))
    .filter { it.fileName.endsWith(".graphql") }
    .map { it.toFile() }
    .collect(Collectors.toList())
```

**Comment by idanDaniel12** [comment]
You are totally right. I did not thought to utilize this field.
