### ISSUE TITLE
does graphql-kotlin support NonNegativeInt?

### ISSUE THREAD

**Issue by Taskeren** [ExpediaGroup/graphql-kotlin#1470]
I tried using Int, but it responded me with the "Validation error of type UnknownType: Unknown type NonNegativeInt".

**Comment by dariuszkuc** [comment]
Hello 👋
Take a look at https://opensource.expediagroup.com/graphql-kotlin/docs/schema-generator/writing-schemas/scalars/.

**Comment by Taskeren** [comment]
Sorry for my stupid questions. I just start to learn GQL today.

I tried using [graphql-java-extended-scalars](https://github.com/graphql-java/graphql-java-extended-scalars).
And I get "Validation error of type VariableTypeMismatch: Variable type 'NonNegativeInt' doesn't match expected type 'Int' @ 'set'". What should I do.

**Comment by dariuszkuc** [comment]
Any custom scalars have to be explicitly registered -> https://opensource.expediagroup.com/graphql-kotlin/docs/schema-generator/writing-schemas/scalars/#custom-scalars

**Comment by Taskeren** [comment]
Any example repo or code please.

For UUID, there a class UUID for register. But what class is for registering NonNegativeInt. When registering Int, there are more exceptions thrown.

**Comment by Taskeren** [comment]
Tried using custom class for NonNegativeInt

```kotlin
@JvmInline
value class NNInt(val i: Int)

object CustomSchemaGeneratorHooks : SchemaGeneratorHooks {

	override fun willGenerateGraphQLType(type: KType): GraphQLType? = when(type.classifier as? KClass<*>) {
		NNInt::class -> NonNegativeIntScalar.INSTANCE
		UUID::class -> ExtendedScalars.UUID
		else -> null
	}
}
```

```kotlin
suspend fun set(playCountOrder: Int?, publishTimeOrder: Int?, limit: NNInt?, skip: NNInt?, isHidden: Int?, musicTitle: String?, isOfficial: Int?, isRanked: Int?): List<SetModel> {
	return listOf(FakeSet)
}
```

And it resulted the IllegalStateException thrown from `invoke0()` for using wrong type of arguments to invoke the method.
The args are all type of Int and String and no NNInt exists.

Did I do the wrong thing?
Is there any annotation or something that can specify the GraphQL type of such fields?

Forgive my poor English.

**Comment by dariuszkuc** [comment]
Can you provide a link to a github repository with your setup? Scalar is called `NonNegativeInt` in `graphql-java-extended-scalars` so guessing it has to match your inline value class.

**Comment by Taskeren** [comment]
Setup: <https://github.com/Taskeren/Explode/blob/master/src/main/kotlin/explode/KtorGraphQLSchema.kt>
Error Function: <https://github.com/Taskeren/Explode/blob/a63360eaf11b7e54ae22fda35c30708b2dbe04d7/src/main/kotlin/explode/schema/GameDataQueryService.kt#L25>

Query:
```graphql
query fetchSets(
  $lim: NonNegativeInt
  $skip: NonNegativeInt
  $searchTitle: String
  $orderPlay: Int
  $orderTime: Int
  $hidden: Int
  $official: Int
  $ranked: Int
) {
  r: set(
    playCountOrder: $orderPlay
    publishTimeOrder: $orderTime
    limit: $lim
    skip: $skip
    isHidden: $hidden
    musicTitle: $searchTitle
    isOfficial: $official
    isRanked: $ranked
  ) {
    _id
    introduction
    coinPrice
    isGot
    isRanked
    noter {
      username
    }
    musicTitle
    composerName
    playCount
    chart {
      _id
      difficultyClass
      difficultyValue
    }
  }
}
```

Responding:
```json
{
  "errors": [
    {
      "message": "Exception while fetching data (/r) : argument type mismatch",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "r"
      ]
    }
  ]
}
```

**Comment by dariuszkuc** [comment]
Underlying problem is due to Kotlin having issues with nullable value classes -> https://youtrack.jetbrains.com/issue/KT-31141 (as called out in https://opensource.expediagroup.com/graphql-kotlin/docs/schema-generator/writing-schemas/scalars#inline-value-classes).

Update your Kotlin version to `1.7.0` and add explicit dependency on the `kotlin-reflect` (old version is pulled in transitively by `ktor` server and `jackson`), i.e.

```
implementation("org.jetbrains.kotlin:kotlin-reflect:1.7.0")
````

side note: you probably should also define custom value unboxer.
