### ISSUE TITLE
[Question] Supports modularization?

### ISSUE THREAD

**Issue by mpierucci** [ExpediaGroup/graphql-kotlin#1475]
Im trying to replace a ktor-kgraphql mock server deployed within an android app ( UI tests) with this library.

Ive followed this example https://github.com/ExpediaGroup/graphql-kotlin/tree/master/examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor

But keep getting `InvalidPackagesException: The configured packages do not contain any valid classes` 

The only thing I can think being different is that the code resided in a kotlin module within the android project. SO the question  is if having different modules could  be affecting the ClassScanner some how?

**Comment by dariuszkuc** [comment]
Hello 👋 
It is perfectly fine referencing graph objects from different libraries/jars as long as they are within specified supported packages.

**Comment by mpierucci** [comment]
Hi! Thanks for the quick reply. Thats good to know.
Unfortunately I have no clue whats going then. Im sure the package name is correct, maybe is an issue of running on android OS?.
Trying to put up a repo to reproduce just need to math the real setup.

**Comment by dariuszkuc** [comment]
Underlying issue seems to be related to the Android itself -> at runtime you won't have access to classfiles which we rely on during schema building process.

See -> https://github.com/classgraph/classgraph/discussions/567
Related -> https://github.com/ExpediaGroup/graphql-kotlin/issues/1224
