### ISSUE TITLE
@Deprecated, but only for the client

### ISSUE THREAD

**Issue by jmfayard** [ExpediaGroup/graphql-kotlin#1492]
![image](https://user-images.githubusercontent.com/459464/181576508-8c26245b-84f0-4f41-949e-342b58594b23.png)

**Is your feature request related to a problem? Please describe.**

It's cool that graphql-kotlin supports `@Deprecated` out of the box.

But often I want to mark something as deprecated for my clients
but not on my own code since I'm still implementing the feature.

Since I'm converting all my warnings in errors, I have to add `@Suppress("DEPRECATION")` everywhere.

**Describe the solution you'd like**

Add a `@GraphQLDeprecated("message")` annotation that would be sent to the client but not pollute my own code.

**Describe alternatives you've considered**

For the naming I chose something similar to `@GraphQLDocumentation("documentation")`

`@file:Suppress("DEPRECATION")` everywhere relevant but then I'm loosing the benefits of Kotlin's `@Deprecated` annotation

I could wire up my own annotation processor but it would be cool it worked out of the box just like `@Deprecated`

**Comment by smyrick** [comment]
Maybe another solution is to allow for more hooks for all the built-in logic of the library. The only part today that checks for the use of `@Deprecated` are in the extension functions: https://github.com/ExpediaGroup/graphql-kotlin/tree/master/generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions

For example this block: https://github.com/ExpediaGroup/graphql-kotlin/blob/7711942aaa4d368bffbb98c78b8da31726cf8957/generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/annotationExtensions.kt#L32

Most of usages rely on extending `KCallable`. There are a few exceptions for class properties and enums aka Fields.

**Comment by smyrick** [comment]
However, considering all the options, I think moving to the more explicit `@GraphQLDeprecated` actually does make sense as there is a difference between internal code and API types. Unfortunately we are now at a point where I don't think we can break that feature either so if we ever did change the default behavior, through the use of some hooks mentioned above we would still have to support the built-in `@Deprecated`

**Comment by jmfayard** [comment]
Oh for sure, I'm not for removing support for `@Deprecated`  it's nice that it's there

**Comment by jmfayard** [comment]
I had a shot here https://github.com/ExpediaGroup/graphql-kotlin/pull/1505
