### ISSUE TITLE
pojo support for query / mutation parameter

### ISSUE THREAD

**Issue by cryptoki** [ExpediaGroup/graphql-kotlin#1515]
up to version 5.x we could use our Java Pojos

```
public class SomeOldPojo {
  public String value;
}
```

```
  fun pojo(pojo: SomeOldPojo): String? = "hello ${pojo.value}"
```

```
query {
	pojo(pojo: {value: "abc"})
}
```

with the 6.x release the Jackson ObjectMapper is removed and therewith the java support. Is there a best practice to use / integrate old pojo?

little playground https://github.com/cryptoki/graphql-defaults

**Comment by dariuszkuc** [comment]
Hello 👋 
While Jackson is no longer used for object serialization/deserialization, POJOs should still be handled in the same way*.

*by using Java POJOs you are missing nullability information

**Comment by cryptoki** [comment]
@dariuszkuc thank you. what do you mean with `in the same way`?

If I'm using Java POJOs in the same way as I used it with `graphql-kotlin 5.x.x` I've got the following error
```
com.expediagroup.graphql.generator.exceptions.PrimaryConstructorNotFound: Invalid input object SomeOldPojo - missing public primary constructor
```

v5.x.x works well with the inside Jackson mapper.

**Comment by cryptoki** [comment]
add on info. 
we can't migration these Java POJOs to Kotlin. It's important to use the same java classes. We have a lot of services with java/groovy code using these POJOs.

**Comment by dariuszkuc** [comment]
@cryptoki correction, yes it is not in the "same" way as instead of reflections and Jackson we are now using constructor to pass in the parameters. Your exception states your POJO classes do not specify the appropriate primary constructor.

**Comment by cryptoki** [comment]
@dariuszkuc java classes does not have a `primary constructor`. 

how can we integrate / using our existing java pojo classes? It's important. see my little playground project linked in the top post.

```
query {
  pojo(pojo: {value: "abc"})
}
```

**Comment by dariuszkuc** [comment]
Looks like `primary` constructor designation is from Kotlin, so Java classes won't provide this metadata. We could potentially update our logic from

```kotlin
var targetConstructor = targetClass.primaryConstructor ?: throw PrimaryConstructorNotFound(targetClass)
```

to something like
```kotlin
var targetConstructor = targetClass.primaryConstructor
if (targetConstructor == null && targetClass.constructors.size == 1) {
  targetConstructor = targetClass.constructors.first()
}
if (targetConstructor == null) {
  throw PrimaryConstructorNotFound(targetClass)
}
```

This would still be somewhat limited (i.e. expects single all-args constructor as POJOs are system-types so their fields are considered non-null and required).

@samuelAndalon thoughts?

**Comment by samuelAndalon** [comment]
Yes, we will have the limitation of the lack of nullability  info, all arguments are going to be considered required and non-null, but i think we can keep the supporting POJOs constructor after removing the  usage of object mapper -- 
i can work in the fix.

**Comment by samuelAndalon** [comment]
as discussed we will provide support for non primary constructors, if multiple constructors an exception will be thrown, you can keep using POJOs but you will have to specify at least 1 constructor. 
As of now we are not going to provide support for matching properties which is something non trivial.
