### ISSUE TITLE
SpringGraphQLSubscriptionHandler cannot be overridden

### ISSUE THREAD

**Issue by emmanuelidi** [ExpediaGroup/graphql-kotlin#1522]
**Library Version**

6.2.0

**Describe the bug**

As noted in `GraphQLRequestHandler` the "subscriptions require more specific server [framework] logic and will need to be handled separately". The `SpringGraphQLSubscriptionHandler` implementation captures the logic for Spring. While it appears to be open for extension, the contract of `SpringGraphQLSubscriptionHandler.executeSubscription` is final which prevents the injection of an alternate implementation.  The bean declaration for the handler uses `ConditionalOnMissingBean` which suggests the intent to allow alternate implementations:

```
    @Bean
    @ConditionalOnMissingBean
    fun subscriptionHandler(
        graphQL: GraphQL,
        dataLoaderRegistryFactory: KotlinDataLoaderRegistryFactory
    ) = SpringGraphQLSubscriptionHandler(graphQL, dataLoaderRegistryFactory)
```

Given the history of the subscription handler, and the current implementation of `GraphQLRequestHandler`, it's likely that the intent was to make `SpringGraphQLSubscriptionHandler` be customizable and therefore leave the method declared as `open`.

**To Reproduce**

Attempt to create an alternate implementation bean of the same name (and have the Spring context fail at startup due to duplicate beans) or attempt to extend `SpringGraphQLSubscriptionHandler` (and get the pretty clear compile error).

**Expected behavior**

The method should be declared `open` to allow customization of the `executeSubscription` method behavior:

```
open class SpringGraphQLSubscriptionHandler(
    private val graphQL: GraphQL,
    private val dataLoaderRegistryFactory: KotlinDataLoaderRegistryFactory? = null
) {

   open fun executeSubscription(...
```

**Comment by dariuszkuc** [comment]
Subscription implementation in the `spring-server` is based on the old deprecated protocol so it didn't make sense to open it up. Use with caution.
