### ISSUE TITLE
Build plugins should allow configuring max parse tokens

### ISSUE THREAD

**Issue by dariuszkuc** [ExpediaGroup/graphql-kotlin#1526]
Generate SDL task/mojo currently do not allow configuring this option and instead rely on the defaults provided by `graphql-java`. Since it is possible to configure this option when build a GraphQL server, we should also allow configuring it in build plugins.

> @dariuszkuc I just saw this coming back with `graphql-kotlin` version 6.2.1. That version depends on `graphql-java` 19.1 which *does* allow to configure the `maxTokens` in `ParserOptions`, but I do not see that option being exposed by the Gradle plugin. Am I missing something?

_Originally posted by @sschuberth in https://github.com/ExpediaGroup/graphql-kotlin/issues/1303#issuecomment-1222215513_

**Comment by samuelAndalon** [comment]
we have 2 options:
1. Manually set the default parser options `ParserOptions.setDefaultParserOptions(ParserOptions.newParserOptions().maxTokens(<YOUR_NEW_VALUE>).build())`
2. Add parserOptions by executionInput https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/ParseAndValidate.java#L64

**Comment by dariuszkuc** [comment]
@samuelAndalon yes thats how you configure it on the server, this issue is about the build plugin allowing this configuration to generate the SDL

**Comment by sschuberth** [comment]
Indeed, it would be nice if the whole `ParserOptions` would be exposed as a Gradle plugin extension, so things like `maxToken` can easily be set from the Gradle build script DSL.

**Comment by sschuberth** [comment]
Just a friendly ping to @dariuszkuc: Is this planned to be worked on any time soon? It currently blocks us from using GitHub's GraphQL schema with the latest version of this plugin, which we'd like to take into use for Ktor 2 support.
