### ISSUE TITLE
schema generator should fail if input types with nullable fields do not define a default value

### ISSUE THREAD

**Issue by samuelAndalon** [ExpediaGroup/graphql-kotlin#1527]
### Discussed in https://github.com/ExpediaGroup/graphql-kotlin/discussions/1525

<div type='discussions-op-text'>

<sup>Originally posted by **Anthonyzou** August 22, 2022</sup>
With the changes in version 6.2.0 and above, input types that could be nullable did not require a default value.

This code would work before version 6.2.0

```kotlin
@GraphQLDescription("")
data class Book(
    val title: String?
)
```

Now I get the error `No argument provided for a required parameter: parameter #0...`  unless I change the input type to:

```kotlin
@GraphQLDescription("")
data class Book(
    val title: String? = null
)
```</div>

**Comment by dariuszkuc** [comment]
I don't think this can be fixed without being able to access default values (https://github.com/ExpediaGroup/graphql-kotlin/issues/53). There is no way to programmatically decide whether default value is provided or not (without actually calling the function).

**Comment by xenomachina** [comment]
> There is no way to programmatically decide whether default value is provided or not (without actually calling the function).

You can use [KParameter.isOptional](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.reflect/-k-parameter/is-optional.html).

**Comment by xenomachina** [comment]
As I mentioned in the linked discussion, I have already implemented these checks in our `SchemaGeneratorHooks`. The check is something like:

``` kotlin
if (inputParam.type.isMarkedNullable) {
    require(inputParam.isOptional) {
        "$inputClassName.${inputParam.name} is nullable but not optional"
    }
}
```

**Comment by samuelAndalon** [comment]
we can add more custom logic here
https://github.com/ExpediaGroup/graphql-kotlin/blob/master/generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/hooks/SchemaGeneratorHooks.kt#L144

adding this logic when unwrapped is `GraphQLInputObjectType`

```kotlin
type.jvmErasure.primaryConstructor?.parameters?.forEach { param ->
  if (param.type.isMarkedNullable && !param.isOptional) {
   // just for demo, we can use a custom exception
    throw RuntimeException("${type.jvmErasure.simpleName}.${param.name} is nullable but not optional")
  }
}
```

**Comment by xenomachina** [comment]
> @xenomachina i would assume you did it in the `didGenerateGraphQLType` hook ?

I actually used the `didGenerate*Field` hooks.

I was thinking about this some more, and realized that instead of prohibiting this combination, it might be possible to treat `null` as the "default default" for nullable parameters. I just made a PR that demonstrates this: https://github.com/ExpediaGroup/graphql-kotlin/pull/1528

**Comment by samuelAndalon** [comment]
released https://github.com/ExpediaGroup/graphql-kotlin/releases/tag/6.2.2
