### ISSUE TITLE
Couldn't able to find generated folder in Android project

### ISSUE THREAD

**Issue by puliajay43** [ExpediaGroup/graphql-kotlin#1529]
I am trying to `graphql-kotlin` in my Android project

Able to get the queries and mutations and they are getting imported from my package `com.example`
While running the app, it is throwing compilation error `Unresolved type` 

I am not getting generated folder in `com.expediagroup.graphql.generated...`

Could anyone please help me out with this in android?

**Comment by dariuszkuc** [comment]
Hello 👋 
You might need to explicitly configure source sets in your Gradle build file.

See [test project](https://github.com/ExpediaGroup/graphql-kotlin/tree/master/plugins/graphql-kotlin-gradle-plugin/src/integration/android/androidGraphQLClient) which we use for our integration testing.

**Comment by puliajay43** [comment]
Fixed 
Thanks!!
