### ISSUE TITLE
GraphQLTypeNotSupportedException: Cannot convert kotlinx.coroutines.flow.Flow

### ISSUE THREAD

**Issue by hantsy** [ExpediaGroup/graphql-kotlin#1531]
**Library Version**

* Spring Boot 2.7.3
* Graphql Kotlin 6.2.2
* Kotlin Coroutines 1.6.4

**Describe the bug**

The `Query` returns a Kotlin Flow type. 

**To Reproduce**
Steps to reproduce the behavior. Please provide:

Check my example project: https://github.com/hantsy/spring-graphql-sample/blob/master/graphql-kotlin/src/main/kotlin/com/example/demo/gql/datafetchers/Queries.kt#L21

**Expected behavior**

Koltin Flow should be supported like a Collection, POJO type etc in Query.

**Comment by samuelAndalon** [comment]
Hello, Flow is supported only for subscriptions, for queries / mutations i would assume internally you would want to collect the stream into a List, if so, you can leverage the `SchemaGeneratorHook` `willResolveMonad` to provide the logic to collect the Flow to a List probably using [Flow.toList](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/to-list.html)

more info https://opensource.expediagroup.com/graphql-kotlin/docs/schema-generator/execution/async-models/#rxjavareactor

**Comment by hantsy** [comment]
> if so, you can leverage the SchemaGeneratorHook willResolveMonad to provide the logic to collect the Flow into a List probably using [Flow.toList](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/to-list.html)

I found the Flow Subscription provides a config for Flow type, but it is converted the parameterized type, not a list.

If I configured this Flow in Query/Mutations using `willResolveMonad ` as you suggested, there will be a conflict.

**Comment by hantsy** [comment]
When I just enabled Flow Subscription Hooks, I got the issue #https://github.com/ExpediaGroup/graphql-kotlin/discussions/1532
