### ISSUE TITLE
How to deserialise nested JSON response?

### ISSUE THREAD

**Issue by puliajay43** [ExpediaGroup/graphql-kotlin#1542]
Throwing `SerializationExpection` when the response is a nested JSON
Example:
`{
  "a": {
    "b": "c"
  }
}`

But, When the response JSON s simple i.e, `{"a": "b"}` it is working fine.

I am using `KotlinX Serializable` with `GraphQLKtorClient`.

Do we need to write any custom serializable class?

**Comment by dariuszkuc** [comment]
Hello 👋 
Our build plugins (Maven and Gradle) should generate you valid data classes that match your query.  You shouldn't have to write any custom code. See [examples](https://github.com/ExpediaGroup/graphql-kotlin/tree/master/examples/client).
