### ISSUE TITLE
[Ktor + gradle plugin] 5.5.0 to 6.2.5 regression around Content-Length & Transfer-Encoding

### ISSUE THREAD

**Issue by maxpiepenbrink** [ExpediaGroup/graphql-kotlin#1560]
**Library Version**
6.2.5

**Describe the bug**
This is likely not an expedia graphql bug, but it seems prudent to start here in case others run into this, or perhaps the maintainers here have more experience and can think of an elegant fix.

The short version is: version 5.x uses Ktor in a way where the Content-Length header is present when running the `:graphqlIntrospectSchema` task. Versions 6.x result in NO Content-Length header. From what I can see, the Ktor Apache engine + Jackson Ktor plugin never resolve a Content-Length, so the engine defaults to `Transfer-Encoding: Chunked`

While most request handlers probably don't have issues with chunked encoding, we are using this library in a context where we have a 3rd party vendor whose GraphQL server does NOT handle chunked encoding, so this regression is causing us heartburn as we need to upgrade this library to be in lock-step other dependency upgrades (kotlin 1.7, spring, etc), and not be left behind.

We can work around this with static schema files we fetch from 5.x (the /sdl endpoint isn't supported here, so we must use introspection) or other hacks, but it's not ideal.

**To Reproduce**
Steps to reproduce the behavior. Please provide:

- Schema Configuration

This is happening in a very vanilla usage context, with a very simple graphql config like:
```
graphql {
    client {
        endpoint = "http://$host/graphql"
        packageName = "com.testingmyissue.graphql.generated"
        queryFileDirectory = "${project.projectDir}/src/main/resources/gql"
    }
}
```

- Kotlin code used to generate the schema

Compare the request headers from a `:graphqlIntrospectSchema` request in version 5.5.0 to 6.2.5 (or probably any other minor versions).

**Expected behavior**

The above configs are left totally alone (but with a valid remote host, of course), and you can see the regression in this comparison, having changed only the gradle plugin version from 5.5.0 to 6.2.5:

Example 5.5.0 request headers:
```
POST /graphql HTTP/1.1 
Accept: application/json 
Accept-Charset: UTF-8 
User-Agent: Ktor client 
Content-Length: 1761 
Content-Type: application/json 
Host: [[omitted]]
Connection: Keep-Alive 
```

Example 6.2.5 request headers:
```
POST /graphql HTTP/1.1 
Accept: application/json 
Accept-Charset: UTF-8 
User-Agent: Ktor client 
Transfer-Encoding: chunked 
Content-Type: application/json 
Host: [[omitted]
Connection: Keep-Alive 
```

**Comment by maxpiepenbrink** [comment]
The seemingly relevant areas are [here in 5.x.x](https://github.com/ExpediaGroup/graphql-kotlin/blob/5.x.x/plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/introspectSchema.kt#L136-L160) and [here in 6.x.x](https://github.com/ExpediaGroup/graphql-kotlin/blob/6.x.x/plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/introspectSchema.kt#L134-L169)

I did pull this repo down and try out some hacky solutions just to prove out a potential fix in my local environment, but I imagine this kind of workaround is less than ideal:
```kotlin
    runBlocking {

        // by doing this here we basically get no benefit from the Jackson ContentNegotiation 
        // plugin
        val om = ObjectMapper()
        val bytePayload = om.writeValueAsString(
            mapOf(
                "query" to INTROSPECTION_QUERY,
                "operationName" to "IntrospectionQuery"
            )
        ).toByteArray() // UTF-8 by default

        val introspectionResult = try {
            client.post {
                url(endpoint)
                contentType(ContentType.Application.Json)
                httpHeaders.forEach { (name, value) ->
                    header(name, value)
                }
                header("Content-Length", payload.size) // UTF-8 encoded byte length
                setBody(payload) // <-- pass in the raw bytes
                expectSuccess = true
            }.body<Map<String, Any?>>()
        }
    }
```

This hacky fix DID allow the 6.x branch to work against the offending endpoint, but it is clearly a less-than-ideal workaround when Ktor + Ktor-Jackson + Ktor-Apache were all doing this appropriately in the 5.x configuration of all these dependencies.

**Comment by dariuszkuc** [comment]
Hello 👋 
This is due to the change in behavior in Ktor v2.0. I opened up [YouTrack KTOR-4904 issue](https://youtrack.jetbrains.com/issue/KTOR-4904/Ktor-client-Jackson-converter-support-Content-Length-header) to track it.

**Comment by maxpiepenbrink** [comment]
I'm keeping an eye on the PR the Ktor folks just threw up to add the optionality we'd want here: https://github.com/ktorio/ktor/pull/3175/files

I can throw a PR up for it once we have a Ktor 2.x release to work against.

**Comment by maxpiepenbrink** [comment]
Looks like the fix is available as of ktor's `2.2.0-eap-529` preview releases now. Testing this change to the graphql-kotlin plugin locally in my problem environment, I was able to verify that indeed fixes the issue!

e.g.

```
# /build.gradle.kts
maven {
   url = uri("https://maven.pkg.jetbrains.space/public/p/ktor/eap")
}
```

```
# /gradle.properties
ktorVersion = 2.2.0-eap-529
```

```
// /plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/introspectSchema.kt
     install(ContentNegotiation) {
-        jackson()
+        jackson(streamRequestBody = false)
     }
```

**Comment by maxpiepenbrink** [comment]
@dariuszkuc Hey Darius! It looks like the 2.2.x releases are cut, and the 2.2.0 mentions the fix we pushed for: https://github.com/ktorio/ktor/releases/tag/2.2.0

Can you recommend next steps? Would you like me to throw up a PR? It'd be great if this could be addressed as a 6.x fix for us.

**Comment by samuelAndalon** [comment]
related issue: 
https://github.com/ExpediaGroup/graphql-kotlin/issues/1611

@maxpiepenbrink contributions are always welcomed!.

**Comment by maxpiepenbrink** [comment]
@samuelAndalon I'll find some time soon -- if I can get a PR up for it, do you think a 6.x release with Ktor 2.2.x is in the cards?

**Comment by samuelAndalon** [comment]
yes, once we make the update, we can cherry pick it to 6.x.x

**Comment by dariuszkuc** [comment]
> @samuelAndalon I'll find some time soon -- when I get a PR up for it, do you think a 6.x release with Ktor 2.2.x is in the cards?

@maxpiepenbrink I don't think it will work with 6.x release (we are using Kotlin 1.6 whereas Ktor is based on Kotlin 1.7 since v `2.1.0`).

**Comment by maxpiepenbrink** [comment]
@dariuszkuc Makes sense! Interesting though, I at least had the introspect-schema task working locally with ktor 2.2.0-eap off a 6.x branch of expedia-graphql and that seemed to work just fine for that specific thing I was fixing. This doesn't exercise any other pathways, however, and I didn't run any other special tests to see if using ktor 2.2.0 broke any other functionality. Not surprising to me if that wont work for some reason :)
