### ISSUE TITLE
Update ktor sample for subscriptions

### ISSUE THREAD

**Issue by rocketraman** [ExpediaGroup/graphql-kotlin#1587]
**Is your feature request related to a problem? Please describe.**

There is a ktor sample in the source (https://github.com/ExpediaGroup/graphql-kotlin/tree/master/examples/server/ktor-server). However, as far as I know this sample does not demo GraphQL subscriptions.

**Comment by sustainjane98** [comment]
I would really like to see such an example. But it seems like it isn't even working, bc when I returned a custom Publisher, I get an exception, that the type of it cannot be read out.

**Comment by dariuszkuc** [comment]
example added in https://github.com/ExpediaGroup/graphql-kotlin/pull/1774
