### ISSUE TITLE
use new Spring Boot auto-configuration

### ISSUE THREAD

**Issue by snv** [ExpediaGroup/graphql-kotlin#1609]
**Library Version**
com.expediagroup:graphql-kotlin-spring-server:7.0.0-alpha.0

**Describe the bug**
When switchen to Spring Boot 3 `com.expediagroup.graphql.server.spring.GraphQLAutoConfiguration` does not get executed, because the old way of registering them via `spring.factories` has been removed.
The new way needs a `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`-File.

**Additional Info**
Details about [the introduction of the new mechanism](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#auto-configuration-registration), and [the deactivation of the old one](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files).

As a workaround i can get my project to work, by registering `com.expediagroup.graphql.server.spring.GraphQLAutoConfiguration` myself with a  `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports` in my own application.

**Comment by hantsy** [comment]
>As a workaround i can get my project to work, by registering com.expediagroup.graphql.server.spring.GraphQLAutoConfiguration myself with a META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports in my own application.

Alternatively, add `@ImportAutoConfiguration` on your Spring application class to import it manually.
