### ISSUE TITLE
Upgrade to Ktor 2.2.1

### ISSUE THREAD

**Issue by sschuberth** [ExpediaGroup/graphql-kotlin#1611]
**Describe the solution you'd like**

Please upgrade Ktor to the newly release version 2.2.0 (from [current version 2.0.3](https://github.com/ExpediaGroup/graphql-kotlin/blob/6699da26533c4fe271ce5ecf9cc4bf9ecc09fc56/gradle.properties#L29)).

**Describe alternatives you've considered**

Sticking to Ktor 2.0.3 / up to 2.1.3 downstream is technically possible, but consumer will not be able to beneiot from [new Ktor 2.2.0 features](https://github.com/ktorio/ktor/blob/main/CHANGELOG.md#220).

**Additional context**

Upgrading downstream to Ktor 2.2.0 results in `java.lang.NoClassDefFoundError: kotlinx/atomicfu/AtomicFU`.

**Comment by sschuberth** [comment]
> Upgrading downstream to Ktor 2.2.0 results in `java.lang.NoClassDefFoundError: kotlinx/atomicfu/AtomicFU`.

Actually, that was a bug in Ktor 2.2.0 that was [fixed in version 2.2.1](https://github.com/ktorio/ktor/blob/main/CHANGELOG.md#221).

I'll anyway leave this issue open as upgrading Ktor is probably still a good idea.

**Comment by samuelAndalon** [comment]
we will add this to our 7.x.x milestone, contributions are always welcome!

**Comment by sschuberth** [comment]
Hmm, looks like this project is using some very long paths (like `executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/execution/SyncExecutionExhaustedInstrumentationParameters.kt`) which may fail to get checked out on Windows if the working tree parent also is already quite long...
