### ISSUE TITLE
Generated schema is incompatible with Federation v2

### ISSUE THREAD

**Issue by hrkfdn** [ExpediaGroup/graphql-kotlin#1617]
**Library Version**
6.3.2

**Describe the bug**
Currently, the schema generation in 6.3.2 will generate an invalid output containing a `_FieldSet` scalar instead of `FieldSet`. Such a schema will be rejected by Apollo Studio.

**Expected behavior**
The change in https://github.com/ExpediaGroup/graphql-kotlin/pull/1547 should probably be backported to the v6 branch.

**Comment by hrkfdn** [comment]
Fixed via #1618

**Comment by samuelAndalon** [comment]
https://github.com/ExpediaGroup/graphql-kotlin/releases/tag/6.3.3
