### ISSUE TITLE
[client] Allow Automatic Persisted Queries

### ISSUE THREAD

**Issue by samuelAndalon** [ExpediaGroup/graphql-kotlin#1640]
**Is your feature request related to a problem? Please describe.**
[graphql-kotlin-server recently added Automatic Persisted Queries](https://opensource.expediagroup.com/graphql-kotlin/docs/server/automatic-persisted-queries/#automaticpersistedqueriesprovider) to allow clients to send a hash representation of a graphQL operation instead of the actual query string.

**Describe the solution you'd like**
Allow graphql-kotlin-client to implement APQ requests

**Comment by gumimin** [comment]
Hi @samuelAndalon 
I am thinking of implementing this Issue.
Please let me know your implementation plan if you don't mind.

1. Is the scope of this Issue to add an interface to graphql-kotlin-client? (is it unnecessary to add implementations to graphql-kotlin-ktor-client and graphql-kotlin-spring-client?)

2. Is it correct to the modifications are as follows.

Add `AutomaticallyPersistedQueriesSettings` to `com.expediagroup.graphql.client.types`

```kotlin
interface AutomaticPersistedQueriesSettings<T : Any> {
    val enabled: Boolean
    val httpMethodForHashedQueries: T
    val httpMethodForDocumentQueries: T
```

Add the `automaticPersistedQueriesSettings` property to `com.expediagroup.graphql.client.GraphQLClient`

```kotlin
interface GraphQLClient<RequestCustomizer> {
    val automaticPersistedQueriesSettings: AutomaticPersistedQueriesSettings<*>
    ...
}
```

Add the `extensions` property to `com.expediagroup.graphql.client.types.GraphQLClientRequest`

```kotlin
interface GraphQLClientRequest<T : Any> {
    ...
    val extensions: Any?
        get() = null
    ...
}
```

**Comment by samuelAndalon** [comment]
Hello, the plan is to enable this from a flag, i think thats the only thing we can let clients to configure, regarding the hash, it has to be sha256 and pretty much follow this pattern

https://opensource.expediagroup.com/graphql-kotlin/docs/server/automatic-persisted-queries/

**Comment by gumimin** [comment]
@samuelAndalon 
Thank you for your reply.
Is the implementation correct as below?
https://github.com/gumimin/graphql-kotlin/commit/b7d97144802c2d682f4491621149e00359c571c3

**Comment by gumimin** [comment]
Hi @samuelAndalon 
I made a pull request, could you review it?
https://github.com/ExpediaGroup/graphql-kotlin/pull/1802

**Comment by dariuszkuc** [comment]
Resolved in https://github.com/ExpediaGroup/graphql-kotlin/pull/1802
