### ISSUE TITLE
getValueFromDataLoader is broken after changes to context

### ISSUE THREAD

**Issue by jarlehansen** [ExpediaGroup/graphql-kotlin#1649]
**Library Version**
6.3.5

**Describe the bug**
The code in `getValueFromDataLoader` and `getValuesFromDataLoader` uses the old context, which will effect the dataloaders getting an empty GraphQLContext.
```
return loader.load(key, this.graphQlContext)
```

**To Reproduce**
Use either `getValueFromDataLoader` or `getValuesFromDataLoader`, and access the GraphQLContext in a dataloader.

**Expected behavior**
It should be updated to pass inn DataFetchingEnvironment instead:
```
fun <K, V> DataFetchingEnvironment.getValueFromDataLoader(dataLoaderName: String, key: K): CompletableFuture<V> {
    val loader = getDataLoader<K, V>(dataLoaderName) ?: throw MissingDataLoaderException(dataLoaderName)
    return loader.load(key, this) // <-- use this instead of context here
}

fun <K, V> DataFetchingEnvironment.getValuesFromDataLoader(dataLoaderName: String, keys: List<K>): CompletableFuture<List<V>> {
    val loader = getDataLoader<K, V>(dataLoaderName) ?: throw MissingDataLoaderException(dataLoaderName)
    return loader.loadMany(keys, listOf(this)) // <-- use this instead of context here
}
```
By doing this the `BatchLoaderEnvironment.getGraphQLContext()` will work as intended

**Comment by samuelAndalon** [comment]
im not opposed at this idea, but if we change the `keyContext` type, then people that is still using the deprecated context will be facing a breaking change.

what i would suggest is to if possible, do not use this indirection extension functions and just call

```kotlin
dataFetchingEnvironment.getDataLoader<K, V>(dataLoaderName)?.load(key, dataFetchingEnvironment) 
// or if still using deprecated context
dataFetchingEnvironment.getDataLoader<K, V>(dataLoaderName)?.load(key, this.getContext()) 
// or if still using new context
dataFetchingEnvironment.getDataLoader<K, V>(dataLoaderName)?.load(key, this.graphqlContext) 
```

graphql kotlin `6.x.x` still supports both contexts, so we cannot move from one to another in this specific version.

[in pre-release we already make the change to pass new context](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/extensions/dataFetchingEnvironmentExtensions.kt#L38) given that we already removed all references of deprecated context

**Comment by samuelAndalon** [comment]
i agree, we will update documentation to mention this, also, what could do is having a null check for old context, in case null use the graphQLContext

**Comment by jarlehansen** [comment]
That is a good idea :)
