### ISSUE TITLE
Simplify support for auto-generated data classes

### ISSUE THREAD

**Issue by a8t3r** [ExpediaGroup/graphql-kotlin#1665]
**Is your feature request related to a problem? Please describe.**
Usually auto-generated sources files from IDL (`thrift`, `protobuff`, etc) are not intended for modifications, which complicates usage of schema generator from `graphql-kotlin` library.

**Describe the solution you'd like**
Consider example class `Course`, generated from some IDL:
```kotlin
data class AutoGeneratedCourse(
    val id: Int,
    val name: String? = null,
    val universityId: Int? = null,
    val bookIds: List<Int> = listOf()
)
```
Let's introduce additional abstraction `TypeMixin`, which will enrich data classes for proper `graphql-kotlin` support:
```kotlin
class CourseMixin : TypeMixin {
  // specify model class to be enriched
  override fun supports() = AutoGeneratedCourse::class
 
  // specify functions to be appended for graphql object type during schema generation
  fun books(dataFetchingEnvironment: DataFetchingEnvironment): CompletableFuture<List<Book>> {
    val course = env.getSource<AutoGeneratedCourse>()
    return dataFetchingEnvironment.getValueFromDataLoader(BookDataLoader.dataLoaderName, course.bookIds)
  }
}
```
Schema generator should create `GraphQLObjectType` not only from data class properties, but also from functions of provided mixins.

I implemented the draft of this proposal in [branch](https://github.com/ExpediaGroup/graphql-kotlin/compare/master...a8t3r:graphql-kotlin:mixin-support).

**Comment by dariuszkuc** [comment]
Hello 👋 
As you mentioned those auto-generated classes are not intended for modifications and they often (especially in case of protobuf) come with tons of extra code generated so they can be used seamlessly with the target framework.

Using them to expose them directly in your schema is IMHO a bad idea and would recommend to use some proper abstractions. That being said, you should be able to easily use the hooks to modify the schema generation process to include/exclude some of the object fields.
