### ISSUE TITLE
Spring server not bootstrapping correctly when following instructions in documentation/examples

### ISSUE THREAD

**Issue by GV94** [ExpediaGroup/graphql-kotlin#1679]
**Library Version**
- 6.3.6
- 7.0.0-alpha.3

**Describe the bug**
When setting up a spring server, by referring to the docs and examples below, the server does not bootstrap correctly. Navigating to `http://localhost:8080/graphiql` (or any other url) results in a 404. However, when downgrading dependencies (java version, spring, graphql-kotlin-spring-server) to match what is used in [this article](https://medium.com/@sven_50828/writing-a-spring-boot-graphql-api-in-kotlin-a306116bb8e0), it works.
 
- [docs](https://opensource.expediagroup.com/graphql-kotlin/docs/7.x.x/server/spring-server/spring-overview)
- [example 1](https://github.com/ExpediaGroup/graphql-kotlin/tree/master/servers/graphql-kotlin-spring-server)
- [example 2](https://github.com/ExpediaGroup/graphql-kotlin/tree/master/examples/server/spring-server) 

**To Reproduce**
Please refer to [this reproduction repository](https://github.com/GV94/graphql-kotlin-not-working-repro). The main branch contains the non-working example, and there is a [PR](https://github.com/GV94/graphql-kotlin-not-working-repro/pull/1/files) to the main branch demonstrating the working example with downgraded dependencies.

**Expected behavior**
The server should bootstrap correctly and serve the graphiql user interface at `localhost:8080/graphiql`

Edit: updated endpoint from `/playground` to `/graphiql`

**Comment by samuelAndalon** [comment]
Hello, graphql-playground is now in deprecation process and is disabled by default, this change was introduced in 
https://github.com/ExpediaGroup/graphql-kotlin/pull/1623

and if you want to keep using playground you will have to explicitly enable it like this
```yaml
graphql:
  playground:
    enabled: true
```

graphql playground was deprecated in favor of graphiql, which is the official IDE under graphql foundation

**Comment by GV94** [comment]
and just to add:

```yaml
graphql:
  playground:
    enabled: true
```
does not work in the repro either

**Comment by samuelAndalon** [comment]
ok, i took a closer look at your repro repo, and there are a couple of things wrong:

1. you are using spring-boot 3.0.2 which is not compatible with graphql-kotlin-spring-server [(as it uses 2.7.2)](https://github.com/ExpediaGroup/graphql-kotlin/blob/6.x.x/gradle.properties#L35)
2. also you need to match the graphql-java version that the graphql-kotlin version is using, as the spring bom will attempt to pull the version of graphql-java that is specified there. in this case we use graphql-java 19.2
3. kotlin version should be 1.6.21

if you want to use spring boot 3, you can try the 7.x.x alpha releases.

**Comment by samuelAndalon** [comment]
after fixing your dependencies im able to run the server
![image](https://user-images.githubusercontent.com/6611331/220269518-6a9318f3-ff0b-4622-baa7-f03be33038ac.png)

**Comment by samuelAndalon** [comment]
```kts
plugins {
	id("org.springframework.boot") version "2.7.2"
	kotlin("jvm") version "1.6.21"
	kotlin("plugin.spring") version "1.6.21"
}

group = "com.example"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

repositories {
	mavenCentral()
}

dependencies {
	implementation("org.springframework.boot:spring-boot-starter-webflux")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("io.projectreactor.kotlin:reactor-kotlin-extensions")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib")
	implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor")
	implementation("com.expediagroup:graphql-kotlin-spring-server:6.3.6")
	implementation("com.graphql-java:graphql-java:19.2")
	testImplementation("org.springframework.boot:spring-boot-starter-test")
	testImplementation("io.projectreactor:reactor-test")
}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs = listOf("-Xjsr305=strict")
		jvmTarget = "1.8"
	}
}

tasks.withType<Test> {
	useJUnitPlatform()
}

```

**Comment by GV94** [comment]
Ah, I see. I can indeed get it to work with spring boot 3 and java 17 by using pre-relase version `7.0.0-alpha.3`. I never tried that in combination with `/graphiql`. Thanks a lot for clearing that out for me.
