### ISSUE TITLE
How to use the 7.0.0-alpha.3 ktor kotlin-server?

### ISSUE THREAD

**Issue by ronjunevaldoz** [ExpediaGroup/graphql-kotlin#1691]
is the 7.0.0-alpha.3 already published in the maven? cause dependency could not be resolve using below. It was working properly using `6.4.0`

// build.gradle.kts
```kotlin
repositories {
    mavenCentral()
    maven { url = uri("https://maven.pkg.jetbrains.space/public/p/ktor/eap") }
    maven { url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots") }
}

dependencies {
   implementation("com.expediagroup:graphql-kotlin-ktor-server:7.0.0-alpha.3")
}
```
// build output
```
Could not resolve com.expediagroup:graphql-kotlin-ktor-server:7.0.0-alpha.3.
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

```

**Comment by samuelAndalon** [comment]
client ? server ?
```
com.expediagroup:graphql-kotlin-spring-server:7.0.0-alpha.3
```

**Comment by ronjunevaldoz** [comment]
> 

I'm trying to get the latest plugin for ktor kotlin-server using `com.expediagroup:graphql-kotlin-ktor-server:7.0.0-alpha.3` but its not working.

**Comment by samuelAndalon** [comment]
error logs, repro steps, even better, a repro repo ?

**Comment by ronjunevaldoz** [comment]
// build.gradle.kts
```kotlin
repositories {
    mavenCentral()
    maven { url = uri("https://maven.pkg.jetbrains.space/public/p/ktor/eap") }
    maven { url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots") }
}

dependencies {
   implementation("com.expediagroup:graphql-kotlin-ktor-server:7.0.0-alpha.3")
}
```
// build output
```
Could not resolve com.expediagroup:graphql-kotlin-ktor-server:7.0.0-alpha.3.
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

```

**Comment by dariuszkuc** [comment]
Please provide a link to a repository that reproduces the issue, code above looks correct and the artifact is available on [Maven Central](https://central.sonatype.com/artifact/com.expediagroup/graphql-kotlin-ktor-server/7.0.0-alpha.3).

**Comment by ronjunevaldoz** [comment]
> Please provide a link to a repository that reproduces the issue, code above looks correct and the artifact is available on [Maven Central](https://central.sonatype.com/artifact/com.expediagroup/graphql-kotlin-ktor-server/7.0.0-alpha.3).

I think this is a java compatibility issue. What is the minimum java version requirement for 7.0.0-alpha.3?

**Comment by ronjunevaldoz** [comment]
After using java 17, the dependency now is working.

```
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
```

**Comment by dariuszkuc** [comment]
Yep v7 requires Java 17.
