### ISSUE TITLE
Ktor request validation for graphql support

### ISSUE THREAD

**Issue by ronjunevaldoz** [ExpediaGroup/graphql-kotlin#1697]
**Is your feature request related to a problem? Please describe.**
I needed to add ktor request validation for graphql, but the library don't have an existing utils to get the variables actual class object.

**Describe the solution you'd like**
I wanted to have something like below. [ktor-request-validation](https://ktor.io/docs/request-validation.html#validation-function)

```kotlin
@kotlinx.serialization.Serializable
data class JsonGraphQLRequest(
    val query: String = "",
    val operationName: String = "",
    val variables: JsonObject = JsonObject(emptyMap()),
    val extensions: JsonObject = JsonObject(emptyMap()),
)
```
// sample request parser
```kotlin
class KtorGraphQLRequestParser : GraphQLRequestParser<ApplicationRequest> {
    @Suppress("BlockingMethodInNonBlockingContext")
    override suspend fun parseRequest(request: ApplicationRequest): GraphQLServerRequest = try {
        val rawRequest = request.call.receive<JsonGraphQLRequest>()
        GraphQLRequest(
            query = rawRequest.query,
            operationName = rawRequest.operationName,
            variables = rawRequest.variables,
            extensions = rawRequest.extensions
        )
    } catch (e: IOException) {
        throw IOException("Unable to parse GraphQL payload.")
    }
}
```

```kotlin
install(RequestValidation) {
   // example possible format of graphql request validation
    validate<JsonGraphQLRequest> { graphQLRequest ->
        val inputs = graphQLRequest.variables.mapValues { va->
            AppJson.decodeFromJsonElement<GraphQLInput>(va.value)
        }
        var result: ValidationResult =  ValidationResult.Valid
        inputs.forEach { i->
            val input = i.value
            if(input is UserCredentials) {
                if (input.username.count() < 4) {
                    result = ValidationResult.Invalid("A user name should be at-least 5 characters")
                    return@forEach
                }
            }
        }
        result
    }
}
```

Resulting in a non expected graphql result. Which is `GraphQLServerError`
```kotlin
data class GraphQLServerError(
    val message: String,
    val locations: List<GraphQLSourceLocation>? = null,
    val path: List<Any>? = null,
    val extensions: Map<String, Any?>? = null
)

```
```kotlin
// not sure how do I bypass this to get the actual `GraphQLServerError` response.
exception<RequestValidationException> { call, cause ->
   call.respond(HttpStatusCode.BadRequest, mapOf("message" to cause.reasons.joinToString()))
}
```
<img width="574" alt="Screen Shot 2023-03-07 at 8 46 40 PM" src="https://user-images.githubusercontent.com/4947998/223426512-6e4e70d1-56a3-496e-bda4-2222ecd01026.png">

Expected result

```kotlin
{
  "errors": [
    {
      "message": "A user name should be at-least 5 characters",
      "locations": [],
      "path": [
        "login"
      ]
    }
  ]
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by dariuszkuc** [comment]
Hello 👋 
I've updated default `GraphQLRequestParser` to directly used `receive` vs `receiveText` so above should be possible (using Jackson) once https://github.com/ExpediaGroup/graphql-kotlin/pull/1704 is merged. 

That being said due to 
* duplicate serialization (i.e. data fetchers will still work with raw map objects)
* handling of custom scalars coercing rules 
* and also possibly on how to handle null vs omitted values

I am unsure whether doing the above is a good idea. GraphQL "native" way would be to probably use [custom directives on  arguments](https://opensource.expediagroup.com/graphql-kotlin/docs/schema-generator/customizing-schemas/directives/#custom-directives). You could also try to apply `javax.validation` rules on functions directly.

**Comment by ronjunevaldoz** [comment]
Found this at [graphql-validation-using-directives](https://www.apollographql.com/blog/backend/validation/graphql-validation-using-directives/), in the below input how do I support this kind of directive?

```kotlin
type SignUpInput {
  email: String! @constraint(format: "email", maxLength: 255)
  password: String! @constraint(maxLength: 255)
  firstName: String! @constraint(pattern: "^[0-9a-zA-Z]*$", maxLength: 255)
  lastName: String! @constraint(pattern: "^[0-9a-zA-Z]*$", maxLength: 255)
}
```

**Comment by dariuszkuc** [comment]
As I wrote above you would have to implement `@constraint` as [custom directive](https://opensource.expediagroup.com/graphql-kotlin/docs/schema-generator/customizing-schemas/directives/#custom-directives).

**Comment by ronjunevaldoz** [comment]
> As I wrote above you would have to implement `@constraint` as [custom directive](https://opensource.expediagroup.com/graphql-kotlin/docs/schema-generator/customizing-schemas/directives/#custom-directives).

Hi @dariuszkuc will experiment with that for now.

**Comment by dariuszkuc** [comment]
> Hello 👋 I've updated default `GraphQLRequestParser` to directly used `receive` vs `receiveText` so above should be possible (using Jackson) once #1704 is merged.
> 
> That being said due to
> 
> * duplicate serialization (i.e. data fetchers will still work with raw map objects)
> * handling of custom scalars coercing rules
> * and also possibly on how to handle null vs omitted values
> 
> I am unsure whether doing the above is a good idea. GraphQL "native" way would be to probably use [custom directives on arguments](https://opensource.expediagroup.com/graphql-kotlin/docs/schema-generator/customizing-schemas/directives/#custom-directives). You could also try to apply `javax.validation` rules on functions directly.

As per my comment above we will not be adding explicit support for this.
