### ISSUE TITLE
Unable to add GraphQL Ktor Server to project

### ISSUE THREAD

**Issue by adi9090** [ExpediaGroup/graphql-kotlin#1738]
Hi,

I'm trying to add dependency to GraphQL Ktor server to my project and I'm not able to. I've used 6.4.0 version and I'm receiving next error: `Could not find com.expediagroup:graphql-kotlin-ktor-server:6.4.0.`

I've looked on Maven Repository and there I can not find ktor server: https://mvnrepository.com/artifact/com.expediagroup

```
    implementation("com.expediagroup:graphql-kotlin-server:6.4.0")
    implementation("com.expediagroup:graphql-kotlin-ktor-server:6.4.0")
```

**Comment by dariuszkuc** [comment]
Hello 👋 
`graphql-kotlin-ktor-server` was added to v7 (still wip). While we are still finalizing v7 release, pre-release versions are available -> https://central.sonatype.com/artifact/com.expediagroup/graphql-kotlin-ktor-server/7.0.0-alpha.4
