### ISSUE TITLE
[7.x.x] FederatedTypeSuspendResolverExecutor is not starting futures immediately, hangs application

### ISSUE THREAD

**Issue by roookeee** [ExpediaGroup/graphql-kotlin#1746]
**Library Version**
7.0.0-alpha4

**Describe the bug**
`FederatedTypeSuspendResolverExecutor` is using a `.future {}` call in `execute` to start (**not await!**) the futures for entity requests. The framework expects that all futures are started when `execute` has returned as the DataLoaders are dispatched immediately afterwards. The `.future{}` call defers said starting / queuing which may lead to a DataLoader.dispatch() before the futures are queued.

This leads to hangs as the DataLoaders are never dispatched after they have been requested to load data.

`FederatedTypePromiseResolverExecutor` does not introduce such issues as its current implementation guarantees that all futures have been started / queued after its `execute` function returns.

EDIT / Additional info: ~~Maybe this onlys occur when the CouroutineContext contains more than 1 thread, which is the case for us.~~ Rechecked locally, using only 1 thread doesn't make a difference.

**To Reproduce**
Use a `FederatedTypeSuspendResolverExecutor`

**Expected behavior**
The futures of all requested entities have to be started when `execute` returns. Alternatively make sure that dispatch on all DataLoaders is only called after all futures are queued.

**Comment by samuelAndalon** [comment]
`FederatedTypePromiseResolver` was added to solve this issue
https://github.com/ExpediaGroup/graphql-kotlin/issues/1506

i believe this specific issue if a duplicated of ^

**Comment by roookeee** [comment]
Well there is [another issue](https://github.com/ExpediaGroup/graphql-kotlin/issues/1747) with the `FederatedTypePromiseResolver` which makes it unusable at the moment as we can't properly propagate errors.

Nevertheless it strikes me as odd that `DataLoaders` and `suspend` functions are at the core of GraphQL + Kotlin yet we have to dip into `CompleteableFuture` in a federated type resolver :/ Why offer the suspend variant if it isn't usable with an integral part of GraphQL, `DataLoader` ? 

We even added a thin `DataLoader` wrapper that is based on Kotlin coroutines to "stay in Kotlin" land and never have to touch `CompleteableFuture` again :)

I might dip my feet into the water here, the issue is quite annoying to solve but it would be super useful for other people. Let me know if you aren't interested in a fix for this but I really want this to work, there are lots of pitfalls with `CompleteableFuture` and nesting them while propagating thread locals for tracing etc. which are just not present for coroutines once you have configured them properly.

Let me know if you aren't interested in a fix for this, will give it a shot tomorrow elsewise.

Thank you for your work!

**Comment by samuelAndalon** [comment]
>Well there is https://github.com/ExpediaGroup/graphql-kotlin/issues/1747 with the FederatedTypePromiseResolver which makes it unusable at the moment as we can't properly propagate errors.

lets discuss about that issue not in this issue.

> Nevertheless it strikes me as odd that DataLoaders and suspend functions are at the core of GraphQL + Kotlin yet we have to dip into CompleteableFuture in a federated type resolver :/ Why offer the suspend variant if it isn't usable with an integral part of GraphQL, DataLoader ?

As of now, the graphql-java execution engine only understands `CompletableFuture` for asynchronous resolvers/data fetchers, and as far as i know there is no intention to extend it to coroutines, reactive streams, etc, The intention behind that is to have the execution engine written in pure jvm capabilities.

>Why offer the suspend variant if it isn't usable with an integral part of GraphQL, DataLoader ?

the intention to support suspending functions is to allow syntactic sugar when writing functions executed by resolvers, but at the end graphql-kotlin executed the graphql-java engine so we need to interop.

DataLoaders were not specificaly created for GraphQL.

We added the `FederatedTypeSuspendResolver` with the intention to keep supporting syntactic sugar with coroutines, and `FederatedTypePromiseResolver` with the intention to support the special use case that the n+1 problem causes in GraphQL.

**Comment by samuelAndalon** [comment]
>Let me know if you aren't interested in a fix for this, will give it a shot tomorrow elsewise.

we are interested on fixing if thats why we create `FederatedTypePromiseResolver`, thanks, feel free to create a PR if you find a solution to use dataloaders with suspendable function, would be really interested on taking a look at it.

**Comment by roookeee** [comment]
> > Well there is #1747 with the FederatedTypePromiseResolver which makes it unusable at the moment as we can't properly propagate errors.
> 
> lets discuss about that issue not in this issue.
> 

Sure!

> > Nevertheless it strikes me as odd that DataLoaders and suspend functions are at the core of GraphQL + Kotlin yet we have to dip into CompleteableFuture in a federated type resolver :/ Why offer the suspend variant if it isn't usable with an integral part of GraphQL, DataLoader ?
> 
> As of now, the graphql-java execution engine only understands `CompletableFuture` for asynchronous resolvers/data fetchers, and as far as i know there is no intention to extend it to coroutines, reactive streams, etc, The intention behind that is to have the execution engine written in pure jvm capabilities.
> 

I am aware of this but seeing that there is other "glue" done in graphql-kotlin to support coroutines it's still surprising. But this particular location is hard to "glue" properly, I get that just by looking at the circumstances for a couple moments :)

> > Why offer the suspend variant if it isn't usable with an integral part of GraphQL, DataLoader ?
> 
> the intention to support suspending functions is to allow syntactic sugar when writing functions executed by resolvers, but at the end graphql-kotlin executed the graphql-java engine so we need to interop.
> 
> DataLoaders were not specificaly created for GraphQL.
> We added the `FederatedTypeSuspendResolver` with the intention to keep supporting syntactic sugar with coroutines, and `FederatedTypePromiseResolver` with the intention to support the special use case that the n+1 problem causes in GraphQL.

I get the sentiment but in [another discussion](https://github.com/ExpediaGroup/graphql-kotlin/issues/1563#issuecomment-1270452093) it was explicitly pointed out that we "MUST" use `DataLoader` in the future aka starting with 7.x.x. But we can't in `FederatedTypeSuspendResolver`, this just doesn't match.
And of course I am aware that `DataLoader` was not specifically created for GraphQL, it's just one of the core / idiomatic concepts that make it easy to implement in a performant way, as has been suggested by graphql-kotlin in the past.

> we are interested on fixing if, thats why we create FederatedTypePromiseResolver, thanks, feel free to create a PR if you find a solution to use dataloaders with suspendable functions, would be really interested on taking a look at it.

Will give it a shot, thanks

**Comment by samuelAndalon** [comment]
please have a look at this 
https://opensource.expediagroup.com/graphql-kotlin/docs/server/data-loader/#dataloaders-and-coroutines

there we highlight that you can still use and leverage coroutines to execute your domain code, the only thing you need to do is to make sure to return a completableFuture from the resolver of the type you want to leverage dataloaders, that way the dispatch mechanism will know when is time to dispatch, and when dispatches, you can access to the coroutine scope located in the graphqlContext to execute your coroutines.

same applies for entities resolvers, thats why, we added the `FederatedTypePromiseResolver`.

**Comment by roookeee** [comment]
Will take a look at this after my vacation but as far as I understand the automatic dispatching of dataloaders only works correctly when the returned future is initially created by the dataloader load call as that queues the batch lookup item. But this is just off the top of my head, will double check later.

Thanks!
