### ISSUE TITLE
accessing graphql query in method

### ISSUE THREAD

**Issue by donhill** [ExpediaGroup/graphql-kotlin#1748]
I have an endpoint defined which takes a userId and returns 3 predicates, indicating what system a user has datain. 
In some situations, the query will only include 2 of the predicates in the request. 
How would I go about accessing the request so that I only call the 2 systems and not all 3 that are exposed by the endpoint?

**Comment by samuelAndalon** [comment]
Hello  👋 , can you please be more specific ? probably a code example of how your code and your query looks like ?

it feels that you can achieve this using arguments in your queries, which are available in your resolvers, query is a string :), so even if you have access to it (you do), you would need to parse the query into a AST (which is available as well), you should not worry about that an use graphQL in the way graphQL is supposed to be used, using arguments.

**Comment by donhill** [comment]
Maybe it my misunderstanding of graphql. let me try and provide some details.

I have the following query, which makes calls to each System.
` systemWithRecords (
        userId: $userId
    ) {
        hasSyatemA
        hasSystemB
        hasSystemC
    }`

in some cases I don't care about the other systems, the client will send this query
` systemWithRecords (
        userId: $userId
    ) {
        hasSyatemA
    }`

In the second case, I want to know, based on the payload, which systems I would need to call. In the first case, I would call all systems.

I understand I can use params, but I was looking for a way to read the body and determine which systems need to be called based on graphql query that is sent in.

Any thoughts?

**Comment by samuelAndalon** [comment]
you can inject the [DataFetchingEnvironment](https://opensource.expediagroup.com/graphql-kotlin/docs/schema-generator/execution/data-fetching-environment/) in your systemWithRecords function 

```
class MyQuery : Query {
  fun systemWithRecords(userId: ID, dataFetchingEnvironment: DataFetchingEnvironment): SystemWithRecords {
   datafetchingEnvironment.selectionSet.fields
   // do something
  }
}
```

the `selectionSet` will give you access to the selectedFields of the current field, in this case `systemWithRecords`.
