### ISSUE TITLE
GraphiQL subscriptions URL is forced to relative URL

### ISSUE THREAD

**Issue by jaaqo** [ExpediaGroup/graphql-kotlin#1754]
**Library Version**
7.0.0-alpha.5

**Describe the bug**
GraphiQL subscriptions URL is relative, when absolute is expected.

Trace:
https://github.com/graphql/graphiql/blob/main/packages/graphiql-toolkit/src/create-fetcher/createFetcher.ts#L56
https://github.com/graphql/graphiql/blob/main/packages/graphiql-toolkit/src/create-fetcher/lib.ts#L82
https://github.com/enisdenjo/graphql-ws/blob/master/src/client.ts#L519
https://github.com/whatwg/websockets/issues/20

**To Reproduce**
https://github.com/ExpediaGroup/graphql-kotlin/blob/master/servers/graphql-kotlin-server/src/main/resources/graphql-graphiql.html#L48

**Expected behavior**
Use current `window.location.href` to construct absolute url by default.

**Working solution**
```javascript
const subscriptionUrl = new URL("/${subscriptionsEndpoint}", location.href);
subscriptionUrl.protocol = location.protocol === "https:" ? "wss" : "ws";
```

**Comment by samuelAndalon** [comment]
Hello 👋🏼, feel free to open a PR, should be a pretty straightforward change.
