### ISSUE TITLE
With CustomSchemaGeneratorHooks no whole interfaces can be ignored

### ISSUE THREAD

**Issue by StartedFromTheButton** [ExpediaGroup/graphql-kotlin#1799]
I'm trying to create a CustomSchemaGeneratorHooks to ignore an interface since it's not possible to annotate interfaces from libraries with @GraphQLIgnore.

I'm using 
```
override fun isValidSuperclass(kClass: KClass<*>): Boolean {
  return kClass != KoinComponent::class
}
```

This ignores the interface itself but it doesn't ignore the public methods inside.

Is this the expected behavior?

**Comment by dariuszkuc** [comment]
Hello 👋 
Yes this is the intended behavior. While there are use cases where users may want to ignore all the superclass functions, there are other use cases where users may want to keep those functions in their schema.

Excluding those fields is easy, i.e. they can be excluded by either annotating them with `@GraphQLIgnore` or more generically through [_isValidFunction_ hook](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/hooks/SchemaGeneratorHooks.kt#L109). Doing the opposite, i.e. excluding them by default and allowing users to do the explicit opt-in would be much harder to support.
