### ISSUE TITLE
Sub directory for queries folder client maven plugin

### ISSUE THREAD

**Issue by robp94** [ExpediaGroup/graphql-kotlin#1807]
### Discussed in https://github.com/ExpediaGroup/graphql-kotlin/discussions/1806

<div type='discussions-op-text'>

<sup>Originally posted by **robp94** June 29, 2023</sup>
Is it possible to have subdirectories in the queries folder for the client generator?

Currently, we use this as config `<queryFileDirectory>${project.basedir}/src/main/resources/clients/graphql/queries</queryFileDirectory>`

If the queries are in exactly this folder it is working, if we add a new folder inside the queries folder they are ignored.</div>

**Comment by dariuszkuc** [comment]
Support added in #1809
