### ISSUE TITLE
Support Map<K, V> as input argument type 

### ISSUE THREAD

**Issue by andreyTheGreatest** [ExpediaGroup/graphql-kotlin#1808]
**Is your feature request related to a problem? Please describe.**
I have an input argument of Map<K, V> type for a subscription request. I map it to `ExtendedScalars.JSON` to avoid `TypeNotSupportedException`, however with a 6.x version of generator package I am getting `PrimaryConstructorNotFound: Invalid input object Map - missing public primary constructor`. 
I have noticed related discussions about this problem in #1518 and #1520. But they suggest to create either a constructor, because of predefined POJO java classes usage, or a custom `FunctionDataFetcher `. Any Map implementation doesn't provide one constructor only, and creating custom support of a simple Map via `FunctionDataFetcher ` seems like an overkill to me. 

**Describe the solution you'd like**
I'd suggest Map support is as crucial as List support as an input argument. As far as I am concerned, List doesn't generate `PrimaryConstructorNotFound`, so maybe a similar behavior could be provided for the Map as well.

**Comment by smyrick** [comment]
Maps are not supported per the GraphQL spec, however you should be able to use `ExtendedScalars.JSON` by setting up your schema generator hooks to include the Map type as a valid type, map that to JSON and include extended scalars in your package config

https://github.com/ExpediaGroup/graphql-kotlin/discussions/1198

**Comment by andreyTheGreatest** [comment]
Thanks for the answer!
I have it already set up, as suggested. 
```
fun schemaGeneratorHooks() = object : SchemaGeneratorHooks {
    override fun willGenerateGraphQLType(type: KType): GraphQLType?  = when (type.classifier) {
        Map::class -> ExtendedScalars.Json
        else -> null
    }
}

graphqlSchema = toSchema(
    config = SchemaGeneratorConfig(
    supportedPackages = listOf("graphql.scalars.ExtendedScalars", ...),
        hooks = schemaGeneratorHooks(),
    ),
    ...
)
```

It works flawlessly with Map as an output type. The problem emerges, when I am using Map as an input type. The exception that is thrown: `PrimaryConstructorNotFound: Invalid input object Map - missing public primary constructor`. I have tried swapping Map with HashMap or LinkedHashMap, however, these implementations include multiple constructors, thus `MultipleConstructorsFound` is thrown. This suggests implementing Map with one constructor. 

When I downgrade to 5.x version, input Map type works as well. From my understanding, this is due to drop of Jackson support mentioned [here](https://github.com/ExpediaGroup/graphql-kotlin/pull/1520#issuecomment-1218403159). Although, the Map isn't supported per GraphQL spec, with the previous version of this lib everything worked as expected, whereas with the new one I have to provide custom `FunctionDataFetcher` or create a custom implementation of Map. I understand why it is so for the POJO classes, but Map is widely used.

If this is the expected behavior, however, and my arguments don't suffice, then I will opt out of my take and apply one of the previously mentioned approaches (it just doesn't feel right to write custom Map implementation just for the sake of providing single constructor only ;) ).

**Comment by smyrick** [comment]
Tagging the maintainer for visibility, @samuelAndalon and @tapaderster

**Comment by samuelAndalon** [comment]
@andreyTheGreatest could you share a repo link with minimal setup to reproduce the error ? -- you can use spring boot starter and include graphql-kotlin-server.

**Comment by dariuszkuc** [comment]
IMHO this issue should be closed in favor of https://github.com/ExpediaGroup/graphql-kotlin/issues/1445 which tackles this more generically. TLDR we should provide a mechanism for easily supporting additional input types - right now they have to write their own data fetcher that duplicates the default logic.

**Comment by dariuszkuc** [comment]
We will not be supporting generic `Map<K, V>` as input arguments (as GraphQL specification does not support maps). Closing this in favor of providing mechanism to easily modify the default data fetchers to include custom logic (see #1445).
