### ISSUE TITLE
Scalar Upload is converted as String

### ISSUE THREAD

**Issue by rajeshomprakash** [ExpediaGroup/graphql-kotlin#1821]
i want to test file upload, the graphql client converts the schema to kotlin data class files but i observe Scalar type Upload is mapped with String.

We write test scripts in kotlin to test mutations . How should be the request be constructed to test file upload
<img width="961" alt="Screenshot 2023-08-12 at 5 44 37 PM" src="https://github.com/ExpediaGroup/graphql-kotlin/assets/33834085/014bf534-5449-4898-8e8e-579a0eb26602">
<img width="881" alt="Screenshot 2023-08-12 at 5 45 03 PM" src="https://github.com/ExpediaGroup/graphql-kotlin/assets/33834085/282cbba7-cd6b-4275-a86f-f6eac6a15881">

**Comment by dariuszkuc** [comment]
[`Upload` is a custom scalar so by default it is typealiased to String, you can register custom converters to bind it to other types](https://opensource.expediagroup.com/graphql-kotlin/docs/client/client-features#custom-scalar-support).

---
In general I'd advise against using a base64 "hack" to upload files through GraphQL. IMHO much better and scalable solution is to have a mutation that returns you presigned urls to a native solution (e.g. AWS, GCloud, etc).
