### ISSUE TITLE
graphql-response+json content type is the default

### ISSUE THREAD

**Issue by gumimin** [ExpediaGroup/graphql-kotlin#1831]
**Library Version**
[7.0.0-alpha.5](https://github.com/ExpediaGroup/graphql-kotlin/releases/tag/7.0.0-alpha.5)

**Describe the bug**
I implemented this PR: https://github.com/ExpediaGroup/graphql-kotlin/pull/1699, Issue: https://github.com/ExpediaGroup/graphql-kotlin/issues/1573

I fixed this according to following review comment.
https://github.com/ExpediaGroup/graphql-kotlin/pull/1699#discussion_r1127131395

However, the `*/*` was not taken into account and the change was not sufficient.
Most clients will request with `*/*` unless an any MediaType is specified, so this needs to be fixed.

**To Reproduce**
When a request is send without accept header, the response content type is returned as `application/graphql-response+json`

**Expected behavior**
I want to keep `application/json` as default instead of `application/graphql-response+json`
https://github.com/ExpediaGroup/graphql-kotlin/pull/1699#discussion_r1127131395

**Comment by dariuszkuc** [comment]
Fixed in #1832
