### ISSUE TITLE
Error on mutation with JSON: Could not get the type of the first argument for the type com.fasterxml.jackson.databind.node.ObjectNode

### ISSUE THREAD

**Issue by flinden68** [ExpediaGroup/graphql-kotlin#1841]
We upgraded from graphql-kotlin 5.5.0 to 7.0.0-alpha.6 along with the upgrade from Spring boot 2.7.12 to 3.1.3.

We have a mutation query:
```graphql
{
  "query": "mutation ($submission: JSON!, $caseDefinitionId: String!) {\n  processSubmission(submission: $submission, caseDefinitionId: $caseDefinitionId) {\n    caseId\n    __typename\n  }\n}\n",
  "variables": {
    "caseDefinitionId": "bezwaar",
    "submission": {
      "voornaam": "Bob"
    }
  }
}
```

In the application the query method:
```kotlin
    @GraphQLDescription("Convert submission to json return resulting data")
    fun processSubmission(
        submission: ObjectNode,
        caseDefinitionId: String,
        initialStatus: String? = null,
        dfe: DataFetchingEnvironment
    ): CaseCreated {
        val case = caseService.create(
            caseDefinitionId,
            submission,
            dfe.graphQlContext.get(AUTHENTICATION_KEY),
            initialStatus
        )
        return CaseCreated(case.caseId.value)
    }
```

which went well in the 'old' situation, but after upgrade we received an error

```json
{
    "errors": [
        {
            "message": "Exception while fetching data (/processSubmission) : Could not get the type of the first argument for the type com.fasterxml.jackson.databind.node.ObjectNode",
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "path": [
                "processSubmission"
            ]
        }
    ]
}
```

What do we do wrong?? Or is it a known issue. More important how to fix it?

**Comment by dariuszkuc** [comment]
Hello 👋 
In v6 we dropped dependency on Jackson when deserializing arguments (see [release notes](https://github.com/ExpediaGroup/graphql-kotlin/releases/tag/6.0.0)) to avoid double deserialization issue.

Using custom scalars (ie generic `ObjectNode`) requires A) custom schema generator hook logic and B) resolver that understands this custom scalar so it can map inputs accordingly.

Sadly currently there is no easy way to provide your custom logic to the resolver (see https://github.com/ExpediaGroup/graphql-kotlin/issues/1445) so you would need to copy existing [resolver logic](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/FunctionDataFetcher.kt) (or more specific [Spring aware one](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/execution/SpringDataFetcher.kt)) and add your custom logic there.
