### ISSUE TITLE
Make the federation v2 version configurable, federation v2.5 is still experimental

### ISSUE THREAD

**Issue by roookeee** [ExpediaGroup/graphql-kotlin#1851]
**Is your feature request related to a problem? Please describe.**
We upgraded to graphql-kotlin 7.0 which forces federation `v2.5` which is currently still marked experimental in Apollo Studio and thus not usable for us in production:
![image](https://github.com/ExpediaGroup/graphql-kotlin/assets/1199562/7202b358-3ef2-4620-8370-e06993c8baa0)
We cannot migrate to Spring Boot 3 or graphql-kotlin 7.x while this problem persists, there is no ETA when federation 2.5 will be non-experimental

**Describe the solution you'd like**
Allow us to configure the federation version to include in the auto-generated `@link` directive.

**Describe alternatives you've considered**
Downgrading to graphql-kotlin 6.x or generating the customized `@link` directive ourselves, both are error prone or block us from using Spring Boot 3.x.

**Additional information**
Rover error:
![image](https://github.com/ExpediaGroup/graphql-kotlin/assets/1199562/b6bfd7ea-3a7a-41da-914e-e578f727e095)

**Comment by dariuszkuc** [comment]
There is no loss of functionality.

> can you elaborate the reasoning behind forcing an experimental version like this ?

I believe the only experimental/preview feature of Federation v2.5 are the [new auth features of the router](https://www.apollographql.com/docs/router/configuration/authn-jwt/). Query planner/composition logic is stable and federation v2.5.5 is the latest available version.

>why not allow us to downgrade to a prior minor version?

You can downgrade (or even upgrade in the future) by applying custom `@link` directive.

When generating federated schemas, we auto apply `@link` directive with all federation imports (ones used in the schema and up to version 2.3) so there is no renaming/namespacing of the elements. When you apply custom `@link` directive you explicitly import elements and non-imported elements get namespaced to the imported spec.

While generated SDL might be different (e.g. if you use `@key` directive in your schema but explicitly don't import it, it will be renamed to `@federation__key`), from composition perspective both schemas will be semantically the same.

**Comment by dariuszkuc** [comment]
To close the loop -> Apollo Federation v2.5 is now GA (no longer experimental) in studio

**Comment by roookeee** [comment]
While we are still waiting for our production Apollo Federation to update to 2.5, I wanted to list issues other people might run into:

1. We are running into a gradle build error when prefixing `url` in `@LinkDirective` with `https://` on windows only, CI (Linux) builds without issues. Thus our workaround is not mergeable:
```kotlin

@Component
@LinkDirective(
    url = "https://specs.apollo.dev/federation/v2.4",
    `as` = "federation",
    import = [
        LinkImport("@key"),
        LinkImport("FieldSet")
    ]
)
class FederatedSchema : Schema
```
Error:
![image](https://github.com/ExpediaGroup/graphql-kotlin/assets/1199562/ed820e9e-cce7-475e-9ddc-4d5939c2b48e)

2. We have to disable `kapt` (which we need for some Spring Boot stuff) as the `@LinkDirective` uses `import` as a field name which is a reserved keyword in Java. As `kapt` generates compatibility annotation Java files, this breaks compilation. We don't want to lose `kapt` and thus our workaround is not mergeable

=> We will have to wait for our prod env to update to 2.5 which might take some time.
