### ISSUE TITLE
I got error "This is not implemented by this Scalar class ~~.LinkImportCoercing" when I ran graphqlGenerateSDL

### ISSUE THREAD

**Issue by uryyyyyyy** [ExpediaGroup/graphql-kotlin#1852]
**Library Version**
v7.0.0

**Describe the bug**
when I ran graphqlGenerateSDL task from my gradle project with the gradle plugin, I got this error

```
Execution failed for task ':application:graphqlGenerateSDL'.
> There was a failure while executing work items
   > A failure occurred while executing com.expediagroup.graphql.plugin.gradle.actions.GenerateSDLAction
      > This is not implemented by this Scalar class com.expediagroup.graphql.generator.federation.types.LinkImportCoercing
```

**To Reproduce**
sorry, it's my work project, will prepare some example later, but maybe need federation.

**Expected behavior**
support this customTypes, and generate valid graphql schema.

**Comment by dariuszkuc** [comment]
Hello 👋 
Without a repository with reproduction it is hard to say whats happening. `LinkImportCoercing` is used for "coercing" aka serializing/deserializing `Import` scalar used by `@link` directive. If you are trying to generated federated SDL did you include [federated hooks provider](https://opensource.expediagroup.com/graphql-kotlin/docs/plugins/hooks-provider#federated-hooks-provider)?

**Comment by uryyyyyyy** [comment]
@dariuszkuc 
thank you for the comment!
I tested with federation example codes on graphql-kotlin repo. and it looks when I set this dependencies, it'll fail.
let me prepare minimum code example later.

```
plugins {
    id("io.spring.dependency-management") version "1.0.11.RELEASE"
    ...
}
```

**Comment by uryyyyyyy** [comment]
Sorry, as far as I checked, this was because I used it with spring boot 3.0.
When I use 3.1, it's working very nicely.
Sorry for this issue and thank you for developing great library.
