### ISSUE TITLE
Build-in graphiql service do not support save headers between refresh page

### ISSUE THREAD

**Issue by JajaComp** [ExpediaGroup/graphql-kotlin#1854]
Graphql kotlin version: 7.0.0

Build-in graphiql service do not support save headers between refresh page: https://github.com/graphql/graphiql/issues/1596
In new version this issue fixed

**Comment by JajaComp** [comment]
Unfortunately, I don’t know where or how to get the new version 3.0.6 of graphiql in html form

**Comment by samuelAndalon** [comment]
>Unfortunately, I don’t know where or how to get the new version 3.0.6 of graphiql in html form.

a 5 min search in graphiql should be enough, no problem, preparing a PR.

**Comment by dariuszkuc** [comment]
GraphiQL version was updated in #1855
