### ISSUE TITLE
Website ktor Subscriptions wrong url

### ISSUE THREAD

**Issue by charlee-dev** [ExpediaGroup/graphql-kotlin#1863]
On the [Server/Subscriptions page](https://opensource.expediagroup.com/graphql-kotlin/docs/server/server-subscriptions) link to the ktor subscriptions documentation takes us to the Spring Subscriptions documentation instead of Ktor one.

Link:
![CleanShot 2023-10-08 at 23 51 24](https://github.com/ExpediaGroup/graphql-kotlin/assets/20965327/90d2ed62-0563-4485-8304-7a68fd17738f)

Goes here:
![CleanShot 2023-10-08 at 23 53 31](https://github.com/ExpediaGroup/graphql-kotlin/assets/20965327/3bc25974-8da7-41bf-966b-a793b7105826)

But it should go here:
![CleanShot 2023-10-08 at 23 53 56](https://github.com/ExpediaGroup/graphql-kotlin/assets/20965327/164181ef-d434-481a-831a-5fb5c69437a5)

**Comment by dariuszkuc** [comment]
Contributions are always welcome :) Feel free to open up PR with a fix.

**Comment by dariuszkuc** [comment]
resolved in #1865
