### ISSUE TITLE
Add support for `kotlin.Array`

### ISSUE THREAD

**Issue by BierDav** [ExpediaGroup/graphql-kotlin#1888]
**Is your feature request related to a problem? Please describe.**
When you try to create a graphql query that returns `kotlin.Array` you get an error message like this: 

> Cannot convert kotlin.Array<kotlin.Int> since it is not a valid GraphQL type or outside the supported packages "[]"

**Describe the solution you'd like**
Out of the box support for this return type like for example list

**Describe alternatives you've considered**
None really. A workaround would be to use `toList()` and return a list

**Comment by samuelAndalon** [comment]
https://opensource.expediagroup.com/graphql-kotlin/docs/schema-generator/writing-schemas/lists/#arrays-and-unsupported-collection-types
