### ISSUE TITLE
Coroutine scope null

### ISSUE THREAD

**Issue by ghn1712** [ExpediaGroup/graphql-kotlin#1892]
Hey all! I recently migrated a project using graphql-kotlin from Spring Boot 2 to Spring Boot 3 and after migrating from version 6.x to 7.x the coroutine scope in dataloaders was always empty, without any code change related to it. I checked the docs and in the project I was doing as suggested in the [docs](https://opensource.expediagroup.com/graphql-kotlin/docs/server/data-loader/#example): 

```kotlin
    override fun getDataLoader(graphQLContext: GraphQLContext) = 
        DataLoaderFactory.newDataLoader<Int, User>(
            { ids, batchLoaderEnvironment ->
                val coroutineScope = 
                    batchLoaderEnvironment.getContext<GraphQLContext>()?.get<CoroutineScope>()
                        ?: CoroutineScope(EmptyCoroutineContext) 

                coroutineScope.future { 
                    userService.getUsers(ids)
                }
            },
            DataLoaderOptions.newOptions()
                .setBatchLoaderContextProvider { graphQLContext }
```

The only difference I had was not using `DataLoaderFactory.newDataloader` but `DataLoaderFactory.newMappedDataloader` function and I believe for this issue it shouldn't make a difference. The way I was able to fix it was using the new `graphQLContext` parameter to get the scope instead of the `batchLoaderEnvironment` variable, like:

```kotlin
        DataLoaderFactory.newMappedDataLoader { ids, batchLoaderEnvironment ->
            /* before where context was always empty
            val coroutineScope = batchLoaderEnvironment.getContext<GraphQLContext>()?.get<CoroutineScope>()
                        ?: CoroutineScope(EmptyCoroutineContext)
           */

            //after
            val coroutineScope = graphQLContext.getOrThrow<CoroutineScope>()
```

I would like to check if that's an issue on my side or if the docs should be updated and use the new parameter to get the context. Also do the contexts differ in any way or should they have the same content? Thanks!

**Comment by dariuszkuc** [comment]
Hello 👋 
Are you passing the `DataLoaderOptions` to your `newMappedDataLoader` function? Either way should work, I just tried it and it seem to work fine. If you are still having issue, please provide a link to Github repository that reproduces the issue.

**Comment by ghn1712** [comment]
@dariuszkuc thanks for the quick reply! No, I wasn't using this new `DataLoaderOptions` (at least in version 6.x docs it was not there). Is it mandatory in version 7.x if you want to access the context via `batchLoaderEnvironment`? Using the `graphQLContext` parameter it works just fine without it.

**Comment by dariuszkuc** [comment]
Yes, in order to specify context for the data loader you need to use `DataLoaderOptions`.

In the example above, the `BatchLoaderContextProvider` is just returning the provided `GraphQLContext` so the result is the same as if accessing it directly from the parameter. That being said, `BatchLoaderContextProvider` can be used to provide some additional context elements there. 

While it works without it, since `BatchLoaderContextProvide`r is the built-in data loader mechanism to provide access to context, I'd personally use that mechanism.
