### ISSUE TITLE
Change @GraphQLID to only work on strings

### ISSUE THREAD

**Issue by smyrick** [ExpediaGroup/graphql-kotlin#317]
**Library Version**
1.0.0-RC5

**Describe the issue**
Our current implementation allows for multiple types to be a `ID`:
* `String`, `Int`, `Long` or `UUID`

https://github.com/ExpediaDotCom/graphql-kotlin/wiki/Scalars#id

**Expected behavior**
According the to GraphQL spec the `ID` scalar should always serialize to a String

https://graphql.github.io/graphql-spec/June2018/#sec-ID

Do we need to change this behaviour?

**Comment by dkuc84** [comment]
Our current behavior is based on `graphql-java` implementation which supports implicit conversions from `String`, `Int`, `Long`, `UUID` or `BigInteger` ([link](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/Scalars.java#L266)). As per the spec it will always serialize as a String.

If we update our logic to only support `String` then I believe it will make it much easier to resolve https://github.com/ExpediaDotCom/graphql-kotlin/issues/249 (otherwise deserialization part might be tricky).

**Comment by smyrick** [comment]
@dkuc84 I resolved #249 here: https://github.com/ExpediaDotCom/graphql-kotlin/pull/319

So I think since `graphql-java` is doing the conversion of those types back to Strings we are still spec compliant, and it does make it easier to use types like `UUID`. 

I am going to close this then as discussion is not needed

**Comment by dkuc84** [comment]
I'm actually leaning towards explicitly supporting only Strings - given an `ID` argument client has no idea whether it should be `Int`, `UUID` or whatever. If they specify data in wrong format (e.g. trying to pass `Int` when we expect `UUID`) it will cause runtime exceptions. It will be safer if we explicitly support only `String` and let the devs decide whether they need to validate it.

**Comment by smyrick** [comment]
If we only had to support strings we could create a new simple class `ID` which can be used instead to be more explicit in the Kotlin code about the resulting schema which means we could remove this annotation

**Comment by smyrick** [comment]
Another option is instead of having the annotation we can have a more explicit type that is a wrapper of a type parameter, and then do the wrapped type checks as we normally do.

```kotlin
data class ID<T>(val value: T)
```

This would be a minor change though and not sure if it's worth the effort to go through
```kotlin
class User(val id: ID<UUID>, val name: String)

// vs

class User(@GraphQLID val id: UUID, val name: String)
```

**Comment by dkuc84** [comment]
Using a wrapper class still has a problem with using `GraphQLID` as an input type. Serialization will work either way.

From spec

> Input Coercion
> 
> When expected as an input type, any string (such as "4") or integer (such as 4) input value should be coerced to ID as appropriate for the ID formats a given GraphQL server expects. Any other input value, including float input values (such as 4.0), must raise a query error indicating an incorrect type.

Guess we can perform some validation to ensure we can coerce the value to expected type?

**Comment by smyrick** [comment]
Working on this

**Comment by smyrick** [comment]
Example error that can occur with input if an invalid UUID is given

![Screen Shot 2019-09-17 at 11 48 38 AM](https://user-images.githubusercontent.com/2446877/65070262-2518e180-d941-11e9-99a8-81969a75faf2.png)
