### ISSUE TITLE
Question about supportedPackages in SchemaGeneratorConfig

### ISSUE THREAD

**Issue by kptlronyttcna** [ExpediaGroup/graphql-kotlin#321]
I'm having issues understanding this parameter, what should I give it? Should it be the package name where I define my resolvers? Also why is it required? I wrote a hello world schema and it seems to work with an empty list.

**Comment by dkuc84** [comment]
Great question! We briefly explained it [here](https://github.com/ExpediaGroup/graphql-kotlin/wiki/Schema-Generator-Configuration) but I think the section should be expanded. `SchemaGeneratorConfig.supportedPackages` is a list of valid packages that can contain your GraphQL objects definitions. If your schema returns just scalars (e.g. String) then yes packages could be left empty as there are no custom types created. If your schema returns some custom objects then they have to be defined within specified packages. This is a safeguard to not accidentally try to expose some objects that are not supported by default by GraphQL spec (eg. Java date time, etc).

**Comment by kptlronyttcna** [comment]
Awesome, thanks.
