### ISSUE TITLE
validate subscription function return type when generating schema

### ISSUE THREAD

**Issue by dariuszkuc** [ExpediaGroup/graphql-kotlin#359]
**Is your feature request related to a problem? Please describe.**
Per [graphql-java docs](https://www.graphql-java.com/documentation/v13/subscriptions/) subscription data fetchers should return some `Publisher` (e.g. Reactor `Flux`). Currently we don't perform any validations to verify that functions specified for subscriptions return valid types.

**Describe the solution you'd like**
Schema generator should fail generation process if subscription function returns unsupported type.

**Describe alternatives you've considered**
N/A

**Additional context**
Related issue -> https://github.com/ExpediaGroup/graphql-kotlin/issues/358

**Comment by JithendraD** [comment]
@dariuszkuc Can I pick this issue to work for Hacktoberfest.

**Comment by smyrick** [comment]
Have a branch I am working on
