### ISSUE TITLE
Custom scalar with Federation

### ISSUE THREAD

**Issue by de55** [ExpediaGroup/graphql-kotlin#362]
**Library Version**
1.0.0-RC9

**Describe the bug**
Federation Schema generation throws error when scalar fields are included:

Caused by: graphql.AssertException: Must provide Input Type, cannot use: class graphql.schema.GraphQLInterfaceType

**To Reproduce**
Steps to reproduce the behavior. Please provide:
Attached a simple example.

To replicate the issue, just need to include a scalar on any Federation schema (make sure KeyDirective is actually used)

**Expected behavior**
Scalar should be included in the schema and not cause an error.
[graphql-kotlin-example.zip](https://github.com/ExpediaGroup/graphql-kotlin/files/3638661/graphql-kotlin-example.zip)

**Comment by de55** [comment]
Nevermind. Digging into this more, it is user error on my part. I was overriding the FederatedSchemaGeneratorHooks and that was making it so that FieldSet was not being created as a scalar.

For custom schema generator hooks, one will need to call super.willGenerateGraphQLType(type) if the type is not found to utilize the Federation Scalar types.

In my fork, I have created an example of using CustomSchemaGeneratorHooks under the the current federation example and can submit a pull request if helpful.

**Comment by smyrick** [comment]
@de55 Feel free to make a pull request in the examples to demo. I will close this issue
