### ISSUE TITLE
how to implement authentication scheme?

### ISSUE THREAD

**Issue by aarestu** [ExpediaGroup/graphql-kotlin#365]
How can I build something like this:

```
class HelloQuery: Query {

    @IsAuthenticated
    fun helloAuthenticatedUser(): String = "Hello Authenticated User"

    @IsAdmin
    fun helloAdmin(): String = "Hello Admin"
}
```

base on:
https://youtu.be/xaorvBjCE7A?t=580

**Comment by dariuszkuc** [comment]
This sort of logic in my opinion belongs to some directives, see: https://github.com/ExpediaGroup/graphql-kotlin/wiki/Directives for details. 

If you don't want to use directives then you could also create some utility service or extend some abstract class (you would have to exclude it from schema) and manually invoke appropriate methods. While certainly possible to do it this way, in my opinion it would be much cleaner if you were to use directives.

**Comment by dariuszkuc** [comment]
Related: https://github.com/ExpediaGroup/graphql-kotlin/issues/218 and https://github.com/ExpediaGroup/graphql-kotlin/issues/229

**Comment by aarestu** [comment]
@dariuszkuc 
I am confused. if I use federation it doesn't work well.
any solution? 
hmmm, maybe the way I write code is wrong.

https://github.com/aarestu/graphql-kotlin/blob/df98048fda09d919634bf95367a60ee82890011b/examples/federation-auth/accounts/src/main/kotlin/com/expediagroup/graphql/sample/accounts/query/MeQuery.kt#L29

**Comment by dariuszkuc** [comment]
Directives should work regardless whether you use federation model or not (in fact federation relies on directives).

It looks like you are trying to read GraphQL context? In order to use it you need to populate it - if using `graphql-kotlin-spring-server` you have to implement [GraphQLContextFactory](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/examples/spring/src/main/kotlin/com/expediagroup/graphql/sample/context/MyGraphQLContextFactory.kt#L12) bean. Then you will be able to access it from queries and directive wiring.

**Comment by aarestu** [comment]
@dariuszkuc I am sorry, my question makes you confused too.. (_my English grammar not good._)

actually, I already implement GraphQLContextFactory in another sub-module:
https://github.com/aarestu/graphql-kotlin/blob/df98048fda09d919634bf95367a60ee82890011b/examples/federation-auth/auth-package/src/main/kotlin/com/expediagroup/graphql/sample/auth/context/UserGraphQLContextFactory.kt

because that GraphQLContextFactory will be used in another microservice.. so I declarated in sepereted module.

and the errors does not come from the kotlin code.
but from the gateway:
https://github.com/aarestu/graphql-kotlin/tree/df98048fda09d919634bf95367a60ee82890011b/examples/federation-auth/gateway

```
.
.
.

Unknown directive "isAuthenticated".
    at ApolloGateway.createSchema (C:\Users\aarestu\IdeaProjects\graphql-kotlin\examples\federation-auth\gateway\node_modules\@apollo\gateway\dist\index.js:174:19)
    at ApolloGateway.<anonymous> (C:\Users\aarestu\IdeaProjects\graphql-kotlin\examples\federation-auth\gateway\node_modules\@apollo\gateway\dist\index.js:151:32)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\aarestu\IdeaProjects\graphql-kotlin\examples\federation-auth\gateway\node_modules\@apollo\gateway\dist\index.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
GraphQLSchemaValidationError: Unknown directive "isAuthenticated".

Unknown directive "isAuthenticated".
    at ApolloGateway.createSchema (C:\Users\aarestu\IdeaProjects\graphql-kotlin\examples\federation-auth\gateway\node_modules\@apollo\gateway\dist\index.js:174:19)
    at ApolloGateway.<anonymous> (C:\Users\aarestu\IdeaProjects\graphql-kotlin\examples\federation-auth\gateway\node_modules\@apollo\gateway\dist\index.js:151:32)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\aarestu\IdeaProjects\graphql-kotlin\examples\federation-auth\gateway\node_modules\@apollo\gateway\dist\index.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
GraphQLSchemaValidationError: Unknown directive "isAuthenticated".
```

**Comment by aarestu** [comment]
@dariuszkuc do have any solution for this kind of error?

**Comment by aarestu** [comment]
there is 3 kind of service I already Implement:
https://github.com/aarestu/graphql-kotlin/tree/example/federation-auth/examples/federation-auth

1. accounts
2. products
3. reviews

all of them run without any problem.
but if I run the gateway
https://github.com/aarestu/graphql-kotlin/tree/example/federation-auth/examples/federation-auth/gateway
I got error : `GraphQLSchemaValidationError: Unknown directive "isAuthenticated".`

**Comment by aarestu** [comment]
maybe the gateway not support custom directive.
how about this: 
if I make a custom directive and app is federation, I don't return schema custom directive to service, the custom directive will become something like middleware.
Is it possible??
how can I implement that?

**Comment by dariuszkuc** [comment]
Thanks for the clarification. It is indeed a current limitation of federated gateway. At the moment, federated schema can only contain federated directives.

Unfortunately, since we are relying on `graphql-java` to print out the SDL we cannot conditionally include/exclude which directives to include - it is either include all or exclude all.

**Comment by dariuszkuc** [comment]
I believe this issue belongs under Apollo Federation but created one for `graphql-kotlin` for tracking as well -> https://github.com/ExpediaGroup/graphql-kotlin/issues/373

**Comment by aarestu** [comment]
yeah I mean, probably it will be harder if apollo change the gateway/federation for support custom directives (_I don't know, I am not sure_)

**Comment by dariuszkuc** [comment]
@aarestu is this issue/question still valid?

**Comment by aarestu** [comment]
thanks @dariuszkuc 
I don't find a problem anymore to implement this now
