### ISSUE TITLE
federated schema cannot contain custom directives

### ISSUE THREAD

**Issue by dariuszkuc** [ExpediaGroup/graphql-kotlin#373]
**Library Version**
1.0.0-RC9

**Describe the bug**
[Federated GraphQL schema](https://www.apollographql.com/docs/apollo-server/federation/federation-spec/) requires specific SDL to be returned from the service (i.e. all the types available in the schema conditionally annotated with federation directives). Unfortunately due to the limitations on how `graphql-java` prints out the SDL we cannot conditionally include/exclude directives - if we specify that we want to print SDL with directives it will print out all directives present in the schema.

**To Reproduce**
Run federated example from [examples/federation](https://github.com/dariuszkuc/graphql-kotlin/tree/federation_with_directives)

Gateway will fail to start with following error

```
(node:16995) UnhandledPromiseRejectionWarning: GraphQLSchemaValidationError: Unknown directive "lowercase".

Unknown directive "lowercase".
    at ApolloGateway.createSchema (/Users/DKuc/Development/graphql-kotlin/examples/federation/gateway/node_modules/@apollo/gateway/dist/index.js:174:19)
    at ApolloGateway.<anonymous> (/Users/DKuc/Development/graphql-kotlin/examples/federation/gateway/node_modules/@apollo/gateway/dist/index.js:151:32)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/DKuc/Development/graphql-kotlin/examples/federation/gateway/node_modules/@apollo/gateway/dist/index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:16995) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Expected behavior**
Federated gateway starts successfully and exposes complete federated schema.

**Comment by aarestu** [comment]
I have a clue:
if I replace all custom directives in:

https://github.com/ExpediaGroup/graphql-kotlin/blob/4a704695e67176ab8b3fef6b4fccc3a30725e957/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt#L90

example:
```
 val sdl = originalSchema.print(includeDefaultSchemaDefinition = false)
    .replace(directiveRegex, "")
    .replace(scalarRegex, "")
    .replace(emptyQuery, "")
    .replace("@upper", "")
    .replace("@auth(roles : \"all\")", "")
    .trim()
```

Everything works fine

**Comment by dariuszkuc** [comment]
Workaround has been implemented in https://github.com/ExpediaGroup/graphql-kotlin/pull/374

Long term solution will be updated once https://github.com/apollographql/apollo-server/issues/3334 is resolved.
