### ISSUE TITLE
DataLoaders - how to use?

### ISSUE THREAD

**Issue by neetkee** [ExpediaGroup/graphql-kotlin#381]
Is it possible to use data loaders to perform batch queries? I can't find a way to use it with spring-server, I suppose we need to set dataLoaderRegistry somewhere in here?
https://github.com/ExpediaGroup/graphql-kotlin/blob/master/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLRequest.kt#L28

**Comment by neetkee** [comment]
I see, it's possible to extend SimpleQueryHandler, inject my own DataLoaderRegistry in it, and use it in DataFetcher. Is it right thing to do? 

And one more question, is there a reason why ExecutionResult.toGraphQLResponse() is internal here: [GraphQLResponse](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponse.kt)

**Comment by dariuszkuc** [comment]
Disclaimer: I haven't tried using data loader with this library

By default `graphql-kotlin` will invoke target underlying functions using [FunctionDataFetcher](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcher.kt). Within the target function itself you could easily add some data loading/batching logic.

You definitely can also override default query handler and try configuring your data loader registry there. If you get it working it would be great if you could contribute a PR to the example spring app.

----
re: `ExecutionResult.toGraphQLResponse() being internal

There wasn't a specific reason for it, it is just a convenience function so there wasn't a use case to make it pubic. Feel free to open up a PR to change it.

**Comment by smyrick** [comment]
Example checked in here: https://github.com/ExpediaGroup/graphql-kotlin/pull/396
