### ISSUE TITLE
Can't access /graphql endpoint - getting 400

### ISSUE THREAD

**Issue by SyedAsimAliSE** [ExpediaGroup/graphql-kotlin#382]
Hi,

i just copied spring example into my spring-boot project and included everything along with 
resource/graphql-playground.html file, everything is working i can see the schema generation in the logs :

![image](https://user-images.githubusercontent.com/44644354/65694588-894d4b00-e08f-11e9-95e7-d4b99ad5a24a.png)

but i am unable to run Playground in the browser : http://localhost:8080/graphql

i am getting HTTP ERROR 400 .

am i missing something in the configurations ? 

thanks

**Comment by dariuszkuc** [comment]
`/graphl` endpoint is an endpoint for posting your queries (you can use either do GET on it with query parameters or POST the body of the request).

Our example app configures Playground under `/playground` (https://github.com/ExpediaGroup/graphql-kotlin/blob/master/examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/RoutesConfiguration.kt#L32)

**Comment by SyedAsimAliSE** [comment]
ahh my bad i was used to NodeJS ApolloServer way to hit /graphql enpoint. 

thank you for quick response :) i missed to read the router configs
