### ISSUE TITLE
Extension Methods

### ISSUE THREAD

**Issue by de55** [ExpediaGroup/graphql-kotlin#383]
If I have an extension method like this:
```
fun Widget.doSomething() = "do something"
```

How would you go about adding that so you end up with a schema like:

```
type Widget {
 ...
  doSomething: String
}
```

**Comment by rickfast** [comment]
Not sure this is possible because reflection would have to scan everything on the class path to find all extension functions. That being said, extension functions that are members of a Kotlin class can be found via reflection, but the target of those is likely to be a different class.

**Comment by rickfast** [comment]
just read this https://discuss.kotlinlang.org/t/reflections-and-extension-function-confusion/1417/4

**Comment by de55** [comment]
I think to find the method you could use an annotation and then use reflection. Something like:
'''
annotation class GraphqlExtensionMethod

@GraphqlExtensionMethod
fun Widget.doSomething() = "do something"

val extensionMethods = reflections.getMethodsAnnotatedWith(GraphqlExtensionMethod::class.java)
'''
Also, it doesn't necessarily need to be an extension method. It could be implementing a custom resolver similar to the EntityResolver in the federation package.

That being said, either method would require having an instance of the class to pass into a function. Not sure how to get that though.
