### ISSUE TITLE
@provides references @external list field

### ISSUE THREAD

**Issue by de55** [ExpediaGroup/graphql-kotlin#399]
In graphql-kotlin-federation, the `validateProvidesDirective` function has a comment that says:
- [ERROR] @provides references @external list field
- [ERROR] @provides references @external interface field

And it is true, that `validateProvidesDirective` returns an error if I try to use `@provides` on an `@external` list or interface. Why is that an error? I just tested removing the error and was able to merge the schemas in a gateway and run without issue.

**Comment by dariuszkuc** [comment]
Those validations were based on https://www.apollographql.com/docs/apollo-server/federation/errors/

```
@provides directives
* PROVIDES_FIELDS_MISSING_EXTERNAL: The fields argument can only use fields marked as  @external on types from external services. These external types and fields must be included in the service for validation.
* PROVIDES_NOT_ON_ENTITY: The @provides directive can only be used on Object types with at least one @key, or Lists of such Objects.
* PROVIDES_FIELDS_SELECT_INVALID_TYPE: The fields argument can not reference fields that result in a list or interface.
```

**Comment by de55** [comment]
Thanks. Will close this questions.
