### ISSUE TITLE
SDL is null without keyed types. Is this intended?

### ISSUE THREAD

**Issue by jenssuhr** [ExpediaGroup/graphql-kotlin#416]
We tried to create a simple test project using a federated schema, using a server with graphql-kotlin (version 1.0.0-RC6) to supply an Apollo API gateway.
If there is no class annotated with `@KeyDirective(fields = FieldSet("<something>"))`, the generated schema will have no SDL: 
```graphql
{
  "data": {
    "_service": null
  }
}
```

Is this intended? We had a look at `com.expediagroup.graphql.federation.FederatedSchemaGeneratorHooks`, and noticed that the SDL depends on the filtered field list:

```kotlin
val entityTypeNames = originalSchema.allTypesAsList
    .asSequence()
    .filterIsInstance<GraphQLObjectType>()
    .filter { type -> type.getDirective("key") != null }
    .map { it.name }
    .toSet()

// register new federated queries
if (entityTypeNames.isNotEmpty()) {
    val entityField = generateEntityFieldDefinition(entityTypeNames)
    federatedQuery.field(entityField)

    // SDL returned by _service query should NOT contain
    // - default schema definition
    // - empty Query type
    // - directives
    // - new scalars
    val sdl = originalSchema.print(includeDefaultSchemaDefinition = false)
        .replace(directiveRegex, "")
        .replace(scalarRegex, "")
        .replace(emptyQuery, "")
        .trim()

    federatedCodeRegistry.dataFetcher(FieldCoordinates.coordinates(originalQuery.name, SERVICE_FIELD_DEFINITION.name), DataFetcher { _Service(sdl) })
    ...
```

The Apollo API gateway accepts federation schemas with types that have no key directive. We're not sure if the [federation specification](https://www.apollographql.com/docs/apollo-server/federation/federation-spec/) defines that types must have at least one key directive. All examples contain them, but it's not mentioned explicitly.

Proposal:
It would be nice if a warning was logged if the `entityTypeNames` list is empty. If it is not necessary to filter out types without a key from the SDL, the code generating the SDL should be moved outside the if clause.

**Comment by dariuszkuc** [comment]
Thanks for raising this. I think it should be possible to create federated schema without any federated types so this sounds like a bug to me.
