### ISSUE TITLE
[federation] federated traces support

### ISSUE THREAD

**Issue by dariuszkuc** [ExpediaGroup/graphql-kotlin#418]
**Is your feature request related to a problem? Please describe.**
`graphql-kotlin-federation` should provide support for capturing traces for federated requests.

**Describe the solution you'd like**
Instrumentation that can be included in GraphQL configuration to capture federated trace information.

**Describe alternatives you've considered**
N/A

**Additional context**
https://www.apollographql.com/docs/apollo-server/federation/metrics/

**Comment by tk26** [comment]
I'd like to take this issue up :)

**Comment by smyrick** [comment]
@tk26 I have assigned you. Feel free to start a discussion here on your ideas or start a draft PR to show some examples!

**Comment by Goregius** [comment]
Is it possible to use Apollo's federation-jvm library to use with this? 

```
@Bean
fun federatedTracingInstrumentation(): Instrumentation = FederatedTracingInstrumentation()
```

This is giving me a `DOWNSTREAM_SERVICE_ERROR` only for the gateway though.

**Comment by dariuszkuc** [comment]
> Is it possible to use Apollo's federation-jvm library to use with this?

Haven't tried it myself but technically it should be possible as `FederatedTracingInstrumentation` from `federation-jvm` is just another instrumentation. I believe thought it requires custom `GraphQLContext` to work.

**Comment by Goregius** [comment]
For some reason, it only works if I set the JDK version to 1.8, I was using JDK 11 before and it gave a ConcurrentModificationException when graphql-java was trying to execute the query

**Comment by smyrick** [comment]
Is this issue still valid? Including custom instrumentation through this package seems to have worked for others so I don't think it is required for the 2.0 release

https://github.com/apollographql/federation-jvm/blob/master/graphql-java-support/src/main/java/com/apollographql/federation/graphqljava/tracing/FederatedTracingInstrumentation.java

However maybe we can include this library in our federation lib so others don't have to? That could be a minor change/new feature release

**Comment by dariuszkuc** [comment]
@smyrick `federation-jvm` is another implementation of Apollo Federation model for `graphql-java`. It seems weird to suggest to include whole library (that basically does same thing as we do but following SDL first approach) to just get the tracing. 

If we are to support Apollo Federation we should make it a complete package including tracing support that nicely integrates with our `graphql-kotlin-spring-server`. This should be part of `2.0.0` release.

**Comment by smyrick** [comment]
Closed in https://github.com/ExpediaGroup/graphql-kotlin/pull/960
