### ISSUE TITLE
Maven Builds not Publishing?

### ISSUE THREAD

**Issue by rharriso** [ExpediaGroup/graphql-kotlin#427]
**Library Version**
0.6.1 - unable to upgrade

**Describe the bug**
It doesn't look like versions 1.0.0 or 1.1.0 were published.

* https://mvnrepository.com/artifact/com.expedia/graphql-kotlin
* https://repo.maven.apache.org/maven2/com/expedia/graphql-kotlin/

**To Reproduce**
Update pom version to 1.0.0 or 1.1.0. Run `mvn` install, see below error message:

```
Could not resolve dependencies for project nyc.rowan:api-gateway:jar:1.0-SNAPSHOT: Failure to find com.expedia:graphql-kotlin:jar:1.1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced 
```

**Expected behavior**
The new version of the library should install.

**Comment by smyrick** [comment]
@rharriso As per the 1.0.0 release notes we have moved to the `com.expediagroup` group id


https://github.com/ExpediaGroup/graphql-kotlin/releases/tag/1.0.0

Also see the updated `Installation` page in our new docs https://expediagroup.github.io/graphql-kotlin/docs/getting-started.html#installation

**Comment by rharriso** [comment]
@smyrick great! thanks for the update
