### ISSUE TITLE
Spring Sample: Could not find artifact com.expediagroup:graphql-kotlin-spring-server:jar:1.1.1-SNAPSHOT

### ISSUE THREAD

**Issue by martinbonnin** [ExpediaGroup/graphql-kotlin#429]
From current master (d6e5718dfeade09c46a18468cf7a4e97ec1dbbbb), it is not possible to build the spring sample:

```bash
~/git/graphql-kotlin/examples/spring$ mvn clean install
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] 
[INFO] ------------------< com.expediagroup:spring-example >-------------------
[INFO] Building spring-example 1.1.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.expediagroup:graphql-kotlin-spring-server:jar:1.1.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.614 s
[INFO] Finished at: 2019-10-16T10:47:21+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project spring-example: Could not resolve dependencies for project com.expediagroup:spring-example:jar:1.1.1-SNAPSHOT: Could not find artifact com.expediagroup:graphql-kotlin-spring-server:jar:1.1.1-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by gscheibel** [comment]
Hello @martinbonnin,

We do not publish the snapshot version `1.1.1-SNAPSHOT` and but the `1.1.1` is available in Maven Central: https://search.maven.org/artifact/com.expediagroup/graphql-kotlin-spring-server/1.1.0/jar

**Comment by martinbonnin** [comment]
I just typed `mvn clean install` from the spring sample directory. I was expecting this to work out of the box. Or do I need to tweak the setup ?

**Comment by martinbonnin** [comment]
Looks like running install in the root project did the trick. PR there: https://github.com/ExpediaGroup/graphql-kotlin/pull/430

**Comment by martinbonnin** [comment]
Now I'm stuck on `mvn spring-boot:run`:

```
[ERROR] No plugin found for prefix 'spring-boot' in the current project and in the plugin groups 
```

**Comment by smyrick** [comment]
@martinbonnin I am having the same issue locally on master branch now too. Running the Application from IntelliJ does work for me though so in the meantime can you try that. I will look in to why this is failing.

**Comment by smyrick** [comment]
@martinbonnin Make sure you run a `clean install` to remove and dependencies and just verify after, that the `~/.m2/repository/com/expediagroup/graphql-kotlin-spring-server/1.1.1-SNAPSHOT` directory exists and it contains the jar file.

If not I would just remove all the `~/.m2/repository/com/expediagroup/graphql-kotlin*` directories and do another clean install
