### ISSUE TITLE
[schema-generator] remove DataFetcherExecutionPredicate from SchemaGeneratorHooks 

### ISSUE THREAD

**Issue by dariuszkuc** [ExpediaGroup/graphql-kotlin#432]
**Is your feature request related to a problem? Please describe.**
`SchemaGeneratorHooks` are used to modify the behavior of schema generation. `DataFetcherExecutionPredicate` is used at runtime by `FunctionDataFetcher` to allow modification of parameters based on the predicates (e.g. apply JSR-303 bean validations, see [spring example](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/ValidatedQuery.kt)).  

**Describe the solution you'd like**
`SchemaGeneratorHooks` should not contain the predicate. Maybe it should be part of the `SchemaGeneratorConfig` instead?

**Describe alternatives you've considered**
Do we even need to support the predicate evaluation in data fetcher? Directives could be used instead.

**Comment by smyrick** [comment]
I think we can just delete the predicate all together. If someone wants custom behaviours they can now provide their own `DataFetcherFactory`
