### ISSUE TITLE
Javadocs not being published

### ISSUE THREAD

**Issue by smyrick** [ExpediaGroup/graphql-kotlin#443]
**Describe the bug**
It appear the last published version of our javadocs under the new group id is `1.0.0-RC10`

https://www.javadoc.io/doc/com.expediagroup/graphql-kotlin-schema-generator/1.0.0-RC10

RC11, 1.0.0, 1.1.0, and 1.2.0 all do not have published docs

Here are the changes published in RC11: https://github.com/ExpediaGroup/graphql-kotlin/releases/tag/1.0.0-RC11

**Expected behavior**
Javadocs are published to Maven Central and therefore to javadoc.io

**Comment by smyrick** [comment]
Not sure why javadoc.io is not picking these up but I see the `javadoc.jar` in Maven Central

https://repo1.maven.org/maven2/com/expediagroup/graphql-kotlin-schema-generator/

**Comment by smyrick** [comment]
`graphql-kotlin-spring-server` has latest docs but `federation` and `schema-generator` do not

**Comment by smyrick** [comment]
The javadoc jars are published but they are clearly missing some of the base files, like HTML and CSS that the spring server has in the jar

![Screen Shot 2019-10-17 at 3 26 57 PM](https://user-images.githubusercontent.com/2446877/67052323-a3100a00-f0f2-11e9-8953-41435f03b2ff.png)

**Comment by dariuszkuc** [comment]
Reopening as unsure if lib upgrade actually fixed the issue or not - we need to verify it first.

**Comment by smyrick** [comment]
1.2.2 docs now published:

* https://www.javadoc.io/doc/com.expediagroup/graphql-kotlin-spring-server/1.2.2
* https://www.javadoc.io/doc/com.expediagroup/graphql-kotlin-federation/1.2.2
* https://www.javadoc.io/doc/com.expediagroup/graphql-kotlin-schema-generator/1.2.2
