### ISSUE TITLE
Add a simple way to attach additional fields to a GraphQL type without modifying the class

### ISSUE THREAD

**Issue by iguissouma** [ExpediaGroup/graphql-kotlin#471]
**Is your feature request related to a problem? Please describe.**
Add a simple way to attach additional fields to a GraphQL type without modifying the class.

**Describe the solution you'd like**
I like the approach used by the library [graphql-spqr](https://github.com/leangen/graphql-spqr)

```
public class User {

    private String name;
    private Integer id;
    private Date registrationDate;

    @GraphQLQuery(name = "name", description = "A person's name")
    public String getName() {
        return name;
    }

    @GraphQLQuery
    public Integer getId() {
        return id;
    }

    @GraphQLQuery(name = "regDate", description = "Date of registration")
    public Date getRegistrationDate() {
        return registrationDate;
    }
}
```

To attach additional fields to the `User` GraphQL type, without modifyning the `User` class, you simply add a query that has User as the context. The simplest way is using the @GraphQLContext annotation:

```
class UserService {

    // Attach a new field called twitterProfile to the User GraphQL type
    @GraphQLQuery
    public TwitterProfile twitterProfile(@GraphQLContext User user) {
      ...
    }
}
```

**Describe alternatives you've considered**
Now, we can use lateinit varaible with CustomDataFetcher...

**Additional context**
N/A

**Comment by dariuszkuc** [comment]
Can you elaborate more on your use case for supporting this?

Related: https://github.com/ExpediaGroup/graphql-kotlin/issues/383 and https://github.com/ExpediaGroup/graphql-kotlin/pull/384

**Comment by iguissouma** [comment]
Having

`data class User(val id: Int, val name: String, val registrationDate:Date)`

And 

```
@Component
class UserQuery : Query{

     fun userById(@GraphQlID id: String): User? {
          //get User from a dataSource
     }

    fun twitterProfile(@CustomAnnotation user:User): TwitterProfile? {
       //get twitter profile using user as argument
    }

}

```
`@CustomAnnotation` indicate that the twitterProfile should be added as a field twitterProfile to the User and not as a separate query

I want to have this schema as a Result

```
type User {
    id: ID!
    name: String!
    registrationDate: String
    twitterProfile: TwitterProfile
}

type TwitterProfile {
  code: String!
  numberOfTweets
}

type Query {
  userById(id: ID!): User
}
```

And be able to query Like below 

```
{ user (id: 123) {
         name,
         twitterProfile {
           code
           numberOfTweets
         }
    }}
```

You can read more about spqr walking through this [article](https://medium.com/@iguissouma/rapid-development-of-simple-crud-graphql-apis-in-java-and-spring-boot-bafc4e8d387a), you can see how is easy to add query that run on object context (isCool and giphyUrl)

Hope the feature is more clear.

**Comment by dariuszkuc** [comment]
The example above can be easily represented in the graph as

```
class User(val id: Int, val name: String, val registrationDate:Date) {
  fun twitterProfile(): TwitterProfile? { ... }
}
```

which IMHO also leads to a clearer structure (i.e. instead of defining your all queries in single file you are traversing the objects as you go through it). If you don't want to modify the data classes to contain some functions in them I'd recommend to take a look at the referenced issues around support for generating schema for extension functions.

**Comment by iguissouma** [comment]
I see.
But what if I need to inject a Service or Repository to get the TwitterProfile,
What is the recommended design?

**Comment by smyrick** [comment]
@iguissouma non-public members of a class are not exposed as part of the graphql schema. So if the `User` has DI you can attach the members there.

Example from our spring example. Note, you shouldn't have to use the `beanFactory` method anymore since you can include the `DataFetcherEnvironment` as part of the arguments

https://github.com/ExpediaGroup/graphql-kotlin/blob/8d0c4981ff063cc52f7b60bd5a89353f8d06d63d/examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/NestedQueries.kt#L31-L32

**Comment by smyrick** [comment]
Going to close this issue as discussion has provided alternatives, and we have already discussed the difficulties of supporting extension methods through reflection.

**Comment by philaw** [comment]
> I see.
> But what if I need to inject a Service or Repository to get the TwitterProfile,
> What is the recommended design?

We are having similar problem and found out the solution to use custom DataFetcher, for your reference:
https://github.com/ExpediaGroup/graphql-kotlin/blob/798ff31046bf6df1eaf26229f735d6b555855caa/examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/OrganizationQuery.kt#L41

and to register a dataloader is required where a service can be injected:
https://github.com/ExpediaGroup/graphql-kotlin/blob/798ff31046bf6df1eaf26229f735d6b555855caa/examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/dataloaders/DataLoaderConfiguration.kt#L20

and also need this SpringDataFetcherFactory to link them:
https://github.com/ExpediaGroup/graphql-kotlin/blob/798ff31046bf6df1eaf26229f735d6b555855caa/examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/execution/SpringDataFetcherFactory.kt#L28
