### ISSUE TITLE
Failed to bind properties under 'graphql.playground' to com.expediagroup.graphql.spring.PlaygroundConfigurationProperties

### ISSUE THREAD

**Issue by iguissouma** [ExpediaGroup/graphql-kotlin#479]
**Library Version**
1.4.0

**Describe the bug**
When I add graphql.playground=false on application.properties I got the following error

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'graphql.playground' to com.expediagroup.graphql.spring.PlaygroundConfigurationProperties:

    Property: graphql.playground.enabled
    Value: false
    Origin: class path resource [application.properties]:8:28
    Reason: No setter found for property: enabled

Action:
Update your application's configuration

```

**To Reproduce**
add graphql.playground=false on application.properties 

**Expected behavior**
properties in this classes FederationConfigurationPropertiesSubscriptionConfigurationProperties, PlaygroundConfigurationProperties and SDLConfigurationProperties can be overided on application.[properties|yml]

**Comment by dariuszkuc** [comment]
Which version of Spring are you using? e.g. I just tried to reproduce in our example app and it all started fine (https://github.com/ExpediaGroup/graphql-kotlin/blob/master/examples/spring/src/main/resources/application.yml).

**Comment by iguissouma** [comment]
I use :: Spring Boot ::        (v2.2.1.RELEASE)

**Comment by iguissouma** [comment]
I shared a project on [github](https://github.com/iguissouma/graphql-kotlin-479) where I reproduce the problem.

**Comment by smyrick** [comment]
@dariuszkuc @iguissouma I wonder if we need to release version 1.4.1 which updated our deps to spring boot 2.2.1

https://github.com/ExpediaGroup/graphql-kotlin/releases/tag/untagged-33477a5df5fe62ab0b32

Specifically with this PR: https://github.com/ExpediaGroup/graphql-kotlin/pull/474

**Comment by iguissouma** [comment]
@smyrick @dariuszkuc thanks, I will test when the new version is released.

**Comment by dariuszkuc** [comment]
Indeed this is an issue with breaking change in behavior between SpringBoot `2.2.0.RELEASE` and `2.2.1.RELEASE`. With 2.2.1 Spring team "fixed" "invalid" behavior of automatically applying `ConstructorBinding` to all objects that were referenced from `ConfigurationProperties` (that were configured to use `ConstructorBinding`). Unsure why they changed the behavior as IMHO it was simpler in 2.2.0 - I guess it was causing some issues when mixing constructor and field bindings.

I just released 1.4.1 which should fix your issue.

**Comment by smyrick** [comment]
We had an issue with the travis build for 1.4.1 so it did not publish properly. We are fixing the build config and should be updated in 1.4.2

**Comment by iguissouma** [comment]
@dariuszkuc @smyrick works as expected in 1.4.2
thanks.
