### ISSUE TITLE
Allow graphql.subscriptions.endpoint to be equals to graphql.endpoint = graphql 

### ISSUE THREAD

**Issue by iguissouma** [ExpediaGroup/graphql-kotlin#484]
**Is your feature request related to a problem? Please describe.**
I want my graphql subscriptions endpoint to be `graphql` and not the default value `subscriptions`.
When I set `graphql.subscriptions.endpoint=graphql` the application started without problem but it seems that the graphql endpoint stop working.
playground can't connect to the server and when I run a query I get the following response from server:

```
{
  "error": {
    "timestamp": "2019-11-19T19:52:42.530+0000",
    "path": "/graphql",
    "status": 405,
    "error": "Method Not Allowed",
    "message": "Request method 'POST' not supported",
    "requestId": "b32bd99c"
  }
}

```
**Describe the solution you'd like**
It should be possible to handle the websocket and http endpoint with the same path `/graphql`. 

**Describe alternatives you've considered**
N/A

**Additional context**
On many frontend app using apollo client the usual way to setup the client is as following, we just replace the http(s) by ws(s) to have the websocket URI.

```
const httpUri = process.env.APP_SERVER_URL + '/graphql';
const wsUri = httpUri.replace(/^https?/, 'ws');

const httpLink = new HttpLink({
  uri: httpUri,
  credentials: 'include',
});

const wsLink = new WebSocketLink({
  uri: wsUri,
  options: {
    // Automatic reconnect in case of connection error
    reconnect: true,
  },
});
```

**Comment by smyrick** [comment]
@iguissouma Unfortunately this is a limitation of the websocket protocol itself

https://stackoverflow.com/questions/48006498/is-this-possible-to-server-websocket-handler-and-normal-servlet-over-same-contex

This is also why `apollo-server` (javascript graphql server) also exposes a separate url for subscriptions

https://www.apollographql.com/docs/apollo-server/data/subscriptions

**Comment by iguissouma** [comment]
@smyrick thanks for your reply
If I'm not mistaken by default the subscriptionsPath is same as graphqlPath. 

See Running `apollo-server` sample:
<img width="567" alt="Screenshot 2019-11-20 at 08 44 24" src="https://user-images.githubusercontent.com/9085108/69219083-59dc2b80-0b72-11ea-8035-a1d40b38de42.png">

On [graphql-spqr-spring-boot-starter](https://github.com/leangen/graphql-spqr-spring-boot-starter) library, the websocket endpoint is configured the same as http endpoint if no value is precised and evrything is working fine.

```
 @Override
    public void registerWebSocketHandlers(WebSocketHandlerRegistry webSocketHandlerRegistry) {
        String webSocketEndpoint = config.getWs().getEndpoint();
        String graphQLEndpoint = config.getHttp().getEndpoint();
        String endpointUrl = webSocketEndpoint == null ? graphQLEndpoint : webSocketEndpoint;
        webSocketHandlerRegistry
                .addHandler(webSocketHandler(webSocketExecutor(webSocketContextFactory())), endpointUrl)
                .setAllowedOrigins(config.getWs().getAllowedOrigins());
    }
```

**Comment by smyrick** [comment]
Hm, ok we can take a look at if this is possible then in spring
