### ISSUE TITLE
Can graphql-kotlin be used with micronaut?

### ISSUE THREAD

**Issue by macmillan78** [ExpediaGroup/graphql-kotlin#506]
Is there a way to use graphql-kotlin with micronaut to take advantage of AOT compilation and the memory and time savings? Maybe in conjunction with micronaut-spring ...

**Comment by smyrick** [comment]
@macmillan78 We have not personally tested using micronaut but I don't see any reason why you wouldn't be able to use the spring parts as we don't have any logic that makes us different than any other spring app.

If that doesn't work, please create an issue. You should also be able to use the `graphql-kotlin-schema-generator` without spring if you wanted to use Ktor or some other server framework

**Comment by dariuszkuc** [comment]
AFAIK it would be pretty challenging to use schema generation with micronaut as we build schemas at runtime using reflection.

**Comment by macmillan78** [comment]
Ok, thx, I will try @smyrick 's hint when I have time ...

**Comment by gscheibel** [comment]
There is a GraphQL module / support for Micronaut based on graphql-java.
As Shane mentioned you can directly use the the schema generator and manually hooking with micronaut-graphql.

Last time I checked (~11 months ago) it looked like:
This example is based on a very old version of graphql-kotlin it should show you the gist of it.
The big difference was on the level of configuration (error handling, interceptors etc) which was/is limited with micronaut-graphql.

```
import com.expedia.graphql.SchemaGeneratorConfig
import com.expedia.graphql.TopLevelObject
import com.expedia.graphql.toSchema
import graphql.ExecutionInput
import graphql.GraphQL
import graphql.execution.instrumentation.Instrumentation
import graphql.execution.instrumentation.SimpleInstrumentation
import graphql.execution.instrumentation.parameters.InstrumentationExecutionParameters
import io.micronaut.context.annotation.Bean
import io.micronaut.context.annotation.Factory
import io.micronaut.graphql.GraphQLContextBuilder
import io.micronaut.http.HttpRequest
import org.slf4j.LoggerFactory
import java.util.UUID
import javax.inject.Singleton

@Factory
class GraphQLFactory {
    private val logger = LoggerFactory.getLogger(GraphQLFactory::class.java)

    @Bean
    @Singleton
    fun graphQL(queries: List<Query>, instrumentations: List<Instrumentation>): GraphQL {
        val topLevelQueries = queries.map { TopLevelObject(it) }

        val config = SchemaGeneratorConfig(supportedPackages = listOf("bex.api.micronaut"))

        val schema = toSchema(
            queries = topLevelQueries,
            config = config
        )

        val graphQL = GraphQL.newGraphQL(schema)
        instrumentations.forEach { graphQL.instrumentation(it) }
        return graphQL.build()
    }

    @Bean
    @Singleton
    fun contextBuilder(): GraphQLContextBuilder = GraphQLContextBuilder { req ->
        MyContext(UUID.randomUUID(), req)
    }
}

@Singleton
class MyInstrumentation : SimpleInstrumentation() {

    private val logger = LoggerFactory.getLogger(MyInstrumentation::class.java)

    override fun instrumentExecutionInput(executionInput: ExecutionInput?, parameters: InstrumentationExecutionParameters?): ExecutionInput {
        val myContext = executionInput?.context as? MyContext

        logger.info("ExecutionID=${myContext?.customId}")

        return super.instrumentExecutionInput(executionInput, parameters)
    }
}

data class MyContext(
    val customId: UUID,
    val httpRequest: HttpRequest<*>?
)

interface Query
```

**Comment by manideepl** [comment]
@smyrick 
We generate the schema using the schema generator module, but how do I actually write resolvers for the generated queries/mutations in Ktor?
Are there pointers to this?

**Comment by dave08** [comment]
Just a question without knowing too much about graphql or graphql-kotlin... wouldn't it be possible to make a gradle plugin to create the schemas before runtime @dariuszkuc ? Then no runtime reflection would need to be used...

**Comment by dariuszkuc** [comment]
@dave08 schema artifacts can be generated at compile time using the plugins but unless we move to something like a custom compiler plugin I don't think we will be able to eliminate dependency on reflection at runtime.
