### ISSUE TITLE
Including Voyager

### ISSUE THREAD

**Issue by elenigen** [ExpediaGroup/graphql-kotlin#507]
I'm curious if you have considered to include Voyager next to Playground.

**Describe the solution you'd like**
https://github.com/APIs-guru/graphql-voyager

**Additional context**
[![voyager demo](https://raw.githubusercontent.com/APIs-guru/graphql-voyager/master/docs/demo-gif.gif)](https://apis.guru/graphql-voyager/)

**Comment by smyrick** [comment]
@elenigen We use voyager internally as well and think it is a very useful tool. It should be pretty simple to just add another route to your spring server to expose the HTML file. We didn't include it by default though because we didn't want to choose the tools for everyone.

**Comment by smyrick** [comment]
@ExpediaGroup/graphql-kotlin-committers what does everyone else think? We can leave this request open for now, to see if there are more requests to include this by default or just let server developers add it themselves

**Comment by tapaderster** [comment]
Voyager is a great tool, but I agree with Shane here. Unless there is huge interest in adding this by default, I would let server devs add it manually in their own projects.

**Comment by dariuszkuc** [comment]
While voyager can be useful I don't think it should be bundled by default.

**Comment by smyrick** [comment]
Ok, I think then with consensus we can close this issue. @elenigen You can add voyager easily to your own server if you want to expose that to your clients

**Comment by elenigen** [comment]
I was just thinking that you already packaged Playground with it, so why not Voyager, but on the other hand Playground is much more "essential" to try an API.
Thanks for your time and yes, I already included an endpoint for this.
