### ISSUE TITLE
Support List for input types

### ISSUE THREAD

**Issue by smyrick** [ExpediaGroup/graphql-kotlin#509]
**Is your feature request related to a problem? Please describe.**
Currently we have a check on the library, that input types can not be an interface. This is because that is part of the [GraphQL spec](https://graphql.github.io/graphql-spec/June2018/#sec-Field-Arguments). The work around is to use a concrete class like [`ArrayList`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-array-list/index.html). If we have a type that is shared for input and output, that means that we have to use `ArrayList`s everywhere or use `List`s just for the output.

**Describe the solution you'd like**
In Kotlin, most developers use `List<T>` over `ArrayList<T>`. So in our library could we just convert the List to a `GraphQLList` from graphql-java and override the interface check just for `List`?

**Describe alternatives you've considered**
We could not support this feature and make developers use concrete classes for inputs which would be less logic in the library.

**Comment by dariuszkuc** [comment]
While it is indeed extra check in the library I think it is more natural to define your method signature with list over array so I believe we should support it.
