### ISSUE TITLE
Support for quote descriptions (Docstrings)

### ISSUE THREAD

**Issue by Goregius** [ExpediaGroup/graphql-kotlin#533]
**Is your feature request related to a problem? Please describe.**
Currently, the schema generator can only produce descriptions for functions, types, etc. with # comments instead of quote descriptions (with " or """). This is problematic as Apollo servers with Federation strip these # descriptions away but allows quoted descriptions, this is intentional as # comments for descriptions are depreciated.

**Describe the solution you'd like**
Graphql-java has already fixed this but the fix isn't out as a major release yet. Either wait for that to come out, use a daily release version that has this feature (unlikely), or find a way to support it within this library (I don't see how that is possible without making a custom schema printer).

**Additional context**
The changes graphql-java made can be seen in this PR: https://github.com/graphql-java/graphql-java/pull/1609.

**Comment by smyrick** [comment]
This should be fixed with a graphql-java upgrade https://github.com/ExpediaGroup/graphql-kotlin/issues/565
