### ISSUE TITLE
Dependency on spring-boot-starter-web broke graphql-kotlin-spring-server. Maybe update docs?

### ISSUE THREAD

**Issue by viktorchukhantsev** [ExpediaGroup/graphql-kotlin#537]
Hello. I'm tried to create example application(using start.spring.io) with playground and everything and found that dependency on spring-boot-starter-web broke graphql-kotlin-spring-server. Looks like because it uses Tomcat server. I'm newbie with Spring stack. This isn't covered in docs and take me several hours to understand what was broken. Maybe somebody with more experience should cover this situation in documentation?

**Comment by smyrick** [comment]
@viktorchukhantsev I have updated the docs in the above linked PR. Feel free to contribute to the documentation yourself if something is unclear or reference our [examples](https://github.com/ExpediaGroup/graphql-kotlin/tree/master/examples)

**Comment by viktorchukhantsev** [comment]
@smyrick Thank you 👍

**Comment by dariuszkuc** [comment]
Updated docs are available at https://expediagroup.github.io/graphql-kotlin/docs/spring-server/spring-overview
