### ISSUE TITLE
Authentication with subscriptions

### ISSUE THREAD

**Issue by de55** [ExpediaGroup/graphql-kotlin#543]
How would you recommend hooking into the onConnect event for subscriptions, similar to here: 

https://www.apollographql.com/docs/graphql-subscriptions/authentication/

**Comment by dariuszkuc** [comment]
I'd assume it should be handled the same way as for the regular queries, i.e. through GraphQLContext populated by a webfilter that is executed before any query/mutation/subscription execution.

**Comment by Goregius** [comment]
Maybe there could be an example project with authentication (webfilter/directive based) in the examples folder at some point?

**Comment by de55** [comment]
Unlike an http request, the websocket request auth information doesn't come through the headers. Instead, it comes through the initial payload. Right now, I don't see any easy way to access the initial payload information, as the available beans to override in the spring server are:
- ```SubscriptionHandler ```
- ```WebSocketHandlerAdapter```

Neither of these locations allows access to the payload (as far as I'm aware).

What would you think about adding hooks within the ```ApolloSubscriptionProtocolHandler```? We could either just add one in the ```GQL_CONNECTION_INIT.type``` statement (this would be similar to the Apollo OnConnect property) or you could take it a step further and add a hook into every section.
```
   @Suppress("Detekt.TooGenericExceptionCaught")
    fun handle(payload: String, session: WebSocketSession): Flux<SubscriptionOperationMessage> {
        try {
            val operationMessage: SubscriptionOperationMessage = objectMapper.readValue(payload)

            logger.debug("GraphQL subscription client message, sessionId=${session.id} operationMessage=$operationMessage")

            when (operationMessage.type) {
                GQL_CONNECTION_INIT.type -> {
                    // add a hook here to access the message before acknowledging it
                    // the payload property is what we need access to
                    val ackowledgeMessageFlux = Flux.just(acknowledgeMessage)
                    val keepAliveFlux = getKeepAliveFlux(session)
                    return ackowledgeMessageFlux.concatWith(keepAliveFlux)
                }
                GQL_START.type -> return startSubscription(operationMessage, session)
                GQL_STOP.type -> return sessionState.stopOperation(session, operationMessage)
                GQL_CONNECTION_TERMINATE.type -> {
                    sessionState.terminateSession(session)
                    return Flux.empty()
                }
                else -> {
                    logger.error("Unknown subscription operation $operationMessage")
                    sessionState.stopOperation(session, operationMessage)
                    return Flux.just(SubscriptionOperationMessage(type = GQL_CONNECTION_ERROR.type, id = operationMessage.id))
                }
```

Please let me know if you know of a different way to access the payload.

**Comment by de55** [comment]
Following the **Message Flow** section of the [spec](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md) closer, there should be the following callbacks:
- onConnect (this would occur on GQL_CONNECTION_INIT and should be added to the context for subscriptions)
- onOperation (this would occur on GQL_START before running the subscription)
- onOperationDone (this would occur on GQL_STOP before? stopping the subscription)

In the [Apollo Subscription Server](https://www.apollographql.com/docs/graphql-subscriptions/lifecycle-events/), they have two differences from above:
- They call onOperationDone onOperationComplete
- They added an onDisconnect event  (this would occur on GQL_CONNECTION_TERMINATE before? terminating the session)

I can implement these (preferably in 1.xx), if you are okay having the changes in the library.

**Comment by dariuszkuc** [comment]
Thanks @de55 for looking! Indeed webfilter solution won't work (i.e. our current implementation). I like the idea of the hooks.

> I can implement these (preferably in 1.xx), if you are okay having the changes in the library.

We are about to do a `2.0.0-RC1` release soon as we accumulated quite a few fixes/changes already. If needed we should be able to backport this change to `1.x.x`.

**Comment by dariuszkuc** [comment]
> * onConnect (this would occur on GQL_CONNECTION_INIT and result should be added to the context for subscriptions)

I was just thinking about it and unsure if context will work in current implementation, i.e. we are still bound to `graphql-java` implementation which sets the context when it starts executing the subscription (https://github.com/ExpediaGroup/graphql-kotlin/blob/master/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionHandler.kt#L50). I guess we could make some special mutable context but unsure if that will work.

**Comment by de55** [comment]
Adding mutable properties to a context is the way I was thinking of handling it. I tested it using this context:

```
class MyGraphQLContext(
    val request: ServerHttpRequest,
    val response: ServerHttpResponse,
    var session: WebSocketSession?,
    val connectionParams: MutableMap<String, String>
)
```

And I was able to successfully add the session and connectionParams to the object from the onConnect function I created.

**Comment by dariuszkuc** [comment]
@de55 is there any reason why you wrapped subscription context in `Mono`? if possible we should try to avoid putting reactor dependency there

**Comment by gklijs** [comment]
Not sure how usefull this will be, but the micronaut implementation of websockets allow to get the original  HttpRequest in the `onOpen`. By storing it in the session it can later be used on GraphQL invocation.
