### ISSUE TITLE
[generator] allow interfaces to implement other interfaces

### ISSUE THREAD

**Issue by dariuszkuc** [ExpediaGroup/graphql-kotlin#589]
**Is your feature request related to a problem? Please describe.**
GraphQL spec now supports nested interfaces. `graphql-kotlin-schema-generator` should support this as well.

**Describe the solution you'd like**
`graphql-kotlin-schema-generator` should be able to generate schemas with nested interfaces 

**Describe alternatives you've considered**
N/A

**Additional context**
GraphQL spec PR: https://github.com/graphql/graphql-spec/pull/373

**Comment by smyrick** [comment]
We may just want to wait until this is added in graphql-java first: https://github.com/graphql-java/graphql-java/issues/1764
