### ISSUE TITLE
[generator] support repeatable directives

### ISSUE THREAD

**Issue by dariuszkuc** [ExpediaGroup/graphql-kotlin#590]
**Is your feature request related to a problem? Please describe.**
GraphQL spec now supports repeated directives. `graphql-kotlin-schema-generator` should support it as well.

**Describe the solution you'd like**
`graphql-kotlin-schema-generator` should be able to generate a schema with fields that have repeated directives.

**Describe alternatives you've considered**
N/A

**Additional context**
GraphQL spec PR: https://github.com/graphql/graphql-spec/pull/472

**Comment by smyrick** [comment]
We should wait until support is added in graphql-java before we support this in our library: https://github.com/graphql-java/graphql-java/issues/1763

**Comment by elucidator** [comment]
Issue seems to be resolved in 16.0

Any progess on this planned?

**Comment by dariuszkuc** [comment]
I just looked into this and while `graphql-java` does support repeatable directives, unfortunately Kotlin still does not support repeatable annotations with `RUNTIME` retention (see https://youtrack.jetbrains.com/issue/KT-12794). We need `RUNTIME` retention on the directive annotations so we can access them using reflections.

Suggested workaround of using some wrapper annotation won't work as annotations do not extend other annotations so we won't be able to pass instances of custom directives.

```kotlin
annotation class GraphQLRepeatableDirectives(
    val directives: Array<GraphQLDirective>
)

@GraphQLRepeatableDirectives(
  directives = [CustomDirective("foo")] // type mismatch 
)
class Foo(val bar: String)
```

Based on the above I am unsure whether we will be able to support repeatable directives until https://youtrack.jetbrains.com/issue/KT-12794 is resolved or we move away from annotations.

**Comment by elucidator** [comment]
Ok, this was not the answer I expected. But the answer is clear.

Might I suggest a different approach work around?

Currently we have:
annotation class KeyDirective(val fields: FieldSet)

What if to support multiple Key directives in the code we replace this with:
annotation class KeyDirective(val fields: Array<FieldSet>)
With this approach we circumvent the repeatable annotations but get the information I a contained manner to the code base.

Pieter

**Comment by dariuszkuc** [comment]
According to [Kotlin Roadmap](https://kotlinlang.org/docs/roadmap.html#roadmap-details) they will be tackling [KT-12794](https://youtrack.jetbrains.com/issue/KT-12794) in the next couple months. 

Proposed solution of using `Array<FieldSet>` would require some custom processing logic just for this single directive. Guess we could potentially add another schema generator hook specifically for building out the directives.
