### ISSUE TITLE
Is there is a way to add type Resolvers?

### ISSUE THREAD

**Issue by egormasalitin** [ExpediaGroup/graphql-kotlin#592]
We've been using `graphql-java-tools` for a month now, and everything was fine except that we are getting bigger, and we need schema generation. I've been thinking about switching to `graphql-kotlin` (thanks for working on it btw). But I have a question.

In `graphql-java-tools` there is an option to create type resolvers, and it is awesome (main reason we decided to use it in the first place)

It allows you to do stuff like:
```    kotlin
@Component
class PersonResolver(val loader: RelationLoader) : GraphQLResolver<Person> {
    fun getRelatedTo(person: Person) : List<Person> = loader.loadRelated(person.id)
}
```

But I don't see a way to do this kind of stuff in `graphql-kotlin` but maybe I'm missing something, can you please help me?

**Comment by dariuszkuc** [comment]
Great question. I'm not that familiar with `graphql-java-tools` but it looks like their `GraphQLResolver` is their way to expose `graphql-java` "non-trivial" data fetchers (i.e. not object properties which are resolved through corresponding getter). `graphql-java` makes a distinction between their data fetcher (i.e. resolve/fetch data) and type resolver (used to resolve polymorphic types) - see https://www.graphql-java.com/documentation/v11/schema/.

When using`graphql-kotlin-schema-generator` all your object properties and functions are exposed as corresponding GraphQL fields, i.e.

```kotlin
class Person(val id: Int, val name: String, private val loader: RelationLoader) {
   fun getRelatedTo() = loader.loadRelatedTo(id)
}
```

will generate

```graphql
type Person {
  id: Int!
  name: String!
  getRelatedTo: [Person!]!
}
```

There are number of ways you could autowire the beans and expose them (e.g. see our [example app](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/SubQueries.kt)). If your `RelationLoader` is a `DataLoader` it can be also read directly from `DataFetchingEnvironment` that can be automatically wired up for your query. If you were to use `graphql-kotlin-spring-server` it could look something like this

```kotlin
// this is your top level query to fetch Person, assumes there is some service to load it
@Component
class PersonQuery(private val service: PersonService) : Query {
  fun person(id: Int): Person =  service.loadPerson(id)
}

class Person(val id: Int, val name: String) {
  fun getRelatedTo(env: DataFetchingEnvironment): List<Person> = 
    environment.getDataLoader<Int, Person>("personRelationLoader")
            .load(id)
}
```

**Comment by smyrick** [comment]
I am going to close the issue as an answer was provided. If you need more details or would like to reach out you can also always reach us in our community Slack channel

https://github.com/ExpediaGroup/graphql-kotlin#-contact

**Comment by egormasalitin** [comment]
@smyrick Sure, I'm so sorry for not responding to your answer, I had no time trying your solution, but I will try it and reach out for sure, thank you so much

Thank you @dariuszkuc For provided answer
