### ISSUE TITLE
Queries/Mutations over websockets

### ISSUE THREAD

**Issue by de55** [ExpediaGroup/graphql-kotlin#607]
GraphQL allows queries/mutations to be sent over websockets as well. Is it currently possible in the spring server library to do this?

**Comment by gscheibel** [comment]
Hello @de55 

Queries and Mutations are not meant to be supported by this protocol.
If you want to leverage websockets, you should use `Subscriptions`.

We have an example [here](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscription.kt)
