### ISSUE TITLE
Return partial data from subscription

### ISSUE THREAD

**Issue by de55** [ExpediaGroup/graphql-kotlin#608]
Is there a way to return partial data from a subscription?

Just to test it out with DataFetcherResult, I tried this:

```
    suspend fun subscriptionErrorTest() = flow{
        val error = DataFetcherResult.newResult<Boolean>().error(
            GraphqlErrorBuilder
                .newError()
                .message("Test an error")
                .build()
        ).build()
        emit(error)
    }.asPublisher()
```

But when I startup I get an error saying that DataFetcherResult<Boolean> is not a valid type.

**Comment by de55** [comment]
In a related question, how can I return any error from a subscription? Currently if I throw an error, it always returns the following:

```
{
  "error": "Could not connect to websocket endpoint ws://localhost:5000/subscriptions. Please check if the endpoint url is correct."
}
```

**Comment by smyrick** [comment]
It appears that [SubscriptionExecutionStrategy](https://github.com/graphql-java/graphql-java/blob/101dc6cfc8dbdf598206868a3e15f6afa0b3bd1d/src/main/java/graphql/execution/SubscriptionExecutionStrategy.java#L24) does not support unboxing of `DataFetcherResult` the same way [ExecutionStrategy](https://github.com/graphql-java/graphql-java/blob/101dc6cfc8dbdf598206868a3e15f6afa0b3bd1d/src/main/java/graphql/execution/ExecutionStrategy.java#L296) does.

So this will need to be a feature request back to graphql-java

**Comment by smyrick** [comment]
It looks like we need to update how we unwrap function return types to double unwrap the `Publisher` type just like we do for `CompletableFutures`

https://github.com/ExpediaGroup/graphql-kotlin/blob/9f0c278d4f33ef8d7e7bef6899627bb9d70b0db8/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/utils/functionReturnTypes.kt#L46

**Comment by smyrick** [comment]
So taking a second look this is in fact an issue with graphql-java still.

Even though `SubscriptionExecutionStrategy` extends the `ExecutionStrategy` which unboxes `DataFetcherResults` it does not pass for subscriptions because the top level type is a `Publisher`. So a issue will need to be opened there instead

**Comment by smyrick** [comment]
Once that is solved in graphql-java we can update our code to generate the correct types for the schema, which we still need to do in here: https://github.com/ExpediaGroup/graphql-kotlin/blob/9f0c278d4f33ef8d7e7bef6899627bb9d70b0db8/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/utils/functionReturnTypes.kt#L41
