### ISSUE TITLE
graphQL query return type does not support custom generic.

### ISSUE THREAD

**Issue by Ncaffeine** [ExpediaGroup/graphql-kotlin#621]
**Library Version**
`com.expediagroup:graphql-kotlin-spring-server:2.0.0-RC6`

**Describe the bug**
i am running a graphQL server. 
this is my test code

`
import com.expediagroup.graphql.hooks.SchemaGeneratorHooks
import com.expediagroup.graphql.spring.operations.Query
import graphql.Scalars
import graphql.schema.GraphQLInputObjectField
import graphql.schema.GraphQLInputObjectType
import graphql.schema.GraphQLType
import org.springframework.stereotype.Component
import kotlin.reflect.KType

@Component
class GenericQuery : Query {

    fun getWidgetValue(widget: Widget<Long>): Long {
        return widget.value
    }

}

data class Widget<T>(val value: T)

@Component
class CustomSchemaGeneratorHooks : SchemaGeneratorHooks {

    override fun willGenerateGraphQLType(type: KType): GraphQLType? = when (type.classifier) {
        Widget::class -> createWidgetGraphQLType(type)
        else -> null
    }

    fun createWidgetGraphQLType(type: KType): GraphQLType {
        return GraphQLInputObjectType
            .newInputObject()
            .name("WidgetInput")
            .field(
                GraphQLInputObjectField.newInputObjectField()
                    .name("value")
                    .type(Scalars.GraphQLString)
                    .build()
            ).build()
    }

}
`

**To Reproduce**
when i query
`
query {
    getWidgetValue(
        widget: {
            value: "foo"
        }
    )
}
`

i got error info: 
`
java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
  at com.expediagroup.graphql.generator.extensions.KParameterExtensionsKt.javaTypeClass(kParameterExtensions.kt:43) ~[graphql-kotlin-schema-generator-2.0.0-RC6.jar:2.0.0-RC6]
`

**Expected behavior**
i wanna graphQL server return result:
`
{
  "widget": {
           "value": "1" // string format
   }
}
`

i am read source code, i think error in [kParameterExtensions.kt](https://github.com/ExpediaGroup/graphql-kotlin/blob/18a5f9b6f087fc1b0558b0ebee108e29799d1480/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kParameterExtensions.kt) on 43 line.

i try to fix. it is my demo code.

`
internal fun KParameter.javaTypeClass(): Class<*> = 

    if (this.isList()) { 
         this.type.getKClass().java  

    } else { 

        val javaType = type.javaType 

        if(javaType is ParameterizedType) { 

            javaType.rawType as Class<*> 

        } else { 

            javaType as Class<*> 

        }  

    } 
`

point is generic is myself defined. and i expect specific return value. but just can not cast to target.

**Comment by dariuszkuc** [comment]
GraphQL spec currently does not support generics (see [issue #190](https://github.com/graphql/graphql-spec/issues/190)) so unfortunately we won't be supporting this in the library. We'll add support once the spec supports it.

**Comment by Ncaffeine** [comment]
i mean: i can use generics resolve specific GraphQLType.  i defined willGenerateGraphQLType to resolve GraphQLType. It is not GraphQL generics spec.

**Comment by dariuszkuc** [comment]
You defined `data class Widget<T>(val value: T)` - how is this supposed to be represented in the schema?

In your custom hook you are **manually creating the type** with its input value mapped to `String` which does not match your data class.

Simplest workaround is to create specific `Widget` types -> `WidgetInt(val value: Int)/WidgetString(val value: String)` etc

**Comment by Ncaffeine** [comment]
`Widget<T>` just is a simple example. actually is `Widget<T: model>`. model could be any type. model mapping to other type is not problem. i will use jackson library to customize JsonDeserializer solved.
i think graphql-kotlin need not provide default implement about generics, Should allow programmer customize process  by extends `SchemaGeneratorHooks`

**Comment by Ncaffeine** [comment]
the actually no any side effect generics. can cause cast error.
like this:
`
fun findProduct(product: Product<*>): Product? {
    return null
}

data class Product<T>(val name: String)
`

**Comment by dariuszkuc** [comment]
@Ncaffeine again the underlying problem is that while Kotlin supports generics and you can definitely code whatever, generics currently cannot be represented in GraphQL schema so your Kotlin data model CANNOT be mapped 1:1 to a schema.

**Comment by Ncaffeine** [comment]
> @Ncaffeine再次提出了潜在的问题，尽管Kotlin支持泛型并且您绝对可以编写任何代码，但泛型当前无法在GraphQL模式中表示，因此您的Kotlin数据模型无法以1：1映射到模式。

thank you.
