### ISSUE TITLE
Add automated security reporting

### ISSUE THREAD

**Issue by smyrick** [ExpediaGroup/graphql-kotlin#626]
As brought up in https://github.com/ExpediaGroup/graphql-kotlin/issues/625 we don't have any automated security reporting other than what Github provides. There are many tools that are available for free for open-source projects that we should look into adding into our CI pipeline.

**Note**
We will have to talk with the Expedia Group org admins about what tools we can add and get approval from them.

**Comment by smyrick** [comment]
It was brought up in the above issue that we could use the following gradle plugin.

https://plugins.gradle.org/plugin/org.owasp.dependencycheck

We could run this as a separate job on the CI workflow for every check in

**Comment by androa** [comment]
[Snyk](https://snyk.io/) is a very good SaaS option which is free for open source.

**Comment by dariuszkuc** [comment]
Resolved by https://github.com/ExpediaGroup/graphql-kotlin/pull/1164
