### ISSUE TITLE
Ignored interface fields are still used for subtypes 

### ISSUE THREAD

**Issue by gscheibel** [ExpediaGroup/graphql-kotlin#632]
**Library Version**
What version are you using?
Bug found in 1.x and 2.x

**Describe the bug**
When an interface has a field marked with `@GraphQLIgnore`, the field is still used when generating the subtypes.

**To Reproduce**
```
interface Service {
    val name: String

    @GraphQLIgnore
    val shouldNotBeInTheSchema: Boolean
}

data class WebService(override val name: String, override val shouldNotBeInTheSchema: Boolean = false) : Service
```

**Expected behavior**
The expectation is for the schema to contain an interface `Service` with a single `name` field and an object type `WebService` inheriting `name`.
`shouldNotBeInTheSchema` should neither appear in the interface definition nor in the object one.

**Comment by smyrick** [comment]
Resolved in above issues
