### ISSUE TITLE
List's of custom scalar types no longer work as arguments with Jackson 2.10

### ISSUE THREAD

**Issue by alexsparrow** [ExpediaGroup/graphql-kotlin#635]
**Library Version**
2.0.0-RC10

**Describe the bug**
As noted in https://github.com/ExpediaGroup/graphql-kotlin/issues/518, the behaviour of `convertValue` appears to have changed in Jackson 2.10 so that it no longer short-circuits when the input value is already of a suitable type. 

For my use case, this causes an issue  when a function on my `TopLevelObject` takes a list of non-primitive types e.g. 
```
fun foo(ids: List<UUID>)
```
I have registered `UUID` as a scalar type using `SchemaGeneratorHooks` and defined a suitable `Coercing` for it.

With Jackson 2.9.X, this works as expected.

With Jackson 2.10.X, when I try to query this function, I get an exception like:
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader 'bootstrap')
```

I believe this is due to the usage of `convertValue` in `FunctionDataFetcher.convertParameterValue`. In Jackson 2.10.X the list will always go through a serialization/deserialization step, losing the type information. 

**To Reproduce**
See above.

**Expected behavior**
Expect the `List<UUID>` to be forwarded as-is to my function.

Thanks for any help :-)

**Comment by smyrick** [comment]
@alexsparrow Can you verify that you can run #636 locally? I checked out from the master branch I am not seeing any errors and we are running on jackson 2.10.2

**Comment by alexsparrow** [comment]
Hey @smyrick thanks for the response and the tests! I left a couple of comments on your PR.

I don't think I'm running groovy (and definitely for the code that's causing the error).

**Comment by smyrick** [comment]
@alexsparrow Ah, yes. I see now. It seems that we lose the information for converting custom scalars. We only added support for lists as input types in this PR: https://github.com/ExpediaGroup/graphql-kotlin/pull/546

If you change the type to `Array<UUID>` then it should work. I will investigate why Lists are not working.

**Comment by smyrick** [comment]
@alexsparrow I found the issue. It was infact in `FunctionDataFetcher`. I updated my PR to include the bug fix

**Comment by alexsparrow** [comment]
Awesome thanks a lot for looking into this. The bug fix looks good and the workaround with `Array` is handy in the meantime.

**Comment by smyrick** [comment]
Fixed in https://github.com/ExpediaGroup/graphql-kotlin/pull/636
