### ISSUE TITLE
Blocking problem of graphql-kotlin with DataLoader&BatchLoader

### ISSUE THREAD

**Issue by babyfish-ct** [ExpediaGroup/graphql-kotlin#638]
I met a problem when I learn this framework_(I also asked this question on stackoverflow: https://stackoverflow.com/questions/60694291/blocking-problem-of-graphql-kotlin-with-dataloaderbatchloader)_

------------------------------------------------------------------------------------

Description:

I used DataLoader&BatchLoader to resolve the 'N+1' loading problem.

When the scope of DataLoader objects is singleton, it works, but it's not my goal because temporary cache mechanism should not be bridging over different requests.

Then I changed the scope of DataLoader objects to be prototype, in all probability, the graphql query may be blocking and associatied objects will not be loaded, client waits the reponse forver.

What's the reason and how can I resolve it?

------------------------------------------------------------------------------------

All the source code in the attachment:
~[kotlin-graphql.zip](https://github.com/ExpediaGroup/graphql-kotlin/files/4334522/kotlin-graphql.zip)~

------------------------------------------------------------------------------------
Build & Run

1. Execute this quey, result may be success or failed
```
{
  employees {
    id
    name
    department {
      id
      name
      employees {
        id
        name
      }
    }
  }
}
```

2. If it is success, the client can get the response, and the server log is
```
2020-03-15 22:47:26.366  INFO 35616 --- [onPool-worker-5] org.frchen.dal.DepartmentRepository      : BatchLoad departments by ids: [1, 2]
2020-03-15 22:47:26.367  INFO 35616 --- [onPool-worker-5] org.frchen.dal.EmployeeRepository        : BatchLoad employees by departmentIds: [1, 2]
```
3. If it is failed, the client is blocking and wait for the reponse forever, and the server log is
```
2020-03-15 22:53:43.159  INFO 35616 --- [onPool-worker-6] org.frchen.dal.DepartmentRepository      : BatchLoad departments by ids: [1, 2]
```

**Comment by smyrick** [comment]
Hello, instead of a zip file can you please include a link to a branch or separate repo on Github that we can inspect to look at the code

Also there is an example DataLoader usage checked in with this PR: https://github.com/ExpediaGroup/graphql-kotlin/pull/396

**Comment by babyfish-ct** [comment]
Hello smyrick, thanks for your reply, I've uploaded my project to github, the link is
"https://github.com/babyfish-ct/graphql-kotlin-dataloader-example"

**Comment by babyfish-ct** [comment]
I've found the reason, I'll delete the that project and close this issue
