### ISSUE TITLE
JPA Repository to fetch data for a property

### ISSUE THREAD

**Issue by sirhallt** [ExpediaGroup/graphql-kotlin#647]
Referencing this page:

https://expediagroup.github.io/graphql-kotlin/docs/execution/fetching-data 

If I wanted to use a JPA Repository for pulling back related data to an object as a function, how would you recommend doing so? Is there an example of this function?

Thank you

**Comment by dariuszkuc** [comment]
GraphQL specification does not dictate where or how to get the data that is exposed through the schema. It is up to the developer to decide what data source to use (which can be some database, file system, another service, combination of multiple data sources etc).

`graphql-kotlin-schema-generator` auto generates the schema based on provided data model, so as long your queries expose the objects returned from your JPA repository (i.e. they could simply run your CRUD repositories) it should work as is. Unsure if there is a reactive JPA lib so you might need to wrap those calls in some coroutines to avoid blocking calls but that is up to you.

NOTE: In general I would avoid exposing your database data directly through a schema as that will most likely result in in a sub-optimal schema.

**Comment by dariuszkuc** [comment]
See also https://github.com/ExpediaGroup/graphql-kotlin/issues/630
