### ISSUE TITLE
Failing when operationName is null or doesn't exist

### ISSUE THREAD

**Issue by nickgieschen** [ExpediaGroup/graphql-kotlin#658]
**Library Version**
What version are you using?

2.1.0

**Describe the bug**

I'm using this in a Ktor app. When I use Gson as my JSON library, everything works fine. When I switch to Jackson, I get the following error when I set operationName=null or don't send operationName. If I set operationName to "", then everything works fine. Given operationName is optional, shouldn't it be a nullable type?

com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class foo.config.GraphQLRequest] value failed for JSON property operationName due to missing (therefore NULL) value for creator parameter operationName which is a non-nullable type

**To Reproduce**
Steps to reproduce the behavior. Please provide:
- Schema Configuration
- Kotlin code used to generate the schema

**Expected behavior**

**Comment by dariuszkuc** [comment]
Can you provide more details on your setup? 

If you are using ktor I'm assuming you are only using schema generator which just generates the schema and all the runtime configuration is part of your app. Error implies that your request object (`foo.config.GraphQLRequest`) is invalid and your data class specifies `operationName` as not null -> e.g. https://github.com/ExpediaGroup/graphql-kotlin/blob/master/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLRequest.kt#L23. Maybe you just need to include https://github.com/FasterXML/jackson-module-kotlin?

**Comment by nickgieschen** [comment]
Ahh, I see. For some reason I thought the GraphQLRequest was a graphql-kotlin class and not one I created.
