### ISSUE TITLE
How to implement cursor based pagination?

### ISSUE THREAD

**Issue by alchemistgo87** [ExpediaGroup/graphql-kotlin#660]
Can someone help me to implement cursor based pagination using mongo (or SQL) database.

**Comment by smyrick** [comment]
This is specific question about your server implementation, and not about running a GraphQL server. This library is not concerned with how your data is stored or accessed, we just generate the schema and expose it through and HTTP server.

As for what a pagination schema might look like in GraphQL, you can take a look at the official examples in graphql.org: https://graphql.org/learn/pagination/#pagination-and-edges

I am going to close the issue to keep our issues clear, but if anyone else has comments feel to continue the discussion here for others to find later.

Related: https://github.com/ExpediaGroup/graphql-kotlin/issues/662
