### ISSUE TITLE
How to fetch only those fields which are requested by apis?

### ISSUE THREAD

**Issue by alchemistgo87** [ExpediaGroup/graphql-kotlin#662]
To use graphql in its full potential, it would be a good practice to fetch only those fields from the database, which are required by the graphql api. So, what would be the correct (and easy) way to implement this?

**Comment by dariuszkuc** [comment]
GraphQL specification does not dictate which datasource is used to retrieve the data. It could be a database but it doesn't have to. When you use `graphql-kotlin-schema-generator` it will automatically generate GraphQL schemas from the underlying Kotlin data model. How you populate the data returned by the GraphQL queries it is up to the developer to decide. Clients will only receive the data they requested but depending on how you expose it the complete dataset _might_ be fetched every time (e.g. see the difference between exposing a field through a property and function described in our [wiki](https://expediagroup.github.io/graphql-kotlin/docs/execution/fetching-data)).

When executing queries you also have an option to explicitly access the `DataFetchingEnvironment` that contains all information about the query which you can use to trigger some custom logic. See https://expediagroup.github.io/graphql-kotlin/docs/execution/data-fetching-environment and https://github.com/ExpediaGroup/graphql-kotlin/issues/630 for additional details.

**Comment by smyrick** [comment]
I am going to close the issue to keep our issues clear, but if anyone else has comments feel to continue the discussion here for others to find later.
