### ISSUE TITLE
Subscriptions keeps opened while Flux is completed

### ISSUE THREAD

**Issue by gaerfield** [ExpediaGroup/graphql-kotlin#665]
**Library Version**
2.1.0

**Describe the bug**
Subscriptions are not completed on server-side when the underlying stream (Flux or Publisher) has no more date to send.

**To Reproduce**
Given the following Subscription:
```kotlin
@Component
class TestSubscriptions(): Subscription {
    suspend fun intsAsPublisher() = flowOf(1,2,3).asPublisher()
    suspend fun intsAsFlux() = flowOf(1,2,3).asFlux()
}
```
and additionally a Hook-Implementation just echoing some info:
```kotlin
@Bean
fun apolloSubscriptionHooks(): ApolloSubscriptionHooks = object : SimpleSubscriptionHooks() {
  override fun onOperationComplete(session: WebSocketSession): Mono<Unit> {
    println("Operation is complete")
    return super.onOperationComplete(session)
   }
  // etc.
}
```
The following unit-test will never end (adapted from [SimpleSubscriptionIT.kt](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/examples/spring/src/test/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscriptionIT.kt)):
```kotlin
    @Test
    fun `verify singleValueSubscription query`() = runBlocking {
        val query = "intsAsFlux"
        val subscription = subscribe(query, "1", 1000L)

        subscription.collect { it -> println("$it") }
    }
```
The Unit-Test prints and then hangs waiting for more data:
```
Somebody connected
Something happened
{"data":{"intsAsFlux":1}}
{"data":{"intsAsFlux":2}}
{"data":{"intsAsFlux":3}}
```
This behaviour is the same, when using [Altair](https://altair.sirmuel.design/) or the built-in GraphQL-Client.

Calling the implementation directly runs fine:
```kotlin
    @Test
    fun intsAsFlux() = runBlockingTest {
        sut.intsAsFlux()
                .doOnCancel { println("canceled") }
                .doOnComplete { println("completed") }
                .doOnError { th -> println("error ${th.javaClass}: ${th.message} ") }
                .doOnEach { println("each $it") }
                .collect { println("item $it") }
    }
```
It prints and then finishes:
```
each doOnEach_onNext(1)
item 1
each doOnEach_onNext(2)
each doOnEach_onNext(3)
completed
each onComplete()
item 2
item 3
```

**Expected behavior**
When the underlying Stream (Flux or Publisher) has ended, I would expect that:
* `onOperationComplete` is issued
* the server terminates the WebSocket-Connection

**Comment by smyrick** [comment]
This is part of the Apollo subscriptions transport specification that we are implementing:  https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md

> When client done with executing GraphQL, it should close the connection and terminate the session using GQL_CONNECTION_TERMINATE message.

This means that the client is the one that has to terminate the connection, even if there is no more data coming for a specific GraphQL operation. This means that clients can start executing a new operation without having to go through another session initialization.

-------

We decided to implement this specification for GraphQL subscriptions as it is fairly popular in the GraphQL community. However the GraphQL spec does not dictate how subscriptions should communication, so you are free to use your own custom behaviour on your servers and clients.

**Comment by gaerfield** [comment]
Ok, i missed this detail in Specification. In this case, shouldn't the server throw an UnallowedOperationException or something? Because with subscriptions, the server is not able to terminate the subscription and ending a flux is simply not possible.

For queries or mutations on the other hand, it is [allowed](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_complete) to terminate flux:
The [protocol] states:
> GQL_COMPLETE
>
> Server sends this message to indicate that a GraphQL operation is done, and no more data will arrive for the specific operation.
>
>    id: string : operation ID of the operation that completed

The [example](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#connected-phase) says this also:
> Server sends GQL_COMPLETE if the operation is a query or mutation (for subscriptions, this sent when unsubscribing)

As I tried to implement this behaviour, the resulting sdl looks like:
```
type Query {
  intsAsFlux: Int!
}
```
And it fails with:
```
Can't serialize value (/intsAsFlux) : Expected type 'Int' but was 'FlowAsFlux'
```

Is this behaviour intended?

**Comment by smyrick** [comment]
Yes, it is. graphql-java only allows `Publishers` for subscriptions and we map `Flow` and `Flux` for you but we expect queries and mutation to have only the [supported wrapper classes](https://expediagroup.github.io/graphql-kotlin/docs/execution/async-models). We do not unwrap a `Flux` as it doesn't make sense to have a `Flux` when a query is only going to return a single response. It would be better to use a `Mono` in this case

We are only using this protocol for subscriptions as we do not have support for queries and mutations over websockets.

**Comment by gaerfield** [comment]
Ok, thanks for clarification.
