### ISSUE TITLE
SDL including a regular expression in a GraphQLDescription since 2.0.0

### ISSUE THREAD

**Issue by mervyn-mccreight** [ExpediaGroup/graphql-kotlin#666]
Did something major change when generating the schema returned by:
```
query { 
  _service { 
    sdl 
  } 
}
```

I'm using graphql-kotlin in a service together with https://github.com/apollographql/apollo-server/tree/master/packages/apollo-gateway to combine multiple graph-ql endpoints into a single endpoint.

When I try updating from '1.4.2' -> '2.1.0' the apollo-gateway states that the generated schema is illegal. I already tried downgrading to 2.0.0, but that did not help.

I did a comparison and noticed, that beforehand the descriptions in the schema were surrounded by `#` and now they are surrounded with quotes `"`.

The problem only occurs, when I have `Regex::pattern`-strings which include escape symbols in my GraphQLDescriptions. One example for a value in a `GraphQLDescription`-annotation that leads to this behaviour is: 
```
"Should match pattern: `^\+[1-9]\d{7,14}$`"
```

The error reported by the gateway is e.g.:
```
"Encountered error when loading service at http://localhost:8080/graphql: Syntax Error: Invalid character escape sequence: \\+."
```

Is it possible that the data returned from the  `query { _schema { sdl } }` is invalid when there are regular expression patterns including escape symbols in a description?

**Comment by dariuszkuc** [comment]
Per `graphql-java` using `#` for your comments is a deprecated behavior and they updated their logic to use string literals (see [link](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/idl/SchemaPrinter.java#L216)). Currently we do not encode/escape any of the special characters in the comments which could result in the above issue.

Depending on how many of those troublesome comments you have in your code base, one potential workaround is to manually update your comments to properly encode them.

**Comment by mervyn-mccreight** [comment]
Hi @dariuszkuc - thanks for the quick answer 👍 

Unfortunately manually escaping the descriptions leads to inconsistencies between the `_service`-query and the `__schema`-query.

First:
```
query { 
  _service { 
    sdl 
  } 
}
```
needs the manual "doubled" escaping.

and the 
```
query {
  __schema {
    { ... }
  }
```
seems to be doing it by itself.

If I manually escape the troublesome comments in my codebase, the `__schema`-query will return the descriptions with a doubled escape, which is inconsistent.

Maybe it might be a possible temporary workaround to enable the deprecated `#`-description printing of `graph-ql`-java using the `Options::descriptionsAsHashComments` just as long as this is fixed. I had a look and there seems to be no easy way to change the options for the `SchemaPrinter` used by `graphql-kotlin-federation` - or am I missing something? 🤔

**Comment by dariuszkuc** [comment]
The underlying issue is due to a bug in how we print out SDL - basically if you have escape characters they will be printed out in nicely formatted String intended for output. This unfortunately leads to invalid SDL as those comments will no longer be valid Strings. You can see the issue in the SDL that gets printed out at the startup.

Federation relies on custom `sdl` String which suffers from the same. I think the simplest fix is to explicitly escape the special characters when printing out SDL -> see https://github.com/ExpediaGroup/graphql-kotlin/pull/678
