### ISSUE TITLE
Is it possible to return GraphQL ID from a query/mutation?

### ISSUE THREAD

**Issue by danbim** [ExpediaGroup/graphql-kotlin#668]
I couldn't find a way to generate a Schema that has functions returning `ID` types. While this works for arguments it seems it does not for return types, here I could only chose `String`.

Taking a quick look into the generator code base [1] it seems in fact that return type is not in any way evaluated if it could be an `ID`.

Would be happy to help/contribute :)

[1] https://github.com/ExpediaGroup/graphql-kotlin/blob/81c00d55c2152ef6778ac4d1708143c2878598d1/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateFunction.kt#L53

**Comment by dariuszkuc** [comment]
Great question! Currently we are relying on `@GraphQLID` annotation to determine whether given scalar field is of an `ID` type. While you can return complex objects with an `ID` field (e.g. https://expediagroup.github.io/graphql-kotlin/docs/writing-schemas/scalars#id) it appears that currently we do not support returning just raw `ID` by itself. With the current mechanism I am unsure whether we can easily support it. 

Feel free to open up a new bug report that describes this issue. Contributions are also always welcome!

**Comment by dariuszkuc** [comment]
Actually it is a very simple fix. I'll create a PR in a bit.

**Comment by danbim** [comment]
Thanks for the quick fix! That's exactly the solution I had in mind :)
