### ISSUE TITLE
Custom GQL Context not created when endpoint called with trailing slash

### ISSUE THREAD

**Issue by imberda** [ExpediaGroup/graphql-kotlin#672]
**Library Version**
1.4.2

**Describe the bug**

When the `graphql.endpoint` is configured as `/graphql` and a request is made to `/graphql/` (note the trailing slash), the request is handled by the route but the context is not generated nd added into the reactor subscriber context by `ContextWebFilter`.

This is because the route matches based on:
```
POST(config.endpoint)
```
Which is boils down to (something like):
```
PathPatternParser().parse("/graphql")
```
The `PathPatternParser` is automatically configured with `matchOptionalTrailingSeparator = true`, so a request such as `/graphql/` will be matched.

On the other hand the `ContextWebFilter` simply performs:
```
open fun isApplicable(path: String): Boolean = graphQLRoute.equals(path, ignoreCase = true)
```

**To Reproduce**
- Configure the graphql.endpoint to `/graphql`
- Make a request to `/graphql/`
- See that the context factory is not called to generate context

**Expected behavior**

The expected behaviour is that if the request is handled by the query handler, the context generator is called. 

There's likely different ways to solve this, but the most simple seems to be to enhance the `isApplicable` method in `ContextWebFilter`.

Perhaps some improved version of:
```
PathPatternParser().parse(enforceAbsolutePath(config.endpoint)).matches(PathContainer.parsePath(exchange.request.uri.path)
```

**Comment by smyrick** [comment]
@imberda Thank you for raising the issue. This is a quick fix that I have provided in https://github.com/ExpediaGroup/graphql-kotlin/pull/673

If you can not wait for the library to be published the web filter is an open class and you can override the behaviour in `isApplicable` today.

**Comment by imberda** [comment]
The fix looks good to me. Thanks for responding 👍
