### ISSUE TITLE
Exception thrown from ExecutionResult.toGraphQLResponse() when error has null locations

### ISSUE THREAD

**Issue by imberda** [ExpediaGroup/graphql-kotlin#675]
**Library Version**
1.4.2 (but I think this also applies to 2.x)

**Describe the bug**

When a `GraphQLError` is return within the `ExecutionResult`,  extension function `ExecutionResult.toGraphQLResponse()` processes the  errors. Specifically this piece of code:
```
fun ExecutionResult.toGraphQLResponse(): GraphQLResponse {
    val filteredErrors = if (errors?.isNotEmpty() == true) {
        errors.map {
            when (it) {
                is SimpleKotlinGraphQLError -> it
                is Exception -> SimpleKotlinGraphQLError(exception = it, locations = it.locations, path = it.path, errorType = it.errorType)
                else -> it
            }
        }
    } else null
   ...
}
```
If one of the  `GraphQLError`s is an `Exception` the second branch of the `when` statement is evaluated. However, some errors return`null` from the `getLocations()` method. When the `null` is set into the  non-null `locations` property of  the`SimpleKotlinGraphQLError`, this results in an exception being thrown:
```
java.lang.IllegalStateException: it.locations must not be null
```

**To Reproduce**
- Define any simple schema
- Send a request which contains a field within an input type that does not exist within the schema
- This will cause a `InputMapDefinesTooManyFieldsException` (which returns `null` for `getLocations()`
- You will see the error contains this:
```
{
  "errors": [
    {
      "locations": [],
      "path": null,
      "errorType": "DataFetchingException",
      "extensions": {},
      "message": "Exception while fetching data () : it.locations must not be null"
    }
  ]
}
```

**Expected behavior**
The expected response would be something like this:
```
{
  "errors": [
    {
      "locations": [],
      "path": null,
      "errorType": "ValidationError",
      "message": "Exception while fetching data () : The variables input contains a field name 'foo' that is not defined for input object type 'ExampleInput' ",
      "extensions": {}
    }
  ]
}
```

As `GraphQLError` is a platform type we can't be sure if `getLocations()` will return a null. There seems to be two solutions, either replace `null` with an empty list (`it.locations.orEmpty()`) or change `SimpleKotlinGraphQLError.locations` to accept nulls.

**Comment by dariuszkuc** [comment]
Thanks for raising this. Indeed this was missed as in majority of cases `locations` information will be available. If `locations` are unavailable we shouldn't be populating it. I created https://github.com/ExpediaGroup/graphql-kotlin/pull/677 to fix this.
