### ISSUE TITLE
Properties sorting on generated schem

### ISSUE THREAD

**Issue by maespinoza** [ExpediaGroup/graphql-kotlin#689]
It looks like the current implementation reads kotlin files and creates the corresponding properties in the graphql schema correctly. However, the order of the properties is in alphabetical order and not in the order of the defined kotlin files. If we then want to generate code from the generated SDL (lets say clients that want to use your service) it will be also in alphabetical order which might not be the best way from the business perspective. Is it possible to configure the way the schema is generated? Currently we use the toSchema function and then call .print() is there another way to generate the schema without passing through GraphQLSchema object so that we can preserve the order on the original kotlin files?

**Comment by smyrick** [comment]
A GraphQL schema is not sorted in anyway and exposing this order doesn't seem like something that truly provides business value, but is instead leaking implementation details. If there is some reason for an order of fields you should probably return something in a list of objects so you can order them server side or use directives or descriptions to mark any additional metadata about the schema.

**Comment by smyrick** [comment]
However, the schema generator just returns a `GraphQLSchema` object so once you have that you could create a custom implementation of the [SchemaPrinter](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/idl/SchemaPrinter.java) and print the output in any way you want.

**Comment by smyrick** [comment]
I am going to close this issue but feel free to continue the discussion here or in our Slack channel: https://github.com/ExpediaGroup/graphql-kotlin#-contact
