### ISSUE TITLE
Broken CI build is probably the raison why it is impossible get gradle dependencies

### ISSUE THREAD

**Issue by jiraguha** [ExpediaGroup/graphql-kotlin#693]
**Library Version**
`2.1.1`

**Describe the bug**
Gradle cannot find 
- the plugin `com.expediagroup.graphql`
- the lib `com.expediagroup:graphql-kotlin-client:2.1.1`
- probably other stuff

**To Reproduce**
CI in dictators are red:
![image](https://user-images.githubusercontent.com/13137698/81266517-266c5b00-9045-11ea-825e-991f5974cb46.png)
![image](https://user-images.githubusercontent.com/13137698/81266903-e48fe480-9045-11ea-8192-63e1931fcb6c.png)

**Expected behavior**
CI tags to be green 

Thx. Please help

**Comment by smyrick** [comment]
Hello @jiraguha .

We have just merged this package into the master branch so we have not run a release yet. It also has not been officially released so if you are looking for a fully-featured GraphQL client you may want to checkout [apollo-android](https://github.com/apollographql/apollo-android) (it can be used outside of android in any jvm)

That being said we just released 3.0.0-RC1 which should publish the new package and plugins if we set up everything correctly: https://github.com/ExpediaGroup/graphql-kotlin/releases/tag/3.0.0-RC1

**Comment by jiraguha** [comment]
Thx man :-)

**Comment by dariuszkuc** [comment]
[3.0.0-RC2](https://github.com/ExpediaGroup/graphql-kotlin/releases/tag/3.0.0-RC2) was published but since it's publishing new Gradle plugin it may take few days for it to be approved and available in Gradle plugin portal.
