### ISSUE TITLE
Implement the star-wars example app

### ISSUE THREAD

**Issue by smyrick** [ExpediaGroup/graphql-kotlin#695]
**Is your feature request related to a problem? Please describe.**
Our documentation and example apps have lots of content but can be a little bit cluttered as they also contain an example of every single feature available in graphql-kotlin libraries.

**Describe the solution you'd like**
Create a small, concise example of a "real world" app. We don't need to include all the features available but a focused example may be a better starting off point for new devs.

**Additional context**
The existing [swapi-graphql](https://github.com/graphql/swapi-graphql) app is a popular reference point for other GraphQL implementations. We could add a new star-wars example [here](https://github.com/ExpediaGroup/graphql-kotlin/tree/master/examples).

**Comment by dariuszkuc** [comment]
Isn't that's the purpose of [examples](https://github.com/ExpediaGroup/graphql-kotlin/tree/master/examples)?

**Comment by smyrick** [comment]
It has been a while since I looked at our examples as a whole and not just in the sense of adding one specific feature. 

I actually think that the spring example is pretty clear and the folder structure is self documenting

https://github.com/ExpediaGroup/graphql-kotlin/tree/master/examples/spring/src/main/kotlin/com/expediagroup/graphql/examples

I am going to close this issue then but for anyone else that finds this our docs are always open for external contribution as we do our best to write down what we know but sometimes that is not always clear to someone from the outside who isn't a maintainer of this library. 

We can also link to any external example apps or demos you make using our library.
