### ISSUE TITLE
Using ObjectMapper to determine GraphQL type

### ISSUE THREAD

**Issue by VincentHoang** [ExpediaGroup/graphql-kotlin#721]
Hello,

I currently have a data class with a field of type java.Instant for my Query, but says that it is not a valid GraphQL type. How do I make it so the GraphQL type of 'createdAt' become String or perhaps a Long?

```
data class Task(
        val id: String,
        val title: String,
        val createdAt: Instant,
)

@Component
class TaskQuery : Query {
    fun tasks(): List<Tasks> {
        ...
    }
}
```

I thought if I override the spring ObjectMapper by adding the JavaTimeModule it would work:

```
@Bean
fun objectMapper(): ObjectMapper {
    val mapper: ObjectMapper = Jackson2ObjectMapperBuilder().build()
    mapper.registerModule(JavaTimeModule())
    return mapper
}
```

Have I completely misunderstood the way this works?

Thanks,

Vincent

**Comment by smyrick** [comment]
@VincentHoang If you want to create a custom sclar, where `Instant` is treated as a scalar value just like string, you can do that with the hooks. See the docs on [Custom Scalars](https://expediagroup.github.io/graphql-kotlin/docs/writing-schemas/scalars#custom-scalars)

However, keep in mind that you will probably have to still use your custom object mapper when you implement the corercing logic from `String` to `Instant` and clients also have to know what format the string should be in to be `Instant` compatible. While this certainly can be done, this is a hot topic on schema design on how custom you make your types, or would you rather expose some custom type, or just use a string that has the data needed to create an "Instant" in all languages (JS, Kotlin, Swift, ...)

```graphql
type Task {
  id: String
  customInstant: Instant # Custom type
  stringInstant: String # ISO-8601 representation
}

type Instant {
   epochMili: String
   timezone: String
}

**Comment by VincentHoang** [comment]
If I want the schema to look like this 
```
type Task {
  id: String
  createdAt: String # ISO-8601 representation
}
```
I would still need to use hooks?

**Comment by dariuszkuc** [comment]
If you want to expose a field as `String` then no you don't have to use any hooks but this will also mean that you don't need any custom serialization/deserialization logic as String is a built-in scalar.

**Comment by smyrick** [comment]
Yep, no need to expose the `Instant` in that case or use hooks.

```kotlin
data class Task(
    val id: String,
    val title: String,
    @GraphQLDescription("ISO-8601 representation of Java Instant")
    val createdAt: String,
)

@Component
class TaskQuery : Query {
    fun tasks(): List<Tasks> = listOf(Task("id", "title", Instant.now().toString()))
}
```
