### ISSUE TITLE
[client] OperationName should not be capitalized

### ISSUE THREAD

**Issue by androa** [ExpediaGroup/graphql-kotlin#756]
I'm having an issue where the GraphQL API (which uses [graphql-java](https://github.com/graphql-java/graphql-java)) breaks [because the `operationName` is capitalized](https://github.com/ExpediaGroup/graphql-kotlin/blob/61fb764bf0864b114026a1c19d5e24b4dcd57904/plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGenerator.kt#L84) in the generated client.

I can find no reason for the `operationName` to be capitalized in the recent GraphQL spec, so this is probably not the correct behaviour?

https://github.com/ExpediaGroup/graphql-kotlin/blob/61fb764bf0864b114026a1c19d5e24b4dcd57904/plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGenerator.kt#L84

**Comment by dariuszkuc** [comment]
Can you provide some additional details whats breaking? 

We use capitalized `operationName` as the enclosing type name and your API should never know about it. Request will contain operation name (if present) from your actual query that you specified in your `.graphql` file.

**Comment by androa** [comment]
My graphql-file looks like this:

```query hentPerson($ident: ID!) { hentPerson(ident: $ident) { foedsel { foedselsdato } } }```

But the `operationName` in the generated client and what ends up going over the wire is the capitalized version.

**Comment by dariuszkuc** [comment]
Ah! indeed it uses wrong paramater here -> https://github.com/ExpediaGroup/graphql-kotlin/blob/master/plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGenerator.kt#L113 (it should be using the original operation name from the query file). Thanks for raising this.

**Comment by androa** [comment]
Thank you for a very quick fix! 👍
