### ISSUE TITLE
Directive arguments support @GraphQLIgnore

### ISSUE THREAD

**Issue by oatmeal-raisin** [ExpediaGroup/graphql-kotlin#762]
Creating a new directive with an ignored field will prevent the schema from being generated when the ignored field type is not in the supported packages. Is there a way to prevent this behavior? It seems like a type that is only referred to in an ignored field should not break schema generation even if it is not in the supported packages.

Example in a directive:
```
@GraphQLDirective()
annotation class TestDirective(
        val value: String,
        @GraphQLIgnore
        val ignore: Array<KClass<*>> = [] 
)
```
Results in
`Caused by: com.expediagroup.graphql.exceptions.TypeNotSupportedException: Cannot convert kotlin.reflect.KClass<*> since it is not a valid GraphQL type or outside the supported packages [...]`

Obviously something like kotlin.reflect should not be added to the supported packages and nothing representing KClass should be in the schema.

**Comment by dariuszkuc** [comment]
Currently `@GraphQLIgnore` is applied on GraphQL fields only (i.e. functions and properties), we do not apply it against the directive definitions. 

What's the use case behind hiding some of the directive field values?

**Comment by oatmeal-raisin** [comment]
Thank you for the quick response @dariuszkuc.

The current use case is driven by trying to simplify validation. The goal is to create an annotation that exposes constraint information on the SDL as a directive but can also be used as a javax validation constraint annotation. Constraint annotations have fields that do not make sense to include in directives like "groups" and "payload." 

Given that it is not currently supported, what is the best way to work around the problem of having the field ignored and preventing the type on that field from being pulled in? Is it possible with schema generation hooks?

**Comment by smyrick** [comment]
@oatmeal-raisin One way you could solve the issue right now is to have the two different annotations on your kotlin code, one for the GraphQL information and one for the kotlin execution, or with the hooks it would be possible to modify the generated type before it is added to the schema.

However I think you raise a valid point and there is a place in the library code where we can add the requested feature.

**Comment by dariuszkuc** [comment]
Yeah I think we should support it.

**Comment by oatmeal-raisin** [comment]
Thanks @smyrick and @dariuszkuc. I really appreciate how responsive your team is and I am looking forward to the enhancement. Are there any hooks I can take a look at that do something similar? I will need to both exclude the field and to prevent the type on that ignored field from causing an exception because it is not in the configured packages.

**Comment by smyrick** [comment]
@oatmeal-raisin From what I can tell there is no way to get the argument annotation information from a directive during schema generation unless you know the specific class type. So the best way to solve this is just with the hooks.

See the PR for more details https://github.com/ExpediaGroup/graphql-kotlin/pull/763
