### ISSUE TITLE
Passing unique headers without recreating client

### ISSUE THREAD

**Issue by nutgaard** [ExpediaGroup/graphql-kotlin#764]
I may obviously be missing something here. 

But is there a way of passing headers to `GraphQLClient.execute` when using the autogenerated query-classes?

Usecases may differ, but I need to pass a callId to allow tracking between services, and recreating the client for each request seems a bit redundant.

**Comment by dariuszkuc** [comment]
Recreating client per each request is indeed an unnecessary overhead. I think we can probably expose the underlying Ktor client functionality to configure the headers (see: https://github.com/ExpediaGroup/graphql-kotlin/pull/769).

Currently you can do a workaround with OkHttp engine where you can add custom headers using interceptors (which probably would have to rely on some thread locals).

**Comment by nutgaard** [comment]
Tried looking into it myself when creating the issue, and seems like we came to approx the same solution ( https://github.com/nutgaard/graphql-kotlin/pull/1/files ) 👍 

I exposed `HttpRequestBuilder` insteadof `HeadersBuilder`, but I'm rather new to this library and may be overlooking some trivial reason why that would not work.

In the end I ended up with a workaround similar to what you're describing, though using a ktor-client feature and some coroutine-context black-magic.
