### ISSUE TITLE
getting 404

### ISSUE THREAD

**Issue by rajkumar1979** [ExpediaGroup/graphql-kotlin#770]
Trying to run the simple hello world , getting 404.

**Comment by rajkumar1979** [comment]
```package com.example.graphql

import com.expediagroup.graphql.spring.operations.Query
import org.springframework.stereotype.Component

@Component
class HelloWorldQuery: Query {
    fun helloWorld() = "Hello World!"
}```

**Comment by rajkumar1979** [comment]
```graphql.packages=com.example.graphql
```

**Comment by rajkumar1979** [comment]
```
<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>com.expediagroup</groupId>
			<artifactId>graphql-kotlin-spring-server</artifactId>
			<version>${graphql-kotlin.version}</version>
		</dependency>
```

**Comment by smyrick** [comment]
@rajkumar1979 Have you set up the required `graphql.packages` configuration?

https://expediagroup.github.io/graphql-kotlin/docs/spring-server/spring-overview#configuration

If you need an example you can see the following directory

https://github.com/ExpediaGroup/graphql-kotlin/tree/master/examples

**Comment by dariuszkuc** [comment]
You probably also want to remove `spring-boot-starter-web` dependency (see second paragraph in https://expediagroup.github.io/graphql-kotlin/docs/spring-server/spring-overview).

**Comment by rajkumar1979** [comment]
was able to resolve that by removing the spring dependency and using the in built playground
