### ISSUE TITLE
[plugin] generated client should support default values

### ISSUE THREAD

**Issue by huehnerlady** [ExpediaGroup/graphql-kotlin#781]
**Is your feature request related to a problem? Please describe.**
I am frustrated when I try to mock the client for testing. I love the automatic generation of the kotlin files very much, so would prefer to continue to be able to do that. But when I mock I need to give every single field a value. As it is already marked as nullable I can put null into it, but with kotlin it has to be defined.

**Describe the solution you'd like**
I would like a flag or even a default behaviour, that the nullable fields are generated with a default value of null, so they do not have to be specified when creating a new instance of the generated classes

**Comment by dariuszkuc** [comment]
Hello, thanks for raising this! I agree that plugins should generate classes with default values.

---
That being said, your specific use case can be solved by either using relaxed mocks from `mockk` (i.e. `mockk(relaxed = true)`) or `mockito-kotlin` which has this behavior as default.

**Comment by huehnerlady** [comment]
@dariuszkuc it was more about creating a new instance of the generated query classes than a return of mockito or mockk, so it is irrelevant which project I use, basically if I used it in production code (which would be odd as you should let the client do its thing) you would run into this problem if you wanted to create a new instance :) .  
Once you instantiate a new class with kotlin you have to provide a value for every field that does not have a default value, and that is the problem I am facing here.

**Comment by huehnerlady** [comment]
@dariuszkuc is this anything you put on a roadmap yet? So is there any idea if/when this will be fixed?

**Comment by dariuszkuc** [comment]
Unfortunately we currently don't have any specific timeline for implementing this. I added it to the `4.0.0` for now. PRs are always welcome :)

**Comment by huehnerlady** [comment]
> Unfortunately we currently don't have any specific timeline for implementing this. I added it to the `4.0.0` for now. PRs are always welcome :)

Thanks, I will keep that in mind and see whether I can have a look :)

**Comment by huehnerlady** [comment]
@dariuszkuc I had a look and I find it very difficult to work with as I am not deeply in the code. 
Do you maybe have a code-pointer for me? Is there a generator mechanism that sets default property values already?

**Comment by dariuszkuc** [comment]
We use KotlinPoet to generate Kotlin types from the GraphQL schema objects. All type generators are located under https://github.com/ExpediaGroup/graphql-kotlin/tree/master/plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types.

**Comment by dariuszkuc** [comment]
I've opened up https://github.com/ExpediaGroup/graphql-kotlin/pull/810 to automatically set `null` value for nullable input arguments.

**Comment by huehnerlady** [comment]
@dariuszkuc you are a star, thank you so much :)

**Comment by dariuszkuc** [comment]
change to set default `null` value for nullable input arguments was released in `3.5.0`

**Comment by huehnerlady** [comment]
@dariuszkuc Many thanks for your help. I tried it straight away but unfortunately no default values are generated. Is there a configuration property I have to set to make that work? In your PullRequest I cannot see any Readme changes and unfortunately I did not find anything in this direction

**Comment by huehnerlady** [comment]
@dariuszkuc many thanks. I assume the task will stay open for the GraphQL schema objects and as you mentioned this is a more complex problem I guess will take a while?

OR maybe it is a task in the kotlin-poet library to offer adding default values? 🤔

**Comment by dariuszkuc** [comment]
Yes I've kept the issue open to track support for any default values.

**Comment by huehnerlady** [comment]
@dariuszkuc I had a quick look at poed and is [this information](this information) maybe something you can make use of?

**Comment by dariuszkuc** [comment]
@huehnerlady you did not include the links ;) but underlying issue is not with KotlinPoet and more of a how to unwrap default values of the underlying scalars

**Comment by huehnerlady** [comment]
@dariuszkuc how embarrassing 🙈 
Here is the link now: https://square.github.io/kotlinpoet/#default-function-arguments
I also edited the comment above :) 

Otherwise if there is functionality missing I am happy to ask them to help as much as I am able to without understanding the code 😅

**Comment by huehnerlady** [comment]
@dariuszkuc hi, do you have any update for this?

**Comment by huehnerlady** [comment]
Hi, is there any update for this issue?

**Comment by dariuszkuc** [comment]
Sorry no updates on this.

**Comment by dariuszkuc** [comment]
This is superseded by support for handling optional inputs (https://github.com/ExpediaGroup/graphql-kotlin/issues/1151). Clients should be unaware of the server defaults and instead should simply omit the parameter (i.e. don't specify it in the request) so server would fallback to its defaults.
