### ISSUE TITLE
[client] Generate header value at execution time

### ISSUE THREAD

**Issue by huehnerlady** [ExpediaGroup/graphql-kotlin#784]
Hi,
We currently use the gradle plugin `com.expediagroup.graphql` together with the graphql client.
So far the first tests are very promising.
What I have a problem with at the moment, is to find the possibility to add a header in a similar matter as the spring-httpRequestInterceptors do. I have a token in a header I receive and want to pass it onto my graphqlClient. So far I have the following to create my client:

```
return GraphQLClient(url = url) {
            defaultRequest {
                header("AUTHENTICATION-HEADER", "someToken)
            }
            install(Logging) {
                logger = Logger.DEFAULT
                level = LogLevel.ALL
            }
        }
```

I would like to adapt the token at execution time though. My workaround so far is to create a new graphql client for every execution and set the token then.

What I would like to achieve is to create a graphql client bean, similar to Springs RestOperations, and set some kind of interceptor to create the token at that point.

Any idea how I can achieve that?

**Comment by huehnerlady** [comment]
I can see this was addressed and merged in #764. Is there any estimate when this will be released?

**Comment by smyrick** [comment]
@huehnerlady This has been release in [3.3.0](https://github.com/ExpediaGroup/graphql-kotlin/releases/tag/3.3.0)

**Comment by huehnerlady** [comment]
@smyrick Wow I am impressed, didn't expect it today, more like in a week or so. This is brilliant, many many thanks 👍
