### ISSUE TITLE
Validate packages property

### ISSUE THREAD

**Issue by LarsKoelpin** [ExpediaGroup/graphql-kotlin#791]
**Is your feature request related to a problem? Please describe.**
I just wasted an hour by figuring out, I made a mistake when configuring the root package.
I set
```
graphql.packages="de.my.app"
```
which looks fine in the application.properties.
When starting the server I was greeted with
```
: Cannot convert de.my.app.Widget? since it is not a valid GraphQL type or outside the supported packages ["de.my.app"]
```
Which exactly tells what's wrong, (with "-beeing present) But not noticted that easliy

After debugging I noticed it shall not be 
```
graphql.packages="de.my.app"
```
But rather be
```
graphql.packages=de.my.app
```
A silly, small mistake with great effect. Which is difficult to debug when using the project the first time.

**Describe alternatives you've considered**
As `"de.my.app"` is not event a valid package name, I'd suggest these get interpreted as `de.myapp` or atleast add a warning to the exception to prevent these mistakes from happening or get them noticed more easily

Greetings

**Comment by smyrick** [comment]
@LarsKoelpin Thanks for raising this request. This issue has happened before so you are not the first person to report this. I think we can add a check before generating the schema to see the the class scan even has any results at all an throw a specific exception.

Similar issue here: https://github.com/ExpediaGroup/graphql-kotlin/issues/710
