### ISSUE TITLE
Federation Requires With List

### ISSUE THREAD

**Issue by senthilsivanath** [ExpediaGroup/graphql-kotlin#803]
Trying to make federation work with list along with requires but i am getting "conflicting class names in schema generation [class com.package.model.Product, class com.package.model.Product]" exception. Any pointers will be helpful.

```kotlin
@KeyDirective(fields = FieldSet("orderId"))
@ExtendsDirective
class Order(
        @property:ExternalDirective val orderId: String,

        @property:ExternalDirective
        val productIds: List<String> = listOf()


) {

     // this is throwing errors 
    @RequiresDirective(fields = FieldSet("productIds"))
    val products : List<Product> = listOf()
}
```

```kotlin
@KeyDirective(fields = FieldSet("productId"))
data class Institution(
     @Id
var productId: String = IdGenerator.getUUID()
)
```

This issue is duplicate of #637 
https://github.com/ExpediaGroup/graphql-kotlin/issues/637

The following example is not available
https://github.com/dariuszkuc/graphql-kotlin/tree/federation_requires_list

**Comment by smyrick** [comment]
Are you using the latest version of the library?

It should have been resolved in this PR: https://github.com/ExpediaGroup/graphql-kotlin/pull/685

**Comment by senthilsivanath** [comment]
Yes. With latest version i m not getting this error any more. 

Federation is working with list and requires.

**Comment by senthilsivanath** [comment]
Working example

```
@KeyDirective(fields = FieldSet("orderId"))
@ExtendsDirective
data class Order(
        @property:ExternalDirective val orderId: String,

        @property:ExternalDirective
        var orderlines: List<Orderline>

) {

    @RequiresDirective(fields = FieldSet("orderlines"))
    suspend fun products(@GraphQLIgnore @Autowired productService: ProductService, after: String): ProductConnection {
        return productService.getInstitutions(orderlines.map{ orderline -> orderline.productId })
    }

}
```
