### ISSUE TITLE
Links in documentation not working

### ISSUE THREAD

**Issue by sashwatp** [ExpediaGroup/graphql-kotlin#812]
I was going through the documentations at https://expediagroup.github.io/graphql-kotlin/docs/getting-started.html. I see that multiple links on this page are not working. For example, "Schema Generator Getting Started" results in 404.

**Comment by dariuszkuc** [comment]
Thanks for raising this. Indeed looks like by cutting the doc version (https://github.com/ExpediaGroup/graphql-kotlin/pull/807)  I broke those links.

**Comment by dariuszkuc** [comment]
This was resolved in https://github.com/ExpediaGroup/graphql-kotlin/pull/814

**Comment by bleege** [comment]
Thank you for fixing this so quickly.  👍
