### ISSUE TITLE
Reuse generated class for same type in schema

### ISSUE THREAD

**Issue by stengvac** [ExpediaGroup/graphql-kotlin#815]
Hello,

I have schema, which use same type multiple times in response.

```
type Limits {
  cash: LimitTO!
  purchase: LimitTO!
}

```
Generated classes do not use same class for all `LimitTO` occurence. See generated classes bellow.

```
 //in SomeMutation 
  data class Limits(
    val cash: SomeMutation.LimitTO,
    val purchase: SomeMutation.LimitTO2
  )

```

There are 2 genered classes `SomeMutation.LimitTO` and `SomeMutation.LimitTO2` instead of 1.

using gradle plugin `id("com.expediagroup.graphql") version "3.4.2"`

**Comment by dariuszkuc** [comment]
Hello! Thanks for raising this but this is the default behavior if in your queries you have different selection sets for the same object (as it can lead to weird behavior when first selection requires non-nullable field that is not specified in second selection). See https://github.com/ExpediaGroup/graphql-kotlin/pull/760

**Comment by stengvac** [comment]
I see I am not that deep in GraphQL. 

On the other side I think it s possible to implement recognition from provided queries whether generated object can be reused or it needs to generate new one. But it seems to be hard and may break code, because change of query would produce less or more objects. 

So I am closing.
