### ISSUE TITLE
Simplify generateSchema signature 

### ISSUE THREAD

**Issue by smyrick** [ExpediaGroup/graphql-kotlin#818]
**Describe the solution you'd like**
The `generateSchema` has to arguments: `additionalTypes` and `additionalInputTypes`. If we change the signature and use the new public class `AdditionalType` we can make this into one argument

**Describe alternatives you've considered**
We could keep the split arguments and make the `AdditionalType` class internal only

**Additional context**
This change was added here to make it backwards compatible but with a major version we can introduce a breaking change

https://github.com/ExpediaGroup/graphql-kotlin/pull/817

**Comment by smyrick** [comment]
Another option is to move these initial arguments to the `SchemaGeneratorConfig` to keep the `generateSchema` method simple

**Comment by miguelhrocha** [comment]
Hey @smyrick I created a PR for this: https://github.com/ExpediaGroup/graphql-kotlin/pull/825

**Comment by smyrick** [comment]
See comments here: https://github.com/ExpediaGroup/graphql-kotlin/pull/825#issuecomment-670200690
