### ISSUE TITLE
Invalid schema is generated after upgrade: 3.5.1 -> 3.6.0

### ISSUE THREAD

**Issue by xRomZak** [ExpediaGroup/graphql-kotlin#828]
**Library Version**
3.6.0

**Describe the bug**
Generator produces an invalid schema

**To Reproduce**

Dependencies:
- Jackson version 2.11.*
- Kotlin-generator 3.6.0

Kotlin code (source for schema)
```
data class GeoDataInput(
  val tradeLaneIds: List<String>,
  val applyForAll: Boolean,
  val filter: TradeLaneFilterInput?,
  val rfqNum: String
) : ConvertableToJson
```

Invalid schema (with 3.6.0):
```
input GeoDataInput {
  applyForAll: Boolean
  filter: TradeLaneFilterInput
  rfqNum: String
  tradeLaneIds: String
}
```

**Expected behavior**

Valid schema (with 3.5.1):
```
input GeoDataInput {
  applyForAll: Boolean!
  filter: TradeLaneFilterInput
  rfqNum: String!
  tradeLaneIds: [String!]!
}
```

**Comment by smyrick** [comment]
Wow! Not sure how this one got missed! Working on it now
