### ISSUE TITLE
"EmptyQueryTypeException: Invalid query object type" when only exposing a subscription

### ISSUE THREAD

**Issue by itsandreramon** [ExpediaGroup/graphql-kotlin#830]
**Library Version**
3.6.1

**Describe the bug**
Cannot create a Spring Boot server using only a single subscription. I need to provide also a query. Spring Boot crashes with the following exception:

com.expediagroup.graphql.exceptions.EmptyQueryTypeException: Invalid query object type - no valid queries are available

**To Reproduce**
```
@Component
class BookSubscription(
  private val bookService: BookService
) : Subscription {

  @GraphQLDescription("Returns a single book in a non-blocking way")
  fun findBookById(id: Int): Mono<Book> {
    return bookService.findBookById(id)
  }
}
```
**Expected behavior**
Should generate a schema that consists only of one subscription type like this:
```
schema {
  subscription: Subscription
}
```

**Comment by dariuszkuc** [comment]
Root query type is required as per [GraphQL Spec](https://spec.graphql.org/June2018/#sec-Root-Operation-Types).

See https://github.com/graphql/graphql-spec/pull/631 for additional details.

**Comment by itsandreramon** [comment]
Seems really weird to force a root query type if you don't want to support one.
