### ISSUE TITLE
Allow GraphQL properties to be opt-in

### ISSUE THREAD

**Issue by travigd** [ExpediaGroup/graphql-kotlin#833]
**Is your feature request related to a problem? Please describe.**
It would be nice if there was some way to switch GraphQL property registration from opt-out to opt-in.
I'm thinking about the potential security implications of accidentally exposing functions that weren't meant to be wired up to the GraphQL API.

**Describe the solution you'd like**
Add some kind of flag to switch to requiring properties and/or objects to be explicitly opted in to the GraphQL schema. This seems to match more closely to other GraphQL implementations I've seen (including type-graphql for TypeScript and the Facebook Hack implementation). I'd argue that it should be the API default, but I'm not here to die on that molehill.

**Describe alternatives you've considered**
One alternative is to separate the domain objects from the GraphQL objects which has some merits but also involves writing a good bit more code.

**Additional context**
Thanks for maintaining this project!

**Comment by dariuszkuc** [comment]
Hello! Thanks for raising this but we currently don't have any plans on changing the default behavior. 

Changing `schema-generator` to explicit opt-in would require some major rewriter and also would be at odds with one the reasons we created the library in the first place (i.e. simplify development of GraphQL services by eliminating the boilerplate code and allowing users to write their code in similar way they would do with REST APIs). You should be able to achieve similar opt-in behavior through [custom hooks](https://expediagroup.github.io/graphql-kotlin/docs/schema-generator/customizing-schemas/generator-config#schema-generator-hooks) that could verify whether underlying object should be exposed or not. If customization through hooks is insufficient and explicit opt-in is required you could also consider other GraphQL implementations such as https://github.com/leangen/graphql-spqr.

IMHO you should definitely separate your domain objects from the exposed GraphQL objects as that will ultimately lead to a "better" shape of your graph, i.e. your graph should generally be driven by your clients needs and quite often clients need to explicitly process the raw domain data to make it useable.
