### ISSUE TITLE
Add external type to a local union

### ISSUE THREAD

**Issue by gscheibel** [ExpediaGroup/graphql-kotlin#834]
**Current implementation**

Currently graphql union types are created out of the kotlin type hierarchy with an empty interface.
Members of a graphql union are not aware of the relationship meaning it's possible to reference a koltin type coming from a jar for instance and add it to a local union declaration.

With the current implementation as the `Dog` class comes from a jar, it cannot be added as implementation of the `Animal` union.
```kotlin
/**
Type coming from a JAR
*/
data class Dog(name: String)


/**
Type in the service itself
*/
interface Animal

/**
Type in the service itself
*/
data class Fish(color: String): Animal
```

With this example the graphql schema would be:

```graphql
type Dog { name: String! }

union Animal = Fish
type Fish { color: String! }
```

As expected the `Dog` type is not associated to the `Animal` union.

**Workaround**

A possible workaround is to wrap the `Dog` type with a locally managed type `WrappedDog` and add the wrapper to the union.

```kotlin
class WrappedDog(dog: Dog): Animal
```

leading to a graphql schema

```graphql
type Dog { name: String! }
type WrappedDog { dog: Dog! }

union Animal = WrappedDog | Fish
type Fish { color: String! }
```

**Proposed solution**

A new annotation could reference the external types to add to the implementation:

```kotlin
/**
Type coming from a JAR
*/
data class Dog(name: String)


/**
Type in the service itself
*/
@GraphQLUnionExternalReferences( refs = [ Dog::class.java ])
interface Animal

/**
Type in the service itself
*/
data class Fish(color: String): Animal
```

The addition of the annotation would lead to generate the following schema:

```graphql
type Dog { name: String! }

union Animal = Fish | Dog
type Fish { color: String! }
```

**Comment by smyrick** [comment]
@gscheibel How would you return this in Kotlin code though? If you don't control the definition of your `Dog` class then how can you indicate in Kotlin code that you are returning an `Animal` but still return a `Dog` or `Fish`?


i.e. This does not compile
```kotlin
// "External" type whose source code we do not control
@GraphQLExtendUnion(InternalUnion::class)
class ExternalClass(val foo: String)
    
 interface InternalUnion
    
class InternalClass(val bar: String)
    
class Query {
    fun getTypes(): List<InternalUnion> = listOf(ExternalClass("1"), InternalClass("2"))
}
```

**Comment by smyrick** [comment]
It could be possible to return that as a `List<Any>` but then we would require some other feature to indicate the GraphQL type though another annotation and that just seems like a rabbit hole of features.

**Comment by dariuszkuc** [comment]
I believe we could read the classes array from annotation and add them [here](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateUnion.kt#L40).

**Comment by dariuszkuc** [comment]
Nvm we can generate the schema but it won't work with Kotlin code...

**Comment by smyrick** [comment]
We are going to close this as this feature would not easily be handled in the current generator and across multiple services
