### ISSUE TITLE
Ambiguous 500 server error when trying to run subscription

### ISSUE THREAD

**Issue by hawksdoves** [ExpediaGroup/graphql-kotlin#835]
I am using your wonderful graphql-spring-server library and have it up and working for my queries and mutations (tested manually in my local playground) however, I am struggling implementing a simple subscription. When I try and run a subscription within the playground

eg

```

subscription {
  counter
}
```
as defined

```
@Component
class MySubscriptions: Subscription {
    val logger = LoggerFactory.getLogger(MySubscriptions::class.java)

    fun counter(): Flux<Int> = Flux.interval(Duration.ofSeconds(1)).map {
        val value = Random.nextInt()
        logger.info("Returning $value from counter")
        value
    }
}
```
In the playground I get error ``"Could not connect to websocket endpoint ws://localhost:15015/subscriptions. Please check if the endpoint url is correct."`` and on the server I get:

```
ERROR o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler - [5fde5914]  500 Server Error for HTTP GET "/subscriptions"
java.lang.IllegalStateException: No WebSocketServerFactory available
               at org.springframework.util.Assert.state(Assert.java:73)
               Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
               |_ checkpoint ⇢ com.expediagroup.graphql.spring.execution.ContextWebFilter [DefaultWebFilterChain]
               |_ checkpoint ⇢ HTTP GET "/subscriptions" [ExceptionHandlingWebHandler]
Stack trace:
                              at org.springframework.util.Assert.state(Assert.java:73)
                              at org.springframework.web.reactive.socket.server.upgrade.JettyRequestUpgradeStrategy.upgrade(JettyRequestUpgradeStrategy.java:160)
```
I was hoping you might have experienced this before and could point me in the right direction on how to resolve this.

Thanks so much

**Comment by smyrick** [comment]
@hawksdoves Can you see if version https://github.com/ExpediaGroup/graphql-kotlin/releases/tag/4.0.0-alpha.1

helps resolve your issue? It includes this fix: https://github.com/ExpediaGroup/graphql-kotlin/pull/845
