### ISSUE TITLE
kParameterExtensions::isListType doesn't work for inherited mutation class

### ISSUE THREAD

**Issue by chinshaw** [ExpediaGroup/graphql-kotlin#840]
**Library Version**
3.6.1 although I think all builds in July 2020 may exhibit this error.

I tested 3.3.0 and this issue does not occur.

I traced the issue back to commit [801](https://github.com/ExpediaGroup/graphql-kotlin/pull/801/files) in file .../expediagroup/graphql/generator/extensions/kParameterExtensions.kt 

**Describe the bug**
I created a generic resolver class for Mutations but it is able to decipher the method parameter after change in commit 801.

```
abstract class BaseMutationResolver<T>(private val repository: PagingAndSortingRepository<T, Long>): Mutation {

    @GraphQLDescription("modifies passed in widget so it doesn't have null value")
    fun save(entity: T): T = repository.save(entity)
}

@Component
class UserMutation(@Autowired val repository: UserRepository) : BaseMutationResolver<User>(repository)
```

When attempting to decipher the parameter you will get an error about the TypeVariableField cannot be converted to class. This occurs when the base class's type argument is cast to java Class<*> with in kParameterExtensions this.type.getJavaClass().

.../expediagroup/graphql/generator/extensions/kParameterExtensions.kt

```
// Type cast exception occurs with this.type.getJavaClass
internal fun KParameter.isListType() = this.isList() || this.type.getJavaClass().isArray
```

The calling function that rethrows the exception is generateArgument.
```
private fun getUnwrappedClass(parameter: KParameter): KClass<*> =
    if (parameter.isListType()) {
        parameter.type.getWrappedType().getKClass()
    } else {
        parameter.type.getKClass()
    }
```

**Comment by dariuszkuc** [comment]
We don't support generics as GraphQL spec does not support generics (https://github.com/ExpediaGroup/graphql-kotlin/issues/292) so I'm somewhat surprised that it might have worked in the past (afaik it never worked due to the type erasure).

**Comment by chinshaw** [comment]
Ah yes, I was attempting to create a parent class but I didn't think about all inheriting classes having the same graphql function names. It makes sense that I will need to create distinct method names for each of the class methods.
