### ISSUE TITLE
Problem when executing query from a generated client

### ISSUE THREAD

**Issue by angelu25** [ExpediaGroup/graphql-kotlin#854]
I would like to have a spring GraphQL Kotlin server which is also reaching info from a remote GraphQL.
For that, I introduced the client
implementation("com.expediagroup:graphql-kotlin-client:3.6.1")

I can introspect the schema, generate the client, but when executing, a 500 is being returned:

![image](https://user-images.githubusercontent.com/6308120/91705803-c2364f80-eb7d-11ea-8aa1-815e8163eaeb.png)

![image](https://user-images.githubusercontent.com/6308120/91705838-cf533e80-eb7d-11ea-8064-7606ad05c646.png)

Does anyone know why is this issue happening?

**Comment by dariuszkuc** [comment]
`NoSuchMethodError` generally implies some mismatch on your dependencies - it is most likely pulling in multiple versions of  some library and at runtime it uses incompatible one.

Check your dependency trees to see what sort of conflicts you are getting:

```shell
# using Maven dependency plugin tree goal
> mvn org.apache.maven.plugins:maven-dependency-plugin:2.10:tree -Dverbose
# or Gradle dependencies task
> gradle dependencies
```
