### ISSUE TITLE
Ktor GraphQL server documentation

### ISSUE THREAD

**Issue by Czocher** [ExpediaGroup/graphql-kotlin#860]
**Describe the solution you'd like**
I'd like to use this project with [Ktor](https://ktor.io/) but the documentation seems to be lacking for any framework other than Spring. I believe it would be nice to improve the documentation with some other Kotlin frameworks taken into account, Ktor being one of them. At least some getting started docs would be perfect.

**Comment by smyrick** [comment]
@Czocher If you have a working example PRs are always welcome. We do not directly use Ktor as a server library in Expedia Group so we would not have the knowledge to cover all the use cases appropriately. 

All our libraries (other than `graphql-kotlin-spring-server` and `graphql-kotlin-spring-client` of course) should be able to work with any webframework.

There is a minimal example of how to setup a Spark app here: https://github.com/ExpediaGroup/graphql-kotlin/tree/master/examples/spark

**Comment by smyrick** [comment]
Anyone coming in, adding a new module `examples/kor-server` would be a great place to document the set up and maybe showing any issues or things that are more complicated that we could fix in the library.

**Comment by sondr3** [comment]
I have a working Ktor/GraphQL Kotlin/Exposed-project for a student organization that you can take a look at if you want to. The GraphQL configuration is [here](https://github.com/echo-karriere/backend/blob/master/src/graphql/GraphQLConfiguration.kt), and an example query resolver is [here](https://github.com/echo-karriere/backend/blob/master/src/category/CategoryQueryResolver.kt). It was fairly straight forward to get it working, I might be able to contribute an example/documentation in the near future when I have some time to spare :smile:

**Comment by dariuszkuc** [comment]
Example project added in #951
