### ISSUE TITLE
Kotlin data classes to TypeDefinitionRegistry

### ISSUE THREAD

**Issue by claymccoy** [ExpediaGroup/graphql-kotlin#863]
From the high level usage I see in the docs, this project isn't actually helpful for me to generate my GraphQL schema from Kotlin data classes. I don't want to have to create a top level query object with methods and arguments. That is redundant. I just want to supply some classes and have this top level query with methods and args generated from those classes. Avoiding duplication is part the reason I wanted to use this library.

What I really need is a way to turn my Kotlin data classes into a graphql.schema.idl.TypeDefinitionRegistry that I can then hand to something else. I imagine you must be doing something simlar here with reflection. Are there some internals that I can use so that I don't have to write that all over again?

Thanks!

**Comment by smyrick** [comment]
@claymccoy 

> I just want to supply some classes and have this top level query with methods and args generated from those classes

That is exactly what the [graphql-kotlin-schema-generator ](https://github.com/ExpediaGroup/graphql-kotlin/tree/master/graphql-kotlin-schema-generator) does.

You just have to call the `toSchema` with your Kotlin classes and it generates a `GraphQLSchema` object from `graphql-java`.

From there you can use that object to start a server, or use `graphql-kotlin-spring-server` which handles the server logic for you

**Comment by claymccoy** [comment]
Right, I am familiar with the intended use and I am trying to communicate how id doesn't fit my needs. Using toSchema doesn't do enough of the generation for me and outputs a target that I don't want.
1) I shouldn't have to create the Query object if I just want all of my classes to be top level queries.
2) I also need to use another tool (neo4j-graphql-java) which needs either:
* the schema String
* graphql.schema.idl.TypeDefinitionRegistry.

I'd rather not rewrite all the reflection logic that you already have, but I want my model classes to output one of the two types used by neo4j-graphql-java above.

I was looking to "abuse" your library by doing one of the following.
* Directly use the functions that do the conversion using Kotlin reflection, but they are all internal.
* Putting my model in as additional types, letting your library generate the GraphQLSchema, and then trying to turn the GraphQLObjectTypes into ObjectTypeDefinitions.

**Comment by claymccoy** [comment]
More directly I want to convert a Kotlin class like this:
```
@NodeEntity
data class Artifact(
        val groupId: String,
        val artifactId: String,
        val version: String,
        @Relationship(type = "IN_REPO", direction = Relationship.OUTGOING) val repo: ArtifactoryRepo?,
        @Relationship(type = "DEPENDS_ON", direction = Relationship.OUTGOING) val dependencies: Set<Artifact>,
        @Relationship(type = "DEPENDS_ON", direction = Relationship.INCOMING) val consumers: Set<Artifact>
) {
    @Id val id: String = "$groupId:$artifactId:$version"
    val name: String = "$artifactId:$version"
}
```

to this:

```
type Artifact {
            id: ID!
            name: String!
            groupId: String!
            artifactId: String!
            version: String!
            repo: ArtifactoryRepo @relation(name:"IN_REPO", direction:OUT)
            dependencies: [Artifact] @relation(name:"DEPENDS_ON", direction:OUT)
            consumers: [Artifact] @relation(name:"DEPENDS_ON", direction:IN)
        }
```

And then let another library consume the generated text schema. Or a TypeDefinitionRegistry rather than the actual text representation and skip a step. Using toSchema forces me to send it a dummy Query object that can't be empty and it gives me a full GraphQLSchema taht I have to figure out how to backward engineer into just the schema types as a String or TypeDefinitionRegistry.

**Comment by smyrick** [comment]
Ok, I see. So you want access to the internal method `generateGraphQLType`

https://github.com/ExpediaGroup/graphql-kotlin/blob/7f7eb51e78e1ac989d133a9d7dab7f4b5145bdb2/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateGraphQLType.kt#L36

Yea, I don't know if we want to expose these internals as you still have to provide a `SchemaGenerator` class as an argument which contains the shared cache and other references on generating the additional types.

I think the best approach for you is to create a dummy top level query and instead of having to use all the types in the actual schema you can provide then as `additionalTypes`. This will generate them and all the nested classes as well and then from there you can get the types back out from the schema or call `GraphQLTypeUtil.simplePrint()`

**Comment by claymccoy** [comment]
I got this working using onRewireGraphQLType(). I use reflection on the data class myself and construct directives from the annotations on the class. Let me know if you see improvements with the way I am using your library. I'm pretty sure I am not using enum types as intended, but it works! :)

```
import com.expediagroup.graphql.hooks.SchemaGeneratorHooks
import graphql.Scalars
import graphql.schema.*
import org.neo4j.ogm.annotation.Id
import org.neo4j.ogm.annotation.Relationship
import java.lang.IllegalArgumentException
import kotlin.reflect.KClass

class CypherSchemaGeneratorHooks(model: Collection<KClass<*>>) : SchemaGeneratorHooks {

    val modelClassesByName = model.associateBy { it.simpleName }

    val directionOut = GraphQLEnumType.newEnum()
            .name("OUT")
            .value("OUT")
            .build()

    val directionIn = GraphQLEnumType.newEnum()
            .name("IN")
            .value("IN")
            .build()

    val directionBoth = GraphQLEnumType.newEnum()
            .name("BOTH")
            .value("BOTH")
            .build()

    override fun onRewireGraphQLType(generatedType: GraphQLSchemaElement, coordinates: FieldCoordinates?, codeRegistry: GraphQLCodeRegistry.Builder?): GraphQLSchemaElement {
        val rewiredType = super.onRewireGraphQLType(generatedType, coordinates, codeRegistry)
        if (rewiredType is GraphQLFieldDefinition) {
            val typeBuilder = GraphQLFieldDefinition.newFieldDefinition(rewiredType)
            val field = coordinates?.let { fieldCoordinates ->
                modelClassesByName[fieldCoordinates.typeName]?.let { klass ->
                    klass.java.declaredFields.find { it.name == fieldCoordinates.fieldName }
                }
            }
            field?.let {
                field.getAnnotation(Relationship::class.java)?.let {
                    typeBuilder.withDirective(constructRelationDirective(it))
                }
                field.getAnnotation(Id::class.java)?.let {
                    var idType: GraphQLOutputType = Scalars.GraphQLID
                    if (rewiredType.type is GraphQLNonNull) {
                        idType = GraphQLNonNull.nonNull(idType)
                    }
                    typeBuilder.type(idType)
                }
            }
            return typeBuilder.build()
        }
        return rewiredType
    }

    private fun constructRelationDirective(relationship: Relationship) : GraphQLDirective {
        val direction = when (relationship.direction) {
            Relationship.OUTGOING -> directionOut
            Relationship.INCOMING -> directionIn
            Relationship.UNDIRECTED -> directionBoth
            else -> throw IllegalArgumentException("Invalid relationship direction: ${relationship.direction}")
        }
        return GraphQLDirective.newDirective()
                .name("relation")
                .argument(GraphQLArgument.newArgument()
                        .type(Scalars.GraphQLString)
                        .name("name")
                        .value(relationship.type))
                .argument(GraphQLArgument.newArgument()
                        .type(direction)
                        .name("direction")
                        .value(direction.name))
                .build()
    }

}
```

This is a unit tests the demonstrates what I am trying to do. I am turning my neo4j data classes into a GraphQL schema with the neo4j directives.
```
import dev.minutest.junit.JUnit5Minutests
import dev.minutest.rootContext
import org.neo4j.ogm.annotation.Id
import org.neo4j.ogm.annotation.NodeEntity
import org.neo4j.ogm.annotation.Relationship
import strikt.api.expectThat
import strikt.assertions.isEqualTo

class SchemaGeneratorTest : JUnit5Minutests {

    val generator = SchemaGenerator()

    @NodeEntity
    data class TestArtifact(
            val groupId: String,
            val artifactId: String,
            val version: String,
            @Relationship(type = "IN_REPO", direction = Relationship.OUTGOING) val repo: TestRepo?,
            @Relationship(type = "DEPENDS_ON", direction = Relationship.OUTGOING) val dependencies: List<TestArtifact>,
            @Relationship(type = "DEPENDS_ON", direction = Relationship.INCOMING) val consumers: List<TestArtifact>
    ) {
        @Id
        val id: String = "$groupId:$artifactId:$version"
        val name: String = "$artifactId:$version"
    }

    @NodeEntity
    data class TestRepo(
            val name: String,
            @Id val url: String,
            @Relationship(type = "IN_REPO", direction = Relationship.INCOMING) val artifacts: List<TestArtifact>?
    )

    fun tests() = rootContext {
        test("convertClassesToSchema") {
            val generatedSchema = generator.generateSchema(setOf(
                    TestArtifact::class,
                    TestRepo::class
            ))
            expectThat(generatedSchema).isEqualTo("""
            type TestArtifact {
              artifactId: String!
              consumers: [TestArtifact!]! @relation(direction : IN, name : "DEPENDS_ON")
              dependencies: [TestArtifact!]! @relation(direction : OUT, name : "DEPENDS_ON")
              groupId: String!
              id: ID!
              name: String!
              repo: TestRepo @relation(direction : OUT, name : "IN_REPO")
              version: String!
            }

            type TestRepo {
              artifacts: [TestArtifact!] @relation(direction : IN, name : "IN_REPO")
              name: String!
              url: ID!
            }
            """.trimIndent())
        }
    }
}
```

This is how I am using it in my app. I use a bogus Query object and give it my data types as additional types. I bypass the need to tell it packages by using reflection on the classes and getting their packages, CypherSchemaGeneratorHooks about addes the extra directives, and I use SchemaPrinter to produce a text representation of the GraphQL schema.

```
import com.expediagroup.graphql.SchemaGeneratorConfig
import com.expediagroup.graphql.TopLevelObject
import com.expediagroup.graphql.generator.SchemaGenerator
import graphql.schema.idl.SchemaPrinter
import io.armory.astrolabe.graphql.CypherSchemaGeneratorHooks
import kotlin.reflect.KClass
import kotlin.reflect.full.createType

class SchemaGenerator {

    private val schemaPrinter = SchemaPrinter(SchemaPrinter.Options.defaultOptions()
            .includeDirectives(true)
            .includeScalarTypes(true)
            .includeSchemaDefinition(true)
            .includeIntrospectionTypes(false)
    )

    class Query {
        fun placeholder() = 1
    }

    fun generateSchema(model: Collection<KClass<*>>) : String {
        val packages = model.map { it.java.`package`.name }.distinct()
        val config = SchemaGeneratorConfig(
                supportedPackages = packages,
                hooks = CypherSchemaGeneratorHooks(model)
        )
        val schema = SchemaGenerator(config).generateSchema(
                listOf(TopLevelObject(Query())),
                emptyList(),
                emptyList(),
                model.map { it.createType() }.toSet()
        )

        return schema.additionalTypes.map {
            schemaPrinter.print(it)
        }.joinToString("").trimEnd()
    }

}
```

**Comment by smyrick** [comment]
@claymccoy Would having a separate `TypeGenerator` be more useful?

You would have to call this for every type in your model

https://github.com/ExpediaGroup/graphql-kotlin/pull/873

**Comment by claymccoy** [comment]
Maybe. I read the comments on that issue. I feel like I am misusing your library, but it is working for me. Mainly asking if there was a better way to accomplish this.

**Comment by claymccoy** [comment]
Closing this as it seems like I am using the library as intended, even it is a little awkward for my use case.
