### ISSUE TITLE
Two data classes are generated are from the same type

### ISSUE THREAD

**Issue by haagenhasle** [ExpediaGroup/graphql-kotlin#864]
I'm using graphql-kotlin version 3.6.1. 

I'm generating code base on a schema and a query-file. In three different places in the query-file, the same type is referenced. (FolkeregisterMetadata). When graphql-kotlin generates code for this, it generate two data classes instead of one, FolkeregisterMetadata and FolkeregisterMetadata1. The first one is used two places, and the second one the third place. I can't find any differences in the query that should cause this, so I assume it could be a bug? I would have expected just one FolkeregisterMetadata-dataclass to be generated.

I have zipped up a small project that should show this, where the query is included. (The schema is in a public github repo, and is referenced in the build)

[TestKotlinGradle.zip](https://github.com/ExpediaGroup/graphql-kotlin/files/5167964/TestKotlinGradle.zip)

**Comment by smyrick** [comment]
Hello, for graphql type-safe clients we need to have separate classes based of your field selection. That is because as a client you are not required to select all the fields. So the easiest way for us to handle that, and make sure that we don't populate used fields as null as that would imply the server returned null when it really didn't, is to have two separate classes

See: https://github.com/ExpediaGroup/graphql-kotlin/issues/815

**Comment by smyrick** [comment]
If you do have a example of an unexpected, error please include a link to a Github repo with a branch we can clone instead of a zip file

**Comment by haagenhasle** [comment]
You can take a look at https://github.com/haagenhasle/GraphQLKotlinTest

You can see there that Folkeregistermetadata2 is actually used twice, and Folkeregistermetadata is used once. So it seems you are able to reuse a class (or I would have had a Folkeregistermetadata3 as well?), so why don't you do it every time? 

I saw dariuszkuc's comment on the issue you linked to, and he mentioned "different selection sets for the same object". But in my case, I have the same selection set every time.

This is not a big deal, we can easily work with two identical classes. It is merely an inconvenience. I really like the library you have made, and thank you for your effort! :)

**Comment by dariuszkuc** [comment]
Thanks for reporting. Sounds like a bug -> if you have same selection set it should reuse same data class. I'll take a look!
