### ISSUE TITLE
Property generation not taking @GraphQLName into consideration

### ISSUE THREAD

**Issue by skroll** [ExpediaGroup/graphql-kotlin#866]
**Library Version**
3.6.1

**Describe the bug**
It appears that the property generator for any object types is not taking @GraphQLName into affect when generating the field coordinates in the code registry. When I rename a field, I simply get an immediate error when trying to fetch something, with a `The field at path '/foo/bar' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value` error.

**To Reproduce**
A simple example shows this error.
```
@SpringBootApplication
class Application

@Component
class FooQuery : Query {
  fun findFoo(): Foo {
    return Foo("hello, world")
  }
}

class Foo(
  @GraphQLName("baz") val bar: String
)

fun main(args: Array<String>) {
  runApplication<Application>(*args)
}
```

**Expected behavior**
The correct value to be returned.

Looking at the code registry that's generated, it still contains the coordinates for the property as `Foo:bar`, and looking at this line:
https://github.com/ExpediaGroup/graphql-kotlin/blob/346e462a778157814fa2abc7a766be25dfbfa589/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateProperty.kt#L53
I think it's simply not using the `fun KProperty<*>.getPropertyName(parentClass: KClass<*>): String?` variant to resolve this before stashing it in the registry, although I'll admit I'm not super well-versed in the workings of the field coordinates in the graphql-java library.

**Comment by skroll** [comment]
So I've started working on a branch that will take care of the issue. The initial version seems to work, although some existing tests fail (because they are also just using `prop.name` for the coordinates), but it looks like a lot of the tests for the property generator just check that the code registry is returning a `PropertyDataFetcher` for the given coordinates. The graphql-java library itself will ALWAYS return a `PropertyDataFetcher` regardless if it exists or not. It seems like some of these existing tests aren't catching the case that a `DataFetcher` is actually registered correctly. I'm going to look into it a bit further.

This is what is from graphql-java's `GraphQLCodeRegistry':
```
private static DataFetcher<?> getDataFetcherImpl(FieldCoordinates coordinates, GraphQLFieldDefinition fieldDefinition, Map<FieldCoordinates, DataFetcherFactory<?>> dataFetcherMap, Map<String, DataFetcherFactory<?>> systemDataFetcherMap, DataFetcherFactory<?> defaultDataFetcherFactory) {
    assertNotNull(coordinates);
    assertNotNull(fieldDefinition);

    DataFetcherFactory<?> dataFetcherFactory = systemDataFetcherMap.get(fieldDefinition.getName());
    if (dataFetcherFactory == null) {
        dataFetcherFactory = dataFetcherMap.get(coordinates);
        if (dataFetcherFactory == null) {
            dataFetcherFactory = defaultDataFetcherFactory;
        }
    }
    return dataFetcherFactory.get(newDataFetchingFactoryEnvironment()
            .fieldDefinition(fieldDefinition)
            .build());
}
```

So this is definitely giving some false positives.

**Comment by smyrick** [comment]
@skroll I have fixed this in https://github.com/ExpediaGroup/graphql-kotlin/pull/870

**Comment by skroll** [comment]
Forgot to respond, but this works great now, thanks!
