### ISSUE TITLE
Missing bugfix in latest ktor-client patch

### ISSUE THREAD

**Issue by MarkusLund** [ExpediaGroup/graphql-kotlin#875]
Hi,

I believe the latest release of `graphql-kotlin-ktor-client:4.0.0-alpha.2` didnt include the recent header bugfix (https://github.com/ExpediaGroup/graphql-kotlin/commit/d6f7221687b2ca3057eeae4b589b3f349e045772). 

The main package `graphql-kotlin-client:4.0.0-alpha.2` includes the bugfix, making the introspectSchema task working properly. But the client still has the duplicate header bug.

**Comment by smyrick** [comment]
Yep, we need to update.

This was pushed in https://github.com/ExpediaGroup/graphql-kotlin/releases/tag/4.0.0-alpha.3
