### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by smyrick** [ExpediaGroup/graphql-kotlin#88]
We have reached a slow down in changes. We should release a 1.0.0 cut and have this library officially released.

Before we do that we need to make any last breaking changes. Are there any requests?

**Comment by d4rken** [comment]
Lot's of custom functionality can be provided via custom directives. I think it would be nice if we could offer some kind of plugin system where devs can just hook-in a custom directive with a single line of code. 

My idea would be that if a dev needs e.g. default-values (#53) they could do something like `include graph-ql-kotlin:default-values:1.0` and then in code `generator.registerDirectiveProvider(strawberry)` and be able to use new fancy annotations :tada: .

Looking into this over the weekend, could require some breaking changes...

**Comment by Swissbite** [comment]
It would be great to update the wiki and clean up as soon as you released the version 1.0.

To clean up: artifactId, links to renamed classes (like https://github.com/ExpediaDotCom/graphql-kotlin/wiki/Basics) and outdated examples which will not work out of the box.

**Comment by smyrick** [comment]
@ExpediaDotCom/graphql-kotlin Do we want to move the repo to the new organization before we release 1.0.0 since changing the package name is breaking? https://github.com/ExpediaGroup

`com.expediagroup.graphql`

**Comment by dkuc84** [comment]
> @ExpediaDotCom/graphql-kotlin Do we want to move the repo to the new organization before we release 1.0.0 since changing the package name is breaking? https://github.com/ExpediaGroup
> 
> `com.expediagroup.graphql`

Yes

**Comment by aarestu** [comment]
I can't wait for this library v.1.0.0 to be officially released

**Comment by smyrick** [comment]
@aarestu We just finished all our issues for the 1.0.0 milestone. We are going to release RC7 and then get one last PR in. Do you have any additional feedback of something you would like to see?

**Comment by aarestu** [comment]
@smyrick awesome! I just started trying to implement and reading the code of in this project. Maybe I can help or contribute something

**Comment by dariuszkuc** [comment]
released
