### ISSUE TITLE
Using fragments generates multiple classes

### ISSUE THREAD

**Issue by pjwalstrom** [ExpediaGroup/graphql-kotlin#903]
**Library Version**
3.6.4

**Describe the bug**
Multiple similar classes are generated when fragments are used. Similar to https://github.com/ExpediaGroup/graphql-kotlin/issues/864, which was fixed in https://github.com/ExpediaGroup/graphql-kotlin/pull/884

**To Reproduce**
https://github.com/haagenhasle/GraphQLKotlinTest
`./gradlew build`
Multiple classes of type Folkeregistermetadata are generated

**Expected behavior**
There should be only one class of type Folkeregistermetadata

**Comment by dariuszkuc** [comment]
@pjwalstrom is your fragment query actually valid? i.e. shouldn't `fragment folkeregistermetadata on folkeregistermetadata` be `fragment folkeregistermetadata on Folkeregistermetadata` (just tried changing it to the latter and it worked correctly).

It's interesting that the query was generated but there is no `folkeregistermetadata` type in the schema. Names are case sensitive so it is an invalid query (https://spec.graphql.org/June2018/#sec-Names). It looks like we don't validate whether fragments refer to the valid type, I'll see whether we can throw an error in those cases.

**Comment by pjwalstrom** [comment]
You are right, this bug was incorrectly reported (but seems like you have discovered another...)

Anyway, the query is now updated and there are multiple Folkeregistermetadata generated. However, the reason for this is that we use a ScalarConverter for DateTime. And it does not have anything to do with fragments, it seems. Should I update this issue to reflect that, or should I report another one to avoid confusion?

**Comment by dariuszkuc** [comment]
No need to create separate issue. I got it fixed in #916
