### ISSUE TITLE
Gradle Plugin Documentation says use `listOf` but `MutableList` is expected

### ISSUE THREAD

**Issue by xetra11** [ExpediaGroup/graphql-kotlin#906]
**Library Version**
4.0.0-alpha.6

**Describe the bug**
using `listOf` for 
```
 queryFiles = listOf(file("${project.projectDir}/src/main/resources/queries/MyQuery.graphql"))
```
does not work and throws syntax errors. The error explains it needs a `MutableList`

**To Reproduce**
Use the gradle `graphql.client` plugin option above with `listOf()`

**Expected behavior**
The documentation should clarify that `mutableListOf` should be used

**Comment by smyrick** [comment]
It looks like we can fix this by changing our code instead : https://github.com/ExpediaGroup/graphql-kotlin/blob/5f725bb688934db57b93026d20fddee6a75a19ee/plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt#L59
