### ISSUE TITLE
No value has been specified for property 'packageName' when running `graphqlGenerateTestClient`

### ISSUE THREAD

**Issue by xetra11** [ExpediaGroup/graphql-kotlin#919]
**Library Version**
4.0.0-alpha.7

**Describe the bug**
When I run `gradle clean build` I receive and error:
```
7:35:46 AM: Executing tasks 'clean build'...

> Task :clean

> Task :graphqlIntrospectSchema
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8
> Task :graphqlGenerateClient
> Task :compileKotlin
> Task :compileJava NO-SOURCE
> Task :processResources
> Task :classes
> Task :bootJar
> Task :inspectClassesForKotlinIC
> Task :jar SKIPPED
> Task :assemble
> Task :checkFormatIntegrationTest SKIPPED
> Task :checkFormatMain SKIPPED
> Task :checkFormatTest SKIPPED
> Task :checkFormat UP-TO-DATE
> Task :graphqlGenerateTestClient FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings
8 actionable tasks: 8 executed

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':graphqlGenerateTestClient' (type 'GraphQLGenerateClientTask').
> No value has been specified for property 'packageName'.
```

**To Reproduce**
Run `gradle clean graphqlGenerateTestClient` with this config:
```
graphql {
    client {
        allowDeprecatedFields = true
        clientType = GraphQLClientType.WEBCLIENT
        packageName = "com.mycompany.app.network.graphql"
        endpoint = "http://myendpoint/graphql"
    }
}
```
As you can see I am using `packageName` however not explicitly for a `testClient` since I was not able to find any config for a `testClient` in that api.

**Expected behavior**
I was expecting it to simple work like before. For some reason it failed to work I think as soon as I started to write unit tests with the logic using the client but I am unsure.

**Comment by xetra11** [comment]
I worked around this problem by `gradle clean build -x graphqlGenerateTestClient`. However I wonder why it is enforcing the generation of a test client? My unit tests are using the non-test client.

**Comment by dariuszkuc** [comment]
[As per documentation](https://expediagroup.github.io/graphql-kotlin/docs/plugins/gradle-plugin#extension) `graphql` extension is a shorthand for obtaining schema (either through introspection or SDL) and then generating the client. In order to generate test client, you should configure the task directly - see [documentation](https://expediagroup.github.io/graphql-kotlin/docs/plugins/gradle-plugin#generating-test-client).

If you unit tests are using non-test client -> why do you need to run the `graphqlGenerateTestClient`?

**Comment by xetra11** [comment]
@dariuszkuc I don't need to run it. In fact I have no idea why it is hooked into the build process

**Comment by dariuszkuc** [comment]
Can you provide a repro? `graphqlGenerateTestClient` should not be registered by default

**Comment by xetra11** [comment]
@dariuszkuc trying to build repro repo (reprository?) and will link it here in a few

**Comment by xetra11** [comment]
Ok it looks like the issue is introduced by our own IntegrationTest gradle plugin
