### ISSUE TITLE
Not possible to have a custom context for subscription methods

### ISSUE THREAD

**Issue by gerald24** [ExpediaGroup/graphql-kotlin#945]
**Library Version**
com.expediagroup:graphql-kotlin-spring-server:4.0.0-alpha.7

**Describe the bug**
Unable to provide a custom context for subscriptions

**To Reproduce**
Subscription Example (it's not important here if context is of type GraphQLContext or any other, because currently a new instance of graphql.GraphQLContext will be provided anyway - see GraphQLRequest extension below):

```
import com.expediagroup.graphql.spring.operations.Subscription
import graphql.GraphQLContext
import org.springframework.stereotype.Component
import reactor.core.publisher.Flux
import java.time.Duration
import java.util.*

@Component
class NotificationSubscription : Subscription {

    fun notifications(context: GraphQLContext): Flux<String> {

        return Flux.interval(Duration.ofSeconds(5))
            .map {
                UUID.randomUUID().toString()
            }
    }
}
```

is not possible since on start we get an exception:

```
Caused by: com.expediagroup.graphql.exceptions.TypeNotSupportedException: Cannot convert graphql.GraphQLContext since it is not a valid GraphQL type or outside the supported packages
```

Adding "graphql" to `graphql.packages` config property is not desired and will result in an exception anyway:

```
Caused by: com.expediagroup.graphql.exceptions.EmptyInputObjectTypeException: Invalid GraphQLContextInput input object type - input object does not expose any fields.
```

But just noted - `graphql.GraphQLContext` is the default context, generated by the GraphQLRequest#toExecutionInput extension,  if the Mono-subscriber-context will not have one:

```
fun GraphQLRequest.toExecutionInput(graphQLContext: Any? = null, dataLoaderRegistry: DataLoaderRegistry? = null): ExecutionInput =
    ExecutionInput.newExecutionInput()
        .query(this.query)
        .operationName(this.operationName)
        .variables(this.variables ?: emptyMap())
        .context(graphQLContext ?: GraphQLContext.newContext().build())
        .dataLoaderRegistry(dataLoaderRegistry ?: DataLoaderRegistry())
        .build()
```

Here is the default implementation of the `SubscriptionHandler` (`SimpleSubscriptionHandler`):

```
    override fun executeSubscription(graphQLRequest: GraphQLRequest): Flux<GraphQLResponse<*>> = Mono.subscriberContext()
        .flatMapMany { reactorContext ->
            val graphQLContext = reactorContext.getOrDefault<Any>(GRAPHQL_CONTEXT_KEY, null)
            graphQL.execute(graphQLRequest.toExecutionInput(graphQLContext))
                .getData<Publisher<ExecutionResult>>()
                .toFlux()
                .map { result -> result.toGraphQLResponse() }
                .onErrorResume { throwable ->
                    val error = SimpleKotlinGraphQLError(throwable).toGraphQLKotlinType()
                    Flux.just(GraphQLResponse<Any>(errors = listOf(error)))
                }
        }
```

But since I'm not able to add my context to the subscriber context (e.g  in my custom `ApolloSubscriptionHooks`), the evaluation of `reactorContext.getOrDefault<Any>(GRAPHQL_CONTEXT_KEY, null)` will always be null, and therefore the GraphQLRequest.toExecutionInput extension will always offer a new instance of graphql.GraphQLContext.

Actually, the `ApolloSubscriptionProtocolHandler` offers a hook for `onOperation`, but will not link to the result of `startSubscription` and therefore the chain is broken

```
class ApolloSubscriptionProtocolHandler
  ...
    private fun onOperation(operationMessage: SubscriptionOperationMessage, session: WebSocketSession, graphQLContext: Any?): Flux<SubscriptionOperationMessage> =
        subscriptionHooks.onOperation(operationMessage, session, graphQLContext)
            .flatMapMany { startSubscription(operationMessage, session) 
```

**Expected behavior**
```
@Component
class NotificationSubscription : Subscription {

    fun notifications(context: MyContext): Flux<String> {

       // any logic with context ...

        return Flux.interval(Duration.ofSeconds(5))
            .map {
                UUID.randomUUID().toString()
            }
    }
}
```

As far as I understand reactive I should be possible to add my context like this:
```
  startSubscription(operationMessage, session).subscriberContext { it.put(GRAPHQL_CONTEXT_KEY, MyContext(...)) }
```

**My application**

I can extract the handshake info for the web socket connection in my custom `ApolloSubscriptionHooks` through the WebSocketSession, which holds my (JWT) access token as query parameter.  With this token I can provide a user context to my subscription method .

**Comment by dariuszkuc** [comment]
Hello! Thanks for raising this - GraphQL context should be populated in a WebFilter through a custom `GraphQLContextFactory`, see https://expediagroup.github.io/graphql-kotlin/docs/spring-server/spring-graphql-context for details.

As for the default `GraphQLContext` it looks like a bug to me. Originally we were using `com.expediagroup.graphql.execution.EmptyGraphQLContext` for default value which implements the corresponding interface. Context from `graphql-java` obviously doesn't implement our interface so it blows up.

**Comment by gerald24** [comment]
For query methods through http(s) this works like a charm.

Just to be concrete (and maybe someone else need this infos too):

On the client side I use Apollo and splitLink, which sends the token as query parameter for subscriptions (not a security issue when using secure websockets wss), and for all other requests the token is sent as Bearer in the authentication header.

The backend server uses a OAuth2 resource server for authentication (keycloak)

```
 @Bean
    fun securityWebFilterChain(
        http: ServerHttpSecurity
    ): SecurityWebFilterChain {

        return http {
           ...
          oauth2ResourceServer {
            // activate query parameter for websockets (this is not an issue for secure connections, such as wss://)
            bearerTokenConverter = ServerBearerTokenAuthenticationConverter().apply { setAllowUriQueryParameter(true) }

            // converts jwt token to keycloak user principal
            jwt { jwtAuthenticationConverter = KeycloakJwtAuthenticationConverter() }
          }
          ...
          authorizeExchange {
             ...
            authorize(ServerWebExchangeMatchers.pathMatchers(HttpMethod.OPTIONS, "/${graphQLConfigurationProperties.endpoint}"), permitAll)

            authorize(antPattern = "/${graphQLConfigurationProperties.endpoint}", hasAuthority("xxx"))
            authorize(antPattern = "/${graphQLConfigurationProperties.subscriptions.endpoint}", hasAuthority("xxx"))

            if (graphQLConfigurationProperties.playground.enabled) {
                authorize(antPattern = "/${graphQLConfigurationProperties.playground.endpoint}", permitAll)
            }
            if (graphQLConfigurationProperties.sdl.enabled) {
                authorize(antPattern = "/${graphQLConfigurationProperties.sdl.endpoint}", permitAll)
            }

            authorize(anyExchange, authenticated)
          }
...
```

The context factory looks like:
(AuthenticatedUser will be created by KeycloakJwtAuthenticationConverter)

```
@Component
class AuthenticatedGraphQLContextFactory : GraphQLContextFactory<AuthenticatedGraphQLContext> {

    override suspend fun generateContext(request: ServerHttpRequest, response: ServerHttpResponse): AuthenticatedGraphQLContext {
        val reactorContext = coroutineContext[ReactorContext]
        val securityContext = reactorContext?.context?.getOrDefault<Mono<SecurityContext>>(SecurityContext::class.java, null) ?: Mono.empty()
        val user = securityContext.map { it.authentication?.principal as? AuthenticatedUser }

        return AuthenticatedGraphQLContext(
            user = user,
            request = request,
            response = response
        )
    }
}

class AuthenticatedGraphQLContext(
    val user: Mono<AuthenticatedUser?>,
    val request: ServerHttpRequest,
    val response: ServerHttpResponse) : GraphQLContext
```

And a sample query like this:

```
@Component
class SampleQuery : Query {

    fun myquery(context: AuthenticatedGraphQLContext, anyparameter: String): List<MyResult> {
        val user = context.user.block() ?: return emptyList()
        ...
        // return result depending on user context ...
```


Would be awesome if the context will also be available for subscriptions.

I don't know yet if the (same) security context will be also available for websockets after the webfilter chain. But in the worst cast I get the query parameter (token) in the handshake info, which is available through the `WebSocketSession` in `ApolloSubscriptionHooks`. But anyhow I can not modify the mono subscriber context.
